### ISSUE TITLE
Double voting

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#105]
Při editování zdroje Missio došlo ke zdvojení hlasování. Najednou se tam objevilo hlasování z wa adminu. Nevím, jestli teď něco neděláš s databází, nicméně dvě souběžné hlasování by se neměly stát :)
![doublevoting](https://cloud.githubusercontent.com/assets/10117117/8473487/450eb4dc-20aa-11e5-84f2-be2d11d5d594.png)

**Comment by Visgean** [comment]
tak to je z toho importu ne

**Comment by Visgean** [comment]
Jakoze import automaticky vytvoril vsechny ty nove hlasovani plus jeste naimportoval stare, na to uz mam issue
