### ISSUE TITLE
Different font color for seeds

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#106]
Napadlo, že by bylo fajn, pokud by barva písma semínka na stránce zdroje reflektovala druh semínka. A také by se semínka měla řadit tak, aby nahoře byly "běžná semínka", a pak ty ostatní

Mohlo by to vypadat nějak takto:
- běžné semínko v modré barvě, jak je to teď
- červeně vyřazené semínko
- černě nevydávané semínko, třeba i bez hyperlinku
- oranžově semínko s přesměrování
- zeleně časové ohraničené semínko

barvy jsou jen ilustrativní

**Comment by Visgean** [comment]
Zhruba tak jsem to udelal...
