### ISSUE TITLE
Scheduling emails 

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#107]
Při rozvrhování emailů se zobrazuje vždy o jeden zdroj navíc. To znamená, že je tam osm oken pro editování emailů místo čtyř. A čtyři okna jsou vázana k jinému zdroji

**Comment by Visgean** [comment]
muzes poslat screen?

**Comment by kvasnicaj** [comment]
Udělal jsem ti export do pdf. Je to moc dlouhý. Takto to vypadá u zdroje Missio

[Rozvrhnout smlouvy | Semínkáč (kopie).pdf](https://github.com/WebArchivCZ/Seeder/files/477/Rozvrhnout.smlouvy.Seminkac.kopie.pdf)
