### ISSUE TITLE
Přidat zdroj - navrhnuto kurátorem

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#109]
Při přidávání nového zdroje chybí možnost navrhnuto: kurátor (aktuálně je tam vydavatel, ISSN a návštěvník), ve zdroji je pak navrhnuto prázdné (none)

**Comment by kvasnicaj** [comment]
tady došlo k nepochopení situace :) u zdroje, který nebude mít při přidávání vyplněno pole "navrhnuto", tak defaultně nastavit hodnotu navrhnuto kurátorem, místo none

**Comment by Visgean** [comment]
ok, opravim
