### ISSUE TITLE
Automatická změna stavu zdroje po vložení smlouvy

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#112]
Při vložení smlouvy se musí změnit stav zdroje na „archivuje se“ (u starých zdrojů např. stav "vyd. ignoroval" – po přidání sml. se nezmění, např. u zdroje Judaica Olomoucensia).

**Comment by Visgean** [comment]
Tohle by melo fungovat, nemelo by se tak dit u importovanych = zmrazenych dat.
