### ISSUE TITLE
Frequency - 4x

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#114]
Prosím o přidání frekvence archivace 4x ročně.

**Comment by kvasnicaj** [comment]
Navrhuji frekvence lehce předělat:

Nový seznam frekvencí vč. nových názvů:

- Denně ang. Daily (=fq 365x)
- Týdně | Weekly (=fq 52x)
- Měsíčně | Monthly (=fq 12x)
- Dvouměsíčně | Bi-monthly (=fq 6x)
- Čtvrtletně | Quarterly (=fq 4x)
- Půlročně | Semiannual (=fq 2x)
- Ročně | Annual (=fq 1x)
- Jednorázově | One-Time

První dvě jsou samozřejmě příprava do budoucnosti, dnes je nevyužíváme. Nicméně změna názvosloví mi přijde, že je třeba, protože číslování je nepřehledné. Zároveň si již moc neumím představit další kategorie, tzn. tato řada by mohla být konečná. 

Co vy na to?

**Comment by westfood** [comment]
Já bych to nechal do budoucna klidně i v hodinách, hourly.. oni to někde
tak provozují..

Dne 24. července 2015 14:30 Jaroslav Kvasnica <notifications@github.com>
napsal(a):

**Comment by bjackova** [comment]
Jsem pro, dobře to koresponduje i s periodicitou, kterou knihovna uznává pro seriály. Jen teda ty hodiny mi připadají už dost podrobné.
