### ISSUE TITLE
Přidat vydavatele - nový záznam

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#116]
V případě, že chci přidat úplně nového vydavatele, napíšu jeho název, který není v seznamu - v dalším kroku se mi otevře formulář "Přidat vydavatele", který je úplně prázdný - bylo by lepší, kdyby se tam (do názvu) překopíroval řetězec zadaný už v prvním kroku (nebudeme muset duplicitně znovu zadávat název vydavatele).

**Comment by Visgean** [comment]
Tohle nejde diky tomu ze policko vydavatele v prvnim kroku je zaroven vyhledavacim polickem, muselo by se to resit hodne slozite.
