### ISSUE TITLE
Vložit vydavatele - duplicita

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#117]
Pokud vkládám nový zdroj s novým vydavatelem, hledá duplicitu vydavatele pouze v prvním kroku - výběru z nabídky (hledání pouze podle začátku řetězce). Pokud v druhém kroku do prázdné tabulky "Přidat vydavatele" napíšu název, který je duplicitní a v dtb se už nachází, admin to neodhalí. Je potřeba, aby se prováděla ještě kontrola v tomto kroku a to na celý text, ne jen od začátku slova.

**Comment by Visgean** [comment]
Zadani vydavatele v prvnim kroku neslouzi ke kontrole duplicity, to je tam proste jenom na vyhledavani. 
Pridam v dalsim commitu.
