### ISSUE TITLE
Seznam kategorií konspektu

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/Seeder#118]
Při vkládání nového zdroje se nezobrazí celý seznam kategorií Konspektu. Seznam končí u kategorie Tělesná výchova a sport, zbývajících 5 se nezobrazí, a stále tam chybí čísla u jednotlivých názvů kategorií. (1. Antropologie ...26. Literatura pro děti a mládež).

**Comment by Visgean** [comment]
Seznam se nezobrazuje protoze to neni seznam ale vyhledavaci policko, je tam 20 polozek, po napsani casti konspektu se tam objevi hledany konspek..
