### ISSUE TITLE
Zdroje Technické ne

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#119]
Zdroje uzavřené jako "technické ne" v původním adminu, se zde zobrazují se statusem "odmítnuto v hlasování". Je potřeba je odlišit, označit statusem technické ne.

**Comment by Visgean** [comment]
Tohle bude trochu slozitejsi, v soucasne podobe tam ty qa checks nejsou vubec zaintegrovany a tak jak jsme se o tom bavili tak ani nemeli byt. imho je lepsi podobne veci nechat na komentarich. Muzu to nejak presunout nebo to nechat na starem systemu pro kontrolu... (od toho je tam ten odkaz), ale jinak zdroje nemaji Stav technicke ne, funguje to trochu jinak.
![screenshot from 2015-08-02 15 09 57](https://cloud.githubusercontent.com/assets/193832/9026239/8dc2ddf2-3928-11e5-8cb9-23e7494e94cc.png)

**Comment by Visgean** [comment]
Zkusim najit nejaky takove zdroje a kouknout se co k nim mam za informace

**Comment by Visgean** [comment]
Tohle imho vyresila migrace QA, takze je uz videt v QA.
