### ISSUE TITLE
Anotace versus Komentář

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/Seeder#121]
U zdroje je v "Komentáři" - uvedena anotace, tedy stručný popis zdroje. Ve starém adminu sloužil "Komentář" k poznámkám typu jak probíhá korespondence, je-li zdroj něčím výjimečný apod. "Anotace" by pak měla sloužit ke stručnému popisu. viz zdroj Tramvaj načerno www.tramvaj.cz

**Comment by kvasnicaj** [comment]
tohle jsme už řešili, bude opraveno při novém importu dat. viz issue #85
