### ISSUE TITLE
Uzavřená smlouva versus volební kolo

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/Seeder#122]
U zdroje, kterému byla přiřazena smlouva by nemělo být možné hlasovat. Tento zdroj je uzavřený. Viz. např Ikaros www.ikaros.cz

**Comment by Visgean** [comment]
Duplicitni issue k #83 , vyreseno, na testovaci verzi jsou stara data, nove naimportovana data to mit nebudou.
