### ISSUE TITLE
Chybí mi inforormace o datu vložení zdroje

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/Seeder#123]
Ve starém adminu. bylo pole "Vloženo" docela užiteční inf. (jak dlouho je zdroj navržen - od té doby se mohl změnit, mohu ho znovu oslovit apod.) V nové verzi ho má nahradit  "Created" (??) Moc nerozumím funkci filtru Created. Podle čeho se bude vyhledávat, podle data vložení? nefunguje mi vložení datumu.

**Comment by Visgean** [comment]
Policko created skutecne odkazuje na datum vytvoreni/vlozeni zdroje. Na kalendare k vyhledavani udelam jine issue.
