### ISSUE TITLE
Smlouva platná versus smlouva vypršela u stejného zdroje

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/Seeder#124]
u Zdroje Essentia www.essentia.cz je uvedeno "Stav": Smlouva vypršela, když však smlouvu otevřu jednak je označena zeleně (barva aktivní) ale "Stav" je  Smlouva je platná

**Comment by Visgean** [comment]
http://intranet.webarchiv.cz/wadmin/tables/contracts/view/14 Chyba stareho systemu - smlouva je oznacena jako aktivni.
