### ISSUE TITLE
Smlouva vypršela - ale žádná smlouva není přiřazena

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/Seeder#125]
Zdroj Korona http://www.korona.unas.cz/  - Stav : Smlouva vypršela, chci-li však zjistit více info o smlouvě je hláška Sorry no contracts yet. To by být nemělo

**Comment by Visgean** [comment]
Zadna smlouva nikdy nebyla, ve zdroji je k tomuhle ucelu Legacy URL ktera odkaze do predchoziho sytemu: http://intranet.webarchiv.cz/wadmin/tables/resources/view/31 kde zadna smlouva neni, nektere stavy objektu se mapuji v importu dat jinak.
