### ISSUE TITLE
Více zdrojů u jedné smlouvy

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#130]
Bylo by potřeba přidat možnost přiřadit více zdrojům jednu smlouvu, tzn. pokud vložím smlouvu ke zdroji a poté chci vložit sml. u zdroje stejného vydavatele, admin nabídne možnost přiřadit zdroj k už existující smlouvě stejného vydavatele, tzn. dva nebo více zdrojů budou mít stejné číslo smlouvy. 

(nejsem to teď schopná ověřit v adminu, zda to funguje, protože u starých zdrojů chybí smlouvy a není tedy co k čemu přiřazovat), pokud už to tam máš, tak napiš že to je vyřešené, dík :-)

**Comment by Visgean** [comment]
(Bad issue mentioned)

**Comment by Visgean** [comment]
Pridal jsem i k detailu smlouvy tabulku se zdroji ktere maji tento kontrakt
