### ISSUE TITLE
Dodatky ke smlouvám

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#131]
Souvisí s issue #130 (více zdrojů k jedné smlouvě): Potřebovali bychom do adminu ještě doplnit funkci dodatků, tzn. ve starém adminu to funguje podobně jako propojení, ale kromě připojení zdroje k už existující smlouvě nabídne možnost vytvoření dodatku, což je smlouva s vlastním číslem, pouze je propojená (v poznámce je číslo existující smlouvy daného vydavatele) s další smlouvou. Díky.

**Comment by Visgean** [comment]
OK, zkusim se nad tim zamyslet.

**Comment by Visgean** [comment]
Muzes mi poslat nejaky priklad jak je to ve starem adminu?

**Comment by kvasnicaj** [comment]
<img width="647" alt="snimek obrazovky 2016-04-13 v 10 44 18" src="https://cloud.githubusercontent.com/assets/10117117/14490910/1f71fab2-0165-11e6-8f76-9497dd41fa2c.png">
<img width="640" alt="snimek obrazovky 2016-04-13 v 10 44 54" src="https://cloud.githubusercontent.com/assets/10117117/14490909/1f7196da-0165-11e6-83b6-315f82510aee.png">
<img width="639" alt="snimek obrazovky 2016-04-13 v 10 45 10" src="https://cloud.githubusercontent.com/assets/10117117/14490911/1fa39a68-0165-11e6-8e15-f5c4cefe933c.png">
