### ISSUE TITLE
Heritrix api specs and docs

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#137]

**Comment by westfood** [comment]
Here is API Guide: https://webarchive.jira.com/wiki/display/Heritrix/Heritrix+3.x+API+Guide

If there is prepared cxml configuration in job directory, it should be sufficient just to run: LaunchJob - it will build job from cxml and launch job - if configuraion in cxml is set to not pause after launch, crawl will start. Now it is set to pause, for code based configuration, it is better to set value for pauseAtStart in org.archive.crawler.framework.CrawlController to False.

**Comment by westfood** [comment]
I put more info into: #157

**Comment by Visgean** [comment]
Later.
