### ISSUE TITLE
import of old blacklists for OpenWayback

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#144]

**Comment by westfood** [comment]
This is complete blacklist for OpenWayback. If there domain.tld - it should block all URL from domain. If there is domain.tld/URL - it should block only specified URL. I did not test for quite some time, so i am not sure i escape slashed are neccessary and the behaviour is still same. Before, this was also part of mod_rewrite of .htaccess for apache.

czechboxing.cz/images/stories/FOTOclanky/Cerven2011/boxing\ womann\ 372x192.jpg
divokevino.cz/7515/hrabe.php
divokevino.cz/7515/index.php
divokevino.cz/7615/hrabe.php
divokevino.cz/7615/index.php
divokevino.cz/7715/hrabe.php
fotobasne.cz
is.muni.cz/do/1499/el/estud/pedf/ps09/obchod/web/
is.muni.cz/do/1499/el/estud/pedf/ps09/obchod/web/index.html
www.panna.cz/astrologie.4/ascendent-typologie.310.html
www.panna.cz/astrologie.4/cerna-luna-v-horoskopu-postaveni-v-domech.351.html
www.panna.cz/astrologie.4/cerna-luna-v-horoskopu-postaveni-ve-znamenich.342.html
www.panna.cz/astrologie.4/chiron-v-domech.446.html
www.panna.cz/astrologie.4/jupiter-a-strelec-v-domech.448.html
www.panna.cz/astrologie.4/luna-a-rak-v-domech.340.html
www.panna.cz/astrologie.4/lunarni-uzly-v-domech-ii.452.html
www.panna.cz/astrologie.4/lunarni-uzly-v-domech-ii.452.html
www.panna.cz/astrologie.4/mars-a-beran-v-domech.421.html
www.panna.cz/astrologie.4/merkur-blizenci-a-panna-v-domech.369.html
www.panna.cz/astrologie.4/neptun-a-ryby-v-domech-i.488.html
www.panna.cz/astrologie.4/plutonske-principy-astrologie.419.html
www.panna.cz/astrologie.4/saturn-a-kozoroh-v-domech.469.html
www.panna.cz/astrologie.4/saturnske-principy.377.html
www.panna.cz/astrologie.4/slunce-a-lev-v-domech.336.html
www.panna.cz/astrologie.4/uran-a-vodnar-v-domech.473.html
www.panna.cz/astrologie.4/uranske-principy.378.html
www.panna.cz/astrologie.4/venuse-byk-a-vahy-v-domech.415.html
www.panna.cz/panna/clanek/310--ascendent---typologie.html
www.panna.cz/panna/clanek/336--slunce-a-lev-v-domech.html
www.panna.cz/panna/clanek/340--luna-a-rak-v-domech.html
www.panna.cz/panna/clanek/369--merkur--blizenci-a-panna-v-domech.html
www.panna.cz/panna/clanek/377--saturnske-principy.html
www.panna.cz/panna/clanek/378--uranske-principy.html
www.panna.cz/panna/clanek/415--venuse--byk-a-vahy-v-domech.html
www.panna.cz/panna/clanek/421--mars-a-beran-v-domech.html
www.techcorp.cz

**Comment by westfood** [comment]
For whitelisting URLs in openwayback we use these two classes: https://github.com/WebArchivCZ/OpenWayback-devel/tree/master/src/main/java/org/netpreserve/openwayback/accesscontrol/staticmap

It looks like this:
mgvysociny.cz
www.zdravykrajvysocina.cz
zdravykrajvysocina.cz
www.partnerstvi-vysocina.cz
partnerstvi-vysocina.cz
rowanet.cz
www.rowanet.cz
www.emedocs.cz
emedocs.cz

Class will enable access to all URLs on these domains.

**Comment by westfood** [comment]
Black list

**Comment by Visgean** [comment]
Prozatim jsem to nakopiroval na testovaci server, budeme muset vymyslet jak presne integrovat blacklisty, od toho je #179
