### ISSUE TITLE
API /api/wa_kat/conspect 

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#152]
/api/wa_kat/conspect
   • Ten konspekt / sub-konspekt slovník, co už mi posílal v gistu
   • Měl by být stejný pro všechny, proto není nutná autentizace / další parametry

**Comment by Visgean** [comment]
HTTP GET http://seeder.visgean.me/api/category/

**Comment by Visgean** [comment]
@Bystroushaak

**Comment by Bystroushaak** [comment]
Hm. Tohle API můžeš asi nakonec zrušit. Konspekty budu updatovat ručně.

**Comment by Visgean** [comment]
Netreba rusit. API dobre.
