### ISSUE TITLE
Code generated CXML for Heritrix 3

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#157]
If you want to prepare CXML configuration. Here is our repeating configuration: https://github.com/WebArchivCZ/Crawler-config/blob/master/Domain-crawls/crawler-beans.cxml

Each month there are only only few lines changed. Name and description of job, name of resulting WARCs, path where to write WARC files.

There are few lines which change every year. For instance bdbHistory is where we keep database of URLs and hashes, so we do not store same content again, Heritirx will just make revisit record in WARC file.

**URLs to harvest, URLs to ignore**
Configuration also expects some files to be present, such as: 
value="seeds.txt"
value="../Shared-config/surts.txt"
value="../Shared-config/negative-surts.txt"

seeds.txt tells Heritrix which URLs to crawl, you can check it here: https://github.com/WebArchivCZ/Crawler-config/blob/1657340f656ae4161357bdbf74e8ccef4d8cbf64/Domain-crawls/seeds.txt

Surt files are define special rules for allowing or dissallowing harvesting of specifed websites. Surt files accept SURT format (https://webarchive.jira.com/wiki/display/ARIH/SURT+Rules) or simple +URL format. https://github.com/WebArchivCZ/Crawler-config/tree/1657340f656ae4161357bdbf74e8ccef4d8cbf64/Shared-config
In general surt and negative-surt files are one part of whitelising on blacklisting certains URLS from crawl.

There are also specific regex rules for dissallowing some URLs from crawl thru class org.archive.modules.deciderules.MatchesListRegexDecideRule - I will need to test, if these lists of regex can be put into external file. Regex values for global and local traps are separated under different bean ids. Few lines for example:
      <value>.*/ClanekHodnoceni/.*</value>
      <value>.*/Shared_UserLoginBar\.asp.*</value>
      <value>.*/[0-9]{4,5}\.[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}[^/].*</value>
      <value>.*/[0-9]{5}\.[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}[^/].*</value>

**Special rules for certain URLs**
There are also special overlay sheets, which tells Heritrix to crawl certain URLs slower, faster, with bigger budget etc. Look for Big Budget in CXML file for example.

**Special configuration scenerios**
For whole domain crawls we use hashcrawlmapper and configuration is based on how many Heritrix instance we part of whole domain crawl. 
For intance:
hashCrawlMapper.localName=3 
#Number of crawlers among which to split up the URIs.
hashCrawlMapper.crawlerCount=10 
#Diversions directory should be shared between crawlers per job.
hashCrawlMapper.diversionDir=/mnt/archives/archive12/pre-fetch-diversions

**Comment by Visgean** [comment]
Maybe later.
