### ISSUE TITLE
Specifikuj / definuj pravidla sklizni

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#162]

**Comment by Bystroushaak** [comment]
Je v tom:

- Frekvence sklízení (select / input)

A potom kopec radio buttonů:

- Hloubka (budget)
- Jemnost sklízení
- Local Traps
- Kalendáře
- Youtube videa
- Global reject
- Javascript interpreter

![screenshot at 2016-02-05 16 02 39](https://cloud.githubusercontent.com/assets/227282/12849844/07d4e1d0-cc22-11e5-8a10-0541cb05e213.png)

**Comment by Bystroushaak** [comment]
Dneska pro to ještě hodlám dodělat getter, tak ti pošlu ukázku dictu, jaký bych si představoval.

**Comment by Visgean** [comment]
A tohle je k jednotlive url nebo zdroji?

**Comment by Bystroushaak** [comment]
Co já vim co je u tebe URL a zdroj. Já nic takového nerozišuju.

**Comment by Bystroushaak** [comment]
Jaké máš možné hodnoty pro tu **Frekvenci sklízení**?

**Comment by Visgean** [comment]
https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/source/constants.py#L55

**Comment by Bystroushaak** [comment]
Takže tohle jsou hodnoty co ti budu posílat:

```python
{
    'frequency': 365,  # hodnoty v https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/source/constants.py#L55
    'javascript': False, # bool
    'global_reject': True, # bool
    'youtube': False, # bool
    'calendars': False, # bool
    'local_traps': False, # bool
    'gentle_fetch': 'default', # jedna z hodnot {default, low, very_low} / {Default, Jemný, Velmi jemný}
    'budget': 15000 # jedna z hodnot {15000, 60000, 5600}
}
```

Nyní je tu ještě otázka zbylých hodnot, tzn třeba titulku a tak. Ale to asi bude chtít domluvit osobně. Dáme jídlo dneska?

**Comment by Visgean** [comment]
Hmm budes muset rozlisit co z toho se tyka k url a co ke zdroji.

**Comment by kvasnicaj** [comment]
všechny položky z WA KAT jsou ke zdroji, ale některé se budou muset propsat k semínkům :) to bude spíš na ná. Dnes odpoledne dám přesný výčet co a kam :)

**Comment by Visgean** [comment]
@kvasnicaj odpoledne uz bylo a furt nic :clock11:

**Comment by kvasnicaj** [comment]
@Visgean Sorry, my jsme to ten den nestihli probrat a pak jsem onemocněl. 

Nicméně všechny hodnoty, co ti předává @Bystroushaak se vztahují k celému zdroji a tudíž patří ke všem semínkům, co ke zdroji patří.

**Comment by Visgean** [comment]
ok a nemam teda ty veci ze seminek vyhodit a dat je do zdroje?

**Comment by kvasnicaj** [comment]
Semínka mají mít svoje vlastní hodnoty (ty které se nastavují v seederu), ale ty co ti předává WA KAT se vztahují k celému zdroji a semínka je tedy zdědí. 

Z principu věci není možné nastavovat ve WA KATu vlastnosti semínek, protože WA KAT pracuje pouze na úrovni celého zdroje.
