### ISSUE TITLE
QA user interface

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#172]

**Comment by kvasnicaj** [comment]
Návrh QA: 
![qa-navrh](https://cloud.githubusercontent.com/assets/10117117/14204285/79485a10-f803-11e5-8d97-a82ce19f68fb.png)

Kurátor kontroluje obsahovou správnost živého webu a technickou kvalitu archivních verzí.

Obsahová kontrola:
- pokud se obsah tématicky nezměnil, pak je to v pořádku
- pokud se změnil, tak kurátor rozhoduje, jestli tato změna povede k vyřazení webu z výběrových sklizní nebo budou stačit upravit údaje (např. popis, url, název, konspekt, frekvence atd.)
- v případě, že obsahová kontrola skončí neúspěchem nastaví se nový status zdroje na: "vydávání ukončeno"

Technická kvalita: 
- kurátor ve waybacku zkontroluje zda jsou sklizené verze čitelné, kolik se toho sklidilo atd. 
- pokud archivní verze není v pořádku, tak kurátor kontroluje, jestli poslední verze má stejný design jako živý web. Pokud ano, tak technická kontrola je neúspěšná a nastaví se status "technické ne"
- v případě, že je design rozdílný, tak kurátor provede technickou sklizeň  a tak se s QA musí počkat, až se sklizeň provede (uložení stavu a odložení kontroly na později)
- pokud je úspěšná technická sklizeň, tak je to ok, pokud ne, tak zase se nastaví status "technické ne" 

Vyhodnocení: 
- kontrola kvality je úspěšná pokud dostane dvě ok - z technické i obsahové části –> u zdroje se nic nemění a pouze se nastaví časovač na další QA
- kontrola kvality je ukončená ihned v případě jakéhokoliv nezdaru, např. pokud u obsahové části je nastaven status "vydávání ukončeno", tak už se dál nepokračuje na technickou část. 

Časovač: 
- v dashboardu by měl kurátorovi naskočit každý den nový zdroj, který by měl zkontrolovat (1 - denně, 7 za týden) - od nejstaršího
- v případě, že je kontrola v pořádku, tak znovu bude web zkontrolován za dva roky. (zařadí se do fronty za zdroje čekající na kontrolu)

Výstup kontroly: 
- výstupem každé kontroly by měl být protokol nebo log, kde budou informace o provedených akcí, jméno kurátora a **komentář** (možnost vložit komentář již při kontrole)
- ten log by měl být něco jako u obsahové kontroly byl změněn název webu, technická byla ok. QA provedl kurátor Jan Novák 1. 4. 2016, a komentář: "Web během působení se přejmenoval z mladá fronta na MF DNES, ale vydavatel a url zůstalo stejné. "

A na kartě zdroje by měla být možnost spustit QA manuálně (předběhnout frontu). A také by mělo být vidět, že byla kontrola provedena. Napadá mě systém jako má twitter nebo facebook u verified users, nějaká malá značka u názvu webu třeba :+1:  Pro jistotu dávám obrázek, aby bylo jasné, co myslím :) 

<img width="275" alt="verified-user" src="https://cloud.githubusercontent.com/assets/10117117/14204652/fe4ec60c-f805-11e5-8ad4-82dc4ad02574.png">

**Comment by Visgean** [comment]
OK, nektere veci jsem pojmul trochu jinak, snazil jsem se aby mel kurator co nejvetsi volnost. Ted je to vicemene prototyp, tak by bylo fajn aby jste to zkoukli.
