### ISSUE TITLE
Archive crawler reports | after integration with crawler

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#174]
Each crawl run in calendar would keep txt reports from harvester. Curators could evaluate overall information from reports such as: not crawled domains, remaining URIs in frontier, URIs per domain etc.

TODO: 
Define what is interesting for curator - ie for QA, future planning, looking back for information etc.
Define which reports to keep
Define what overall information to show.

**Comment by Visgean** [comment]
Prozatim zaviram dokud to zase nebude aktualni
