### ISSUE TITLE
saving List of urls

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#176]
U sklizně, kde je nyní odkaz List of urls, na který když klikneš, tak se teď zobrazí seznam URL, což je ok. Ale potřebovali bychom tento seznam URL uložit k té sklizní v tom čase, kdy je seznam vygenerován. 

Takže by bylo fajn, kdyby místo "List of urls" bylo "generovat seznam url", na který kdyby někdo kliknul, tak by se mu zobrazil seznam url a zároveň by se tento seznam uložil do databáze k té sklizni, stačí formou obyčejného textu.

**Comment by Visgean** [comment]
Takze potrebujes ten seznam zmrazit na nejaky specificky cas?

**Comment by westfood** [comment]
Na furt:-)

**Comment by Visgean** [comment]
Hmm obecne pocitam s tim, ze pozdeji se budou sklizne spoustet pres cron ktery kazdy den checkne co ma za zklizne, zkombinuje je - treba prvni leden je automaticky spousta zklizni tak je vezme najednou a udela jakysi report pri kterem ulozi: xml vygenerovany pro haritrex, output z haritrexu. Ted je to neco podobneho, jen je to dynamicky generovany, tzn muzu udelat aby po zmene stavu na "running" zmrazil vysledek te funkce co vraci seminka... Nemuzu to ulozit libovolne pri kazde navsteve tehle funkce - lidi si budou chtit zkontrolovat co se dostane do sklizne atp a tim ji zmrazi...

**Comment by westfood** [comment]
Jasně, se změnou stavu by to mělo dostačovat.
