### ISSUE TITLE
add link to wa-kat

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#185]

**Comment by Visgean** [comment]
@Bystroushaak

**Comment by Bystroushaak** [comment]
http://vps4life.kitakitsune.org:8080

**Comment by Visgean** [comment]
$ http vps4life.kitakitsune.org:8080

http: error: ConnectionError: HTTPConnectionPool(host='vps4life.kitakitsune.org', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc733c72fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by Bystroushaak** [comment]
```
$ http vps4life.kitakitsune.org:8080 | head
<!DOCTYPE html>
<html lang="cs">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>WA KAT</title>

    <!-- Bootstrap -->
```

**Comment by Bystroushaak** [comment]
Odkud to zkoušíš? Jestli je to v knihovně, tak to může být jen paranoidně nastavený firewall.

**Comment by Bystroushaak** [comment]
Jde ti resolvnout 80? Tam by měl taky běžet webserver, který zobrazí prázdnou stránku.

**Comment by Visgean** [comment]
Odkudkoliv, proste je to down.

**Comment by Bystroushaak** [comment]
Jo, teď je to asi down. Posraná kanadská VPS za 30$ na doživotí.

**Comment by Bystroushaak** [comment]
Jsem teď koupil jinou VPS, přes den až se aktivuje, tak to zprovozním tam.

**Comment by Bystroushaak** [comment]
http://forpsi.kitakitsune.org:8080/

**Comment by Visgean** [comment]
ok to uz funguje. Flow tedy bude nasledujici, ja poslu uzivatele na adresu http://forpsi.kitakitsune.org:8080/<id> kde <id> predstavuje ID zdroje, tvuj backend se pripoji na moje API a predvyplni uzivateli informace.

**Comment by Visgean** [comment]
Jediny problem je, ze ty to koncipujes na jednu url, ale jeden zdroj muze mit vic URL a cast se to deje. Co v takove situaci? @kvasnicaj

**Comment by Bystroushaak** [comment]
Tak tohle je katalogizace konkrétního webu, ne každé url.

**Comment by Visgean** [comment]
Ja ti v api poslu 5 url, kterou si vyberes?

**Comment by Bystroushaak** [comment]
První.

**Comment by Visgean** [comment]
A co kdyz uzivatel chce i tu druhou?

**Comment by Bystroushaak** [comment]
Tak jí tam může napsat ručně.

Myslím, že jsi pořád nepochopil smysl toho nástroje. Slouží ke katalogizaci celých webů, což umožňuje semi-automatickou analýzou. Když budeš chtít zkatalogizovat seznam.cz, tak tam prostě hodíš seznam.cz a neřešíš katalogizaci všech pod-url co se na něm nacházejí. Ten tool si z toho vytáhne data a pak to url pole použije v generovaných MARC datech, které jdou dál, třeba do alephu.

Já teda potřebuju takovou url, která je „hlavní“. Homepage pro ten web. Něco, co se dává do odkazů, když se na to odkazují.

**Comment by Visgean** [comment]
Nevim ktera je hlavni

**Comment by Bystroushaak** [comment]
...

**Comment by Visgean** [comment]
Test server musi zpracovat tedy url http://forpsi.kitakitsune.org:8080/<id> nebo tak neco. Klidne http://forpsi.kitakitsune.org:8080/?id=1 ale zatim vsechno co jsem zkousel tak nefunguje

**Comment by Bystroushaak** [comment]
http://forpsi.kitakitsune.org:8080/?url_id=1

Zatím na to není namapovaná žádná akce, ale ten parametr to přijímá a je to připravené.
