### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#19]
Asynchronously taking screenshots via http://phantomjs.org/

**Comment by kvasnicaj** [comment]
Funguje to? Je někde vidět screenshot, aby jej kurátor mohl zkontrolovat?

**Comment by Visgean** [comment]
Je videt a lze editovat, na test serveru ale neni nastaveny ten cron co je generuje

**Comment by kvasnicaj** [comment]
Screenshot se automatický nevytvoří při přidání nového zdroje. Jde pouze nahrát manuálně jako obrázek. @westfood říkal, že k tomu instaloval potřebné nástroje na server. Tak kde je problém? :)

**Comment by Visgean** [comment]
manage.py generate_screenshots spusti proces screenshotu, jeste to zkontroluji.
