### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#190]
#61 #19 

screenshoty jsou vždy a pouze ke zdroji. A vždy je jen jeden. Nyní jsou nastavené u semínek. Odtud je prosím tě odstraň a přidej nástroje pro práci se screenshotem na kartu zdroje

**Comment by Visgean** [comment]
d6dcd0c source.html: show thumbnail in info table
3f30a92 fix screenshot function
005a297 settings template with memchaed for compose
86e4b89 add memcached to docker-compose

**Comment by Visgean** [comment]
c430e24ea716f2e68e2e275af14d413b826d8b7e
