### ISSUE TITLE
Crawler variables 

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#191]
Proměnné, které se nastavují ve WA KATu při katalogizaci, musí být možné potom uložené a editovatovatelné i v seederu. Ideálně přidat tlačitko editovat pravidla sklizně a stránku s formulářem níže

![crawler_variables](https://cloud.githubusercontent.com/assets/10117117/13635870/d2bf5fa6-e5fe-11e5-8eaa-5e182fedd72c.png)

**Comment by Visgean** [comment]
Duplicate of #162
