### ISSUE TITLE
Odesílaná data

### ISSUE THREAD

**Issue by Bystroushaak** [WebArchivCZ/Seeder#193]
Abys měl nějaký vzorek a představu o formátu, tak takhle vypadají data, co ti budu odesílat, včetně pravidel. Časem asi ještě něco přibude (Bára zakládala nějaké todo), ale to nebude hned:

```JSON
{  
   "keywords":[  
      "předmětová hesla",
      "xenon"
   ],
   "periodicity":"Časté aktualizace",
   "annotation":"Zde by měl být krátký popis, jako vzadu na obálce knihy a tak.",
   "conspect":{  
      "sub_code":"58",
      "sub_name":"Botanika",
      "consp_id":2
   },
   "language":"cze",
   "place":"Hradec Králové",
   "publisher":"Magnanimitas,",
   "author":{  
      "name":"Grada Publishing",
      "code":"kn20080316009",
      "linked_forms":[  
         "Grada Publishing a.s.",
         "Grada (nakladatelství)",
         "Nakladatelství Grada"
      ],
      "is_corporation":true,
      "record":{  
         "7":[  
            "kn20080316009"
         ],
         "i1":"2",
         "i2":" ",
         "a":[  
            "Grada Publishing"
         ]
      },
      "alt_name":"Grada Publishing [organizace] (Grada Publishing a.s., Grada (nakladatelství), Nakladatelství Grada)"
   },
   "creation_date":"2011-",
   "title":"Ad alta",
   "issn":"2464-6733",
   "url":"http://www.magnanimitas.cz/ad-alta-archive",
   "rules":{  
      "frequency":365,
      "javascript":false,
      "global_reject":true,
      "youtube":false,
      "calendars":false,
      "local_traps":false,
      "gentle_fetch":"default",
      "budget":15000
   }
}
```

**Comment by Visgean** [comment]
OK, tak ted uz by to castecne melo fungovat. Jen to nekdy musim manualne deploynout na server.

**Comment by Visgean** [comment]
Tak. To API se chova stejne jako to co dostavas z GETu, v momente kdy to chces updatovat tak posles PATCH se zmenama...

**Comment by Bystroushaak** [comment]
No, to je mi obávám se docela k ničemu, když moje data jsou něco úplně jiného, než tvoje data a polovinu dat ode mě ani nemáš kam uložit.

**Comment by Visgean** [comment]
to tak je. Muj system nemuze ukladat nahodne nespecifikovane data

**Comment by Bystroushaak** [comment]
No, já prostě data pro tebe v tom formátu jaký chceš ani mít nebudu. Jakože je nemám kde vzít vůbec. Tak jak to máš ti tam můžu posílat asi tak pět položek.

```JSON
{
    "frequency": 6, 
    "issn": "1212-5075", 
    "comment": "Elektronický časopis primárně o informačních zdrojích, informačních službách a aplikacích. Dále se věnuje oblasti informační politiky a vzdělávání", 
    "name": "Ikaros : elektronický časopis o informační společnosti", 
    "mdt": ..
}
```

Minimálně ještě ty pravidla tam chtěl @kvasnicaj posílat taky. Prostě to budeš muset upravit.

**Comment by Visgean** [comment]
Ty pravidla jsou v tom API. A ano, chci aby si mi posilal jenom minimum polozek.

**Comment by Visgean** [comment]
Muzu zacit sbirat dalsi data jako keywords a location atp, jestlize davaji smysl, ale nebudu ukladat data kterym nerozumim a ktere nemaji reprezentaci v systemu.

**Comment by Bystroushaak** [comment]
Kde jsou ty pravidla v tom API? Už jsi nahodil updatovanou verzi na ten test server? Jsem na to koukal včera a neviděl jsem je tam.

**Comment by Visgean** [comment]
Rikal jsem ze to chvili bude trvat, nejspis ten test server uplne zastavim.
