### ISSUE TITLE
Úprava API

### ISSUE THREAD

**Issue by Bystroushaak** [WebArchivCZ/Seeder#194]
Potřeboval bych, abys mi v tom záznamu s API posílal taky MDT. U konspektů posíláš ``"category": 12``, a ``"sub_category": 235``, což vychází z:

```JSON
 {
"id":235,
"name":"Knihovnictví. Informatika",
"subcategory_id":"02"
},
```

Já potřebuju to MDT, co je v tomhle datasetu jako ``subcategory_id``, ten zbytek ID jsou veskrze nesmysly, které nemají s Alephem nic společného.

**Comment by Visgean** [comment]
Nevim co MDT...

pá 11. 3. 2016 v 21:02 odesílatel Bystroushaak <notifications@github.com>
napsal:

**Comment by Bystroushaak** [comment]
Doporučuji přečíst i zbytek komentáře, kde to extenzivně vysvětluji, i s praktickou ukázkou.
