### ISSUE TITLE
Filter by name - diacritics

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#196]
Pokud v záložce Sources hledám zdroj dle jména bez diaritiky, nenajde požadované zdroje - př. při hledání "trebon" je 0 výsledků, při hledání "třeboň" najde 4 výsledky.

**Comment by Visgean** [comment]
tohle nejde moc dobre vyresit, mozna to vyresi vyhledavani v elasticu ale to je jine issue
