### ISSUE TITLE
Přidání komentáře

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/Seeder#198]
Po přidání komentáře a jeho odeslání se zobrazí hláška 404 nenalezeno. Obsah se však uloží. Je to tak v pořádku?

**Comment by Visgean** [comment]
a kde se to stane?

**Comment by Bilinova** [comment]
když jsem vkládala komentář u Vydavatele.

**Comment by Visgean** [comment]
tady mi to funguje http://seeder.visgean.me/publisher/3/detail

**Comment by Bilinova** [comment]
I na té nové adrese mi to ukáže tothle -[PrtScn-komentář u vydavatele.docx](https://github.com/WebArchivCZ/Seeder/files/181933/PrtScn-komentar.u.vydavatele.docx) ale ten komentář se tam pak uloží

**Comment by Visgean** [comment]
No jses na blby adrese, ma to byt http://seeder.visgean.me/publisher/7436/detail a nikoliv http://seeder.visgean.me/publisher/7436/

**Comment by Bilinova** [comment]
OK tak to zkusím odznova.

**Comment by kvasnicaj** [comment]
Vkládání komentáře u vydavatele stále nefunguje. Mě to hodí sem http://seeder.visgean.me/publisher/5/detail a je tam prázdná stránka

**Comment by Visgean** [comment]
chyba je asi u vas, u me je tam normalni stranka. Ale mozna je to chyba testovaciho serveru, uz to chce nejaky vnitrni stroj.

**Comment by Visgean** [comment]
683062c6d5be2f3826f95f6f85efac72beb7f128 fixnul
