### ISSUE TITLE
Dokumentace

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#199]
Čéšť,

jestli rozumím správně, už by jsi chtěl testovat na mašinách v NK?

Připravím stroj v repo machines. Umožní lokální deployment virtual boxu přes vagrant + provize ansible. Plus připravím testovací stroj na naší infrastruktuře, kde se bude testovat.

Pro začátek, moje otázky jsou převázně na workflow. 

a.) Ty máš nějaký svůj lokální deployment, něco vyřešíš a pushes to na github? Plus CI který ti to hodí na tvůj server, kde se následně testuje.

b.) Buildnutí dockeru je pak na mně nebo buildneš docker image do nějaké repozitáře, který si mi stáhneme a nahodíme na server k testování?

c.) Nastřelil jsem si roli pro seeder: https://github.com/WebArchivCZ/machines/blob/master/shared/roles/seeder/task/main.yml - to je varianta, že deployment Seederu připravíme přes Ansible bez Dockeru. Tj. ansible nahodí balíčky, z githubu stáhne aplikaci a testovací prostředí jede. Defakto můžeme mít obojí, celou aplikaci jako kontejner od tebe, stejně jako v yaml zdokumentovaný postup, jak Seeder nainstalovat z nuly pomocí ansible. Případně kombinaci obojího, tj. ansible zajístí docker prostředí, stáhne docker seeder image z repo, ansible dockeru dodá nějaké proměné apod. To mi připadá nejrozumnější. Ale tenhle bod je spíš přemýšlení na hlas, co na to říkáte.

**Comment by Visgean** [comment]
Ahoj, ten soucasny deployment je sluzba ktera pokazde kdyz jsem pushnul tak se pripojila ssh na server a tam spustila deployovaci skript ktery pullnul a pak syncnul db atp. 

Ja v zasade skoro nic nepotrebuju v tom dockeru, jenom par balicku, zbezne mi sedi ta role co si posilal. 
Pri kazdem pullnuti pak pouzivam nasledujici prikazy: 

- tx pull -a
- ./manage.py compilemessages
- ./manage.py migrate
- ./manage.py collectstatic

Tohle musi projet po kazdem pullnuti. Pak se musi taky nainstalovat requirements. Vidim tam par problemu ktery se budou muset vyresit

- tx je prikaz na preklady, ten vyzaduje autentizacni soubor v home nebo tak nekde 
- django pouziva settings soubory, ty budu muset pro tebe udelat nejak dynamicky aby si nacitali promene z envu. 
- jsou tam nejake crony atp. nevim jak se tohle resi...

Seeder v tom settings potrebuje primarne nastavit postgresql databazi kde bude mit prava vytvaret tabulky. Pak je taky dalsi otazka jak na webovy server. Obecne se python appky spousti pres ``gunicorn`` a pak se udela proxy na Nginxu ktera smeruje vsechno skrz na port gunicorn s vyjimkou medii a statickych souboru ktery jsou mimo tenhle flow, primo nginxem ktery na to ma optimalizace a je to celkove bezpecnejsi. 
Takovou templatu pro nginx uz mam jenom je potreba ji asi trochu upravit pro Ansible. (+ asi budou treba udelat templaty s configem pro gunicorn). 

Mam pocit ze nejlepsi by bylo rozdelit ten ansible na dve casti: v tom repu bych to nechal jenom do te casti ze naklonuje tenhle repozitar a v nem bude dalsi role ansiblu ktera dodela zbytek. Jde mi o to aby byla jedna verze ansiblu kterou pouzivame oba.

**Comment by westfood** [comment]
**Ad tajemství**

Ansible má funkci vault, která enkryptuje s AES-256. Na githubu máš pak zaheslovanej soubor, kterej se otevře jen s klíčem v tvým env. Tj. s Járama sdílím klíč, který máme v shell profilu a anisble si pro klíč šáhne, když dělá provizi. Tj. jediný co nechceš aby se ti stalo, je pushnout ještě nezaencryptovanej soubor s tvýmá nejtemnějšíma tajemstvíma.

Tj. tx a django-settings s heslama, můžou být v ansible vault. Akorát si teď nejsem jistej, jak volat ansible-vault jen shellovým příkazem. Ale to si otestuji.

Ansible umí prostgres provizi pěkně. Nginx doufám taky, ale to se pořeší templatem.

*Ad role*
Dvě role jsou asi cajk, ale klidně je můžeme mít centrálně? Ale řešil bych to až se v tom budu vrtat.

**Comment by westfood** [comment]
Prdnul jsem na docker hub organizaci NLCR / National Library of the Czech Republic: https://hub.docker.com/u/nlcr/ -- založte si účty pod svými maily, přidám vás do týmu..

**Comment by Visgean** [comment]
me@visgean.me
