### ISSUE TITLE
Docker | No module named local_settings

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#203]
Selhává mi Docker build v posledním kroku:

Step 8 : RUN /code/Seeder/manage.py collectstatic --noinput
 ---> Running in 86670adb8fbd
Traceback (most recent call last):
  File "/code/Seeder/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named local_settings

**Comment by Visgean** [comment]
Vytvori si ve slozce ``Seeder/settings/local_settings.py`` je tam na nej sablona ale na ten docker-compose tam muzes hodit tohle:

```
from base import *

SECRET_KEY = 'sdfvsdfvsdfvsdfv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Database
# https://docs.djangoproject.com/en/1.7/ref/settings/#databases
# since we use special PostgresSQL fields we cannot simply use any db.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'postgres',
    },
    'legacy_seeder': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'legacy_db',
        'USER': 'legacy',
        'PASSWORD': 'legacy',
        'HOST': 'mysql',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
LEGACY_DB_CONNECTED = True
```

**Comment by westfood** [comment]
vďaka

**Comment by westfood** [comment]
Hele a jakej defaultní admin login pro Seeder? Nenašel jsem to v konfiguraci ani dokumentaci,

**Comment by Visgean** [comment]
zadny, musis vytvorit, https://seeder.readthedocs.org/en/latest/docker_compose.html 

`docker-compose run web ./manage.py createsuperuser`

**Comment by Visgean** [comment]
ted jsem tam jeste pridal nejake veci tak to zcheckni, budes nejspis muset upravit ten settings soubour a znova si zbuildit stroje: ``docker-compose build``
