### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#227]
Hlásí chybu, pokud se chci přepnout na panel Dashboard z jakékoliv jiné sekce:

AttributeError at /

'Contract' object has no attribute 'source'

**Comment by westfood** [comment]
Hele, když kliknu na: http://war.webarchiv.cz/contracts/3981/schedule
Tak: 
Request Method:	GET
Request URL:	http://war.webarchiv.cz/contracts/3981/schedule
Django Version:	1.9.5
Exception Type:	AttributeError
Exception Value:	
'Contract' object has no attribute 'source'
Exception Location:	/code/Seeder/contracts/views.py in get_initial, line 156

Tady z logu:

[27/Apr/2016 11:51:12] "GET / HTTP/1.1" 200 18748
web_1       | [27/Apr/2016 11:51:29] "GET /search/?q=malina HTTP/1.1" 200 6896
web_1       | [27/Apr/2016 11:51:33] "GET /source/detail/10019 HTTP/1.1" 200 11557
web_1       | [27/Apr/2016 11:51:34] "GET /static/css/bootstrap-image-gallery.min.css HTTP/1.1" 200 1472
web_1       | [27/Apr/2016 11:51:34] "GET /static/js/bootstrap-image-gallery.min.js HTTP/1.1" 200 1096
web_1       | [27/Apr/2016 11:51:39] "GET /contracts/3981/detail HTTP/1.1" 200 7761
web_1       | Internal Server Error: /contracts/3981/schedule
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 149, in get_response
web_1       |     response = self.process_exception_by_middleware(e, request)
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
web_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
web_1       |     return self.dispatch(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/utils/decorators.py", line 67, in _wrapper
web_1       |     return bound_func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
web_1       |     return view_func(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/utils/decorators.py", line 63, in bound_func
web_1       |     return func.__get__(self, type(self))(*args2, **kwargs2)
web_1       |   File "/code/Seeder/core/generic_views.py", line 24, in dispatch
web_1       |     return super().dispatch(request, *args, **kwargs)
web_1       |   File "/code/Seeder/core/generic_views.py", line 100, in dispatch
web_1       |     return super().dispatch(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 88, in dispatch
web_1       |     return handler(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 213, in get
web_1       |     return self.render_to_response(self.get_context_data())
web_1       |   File "/code/Seeder/contracts/views.py", line 129, in get_context_data
web_1       |     context = super().get_context_data(**kwargs)
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 122, in get_context_data
web_1       |     kwargs['form'] = self.get_form()
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 74, in get_form
web_1       |     return form_class(**self.get_form_kwargs())
web_1       |   File "/code/Seeder/contracts/views.py", line 146, in get_form_kwargs
web_1       |     kwargs = super().get_form_kwargs()
web_1       |   File "/usr/local/lib/python3.4/dist-packages/django/views/generic/edit.py", line 81, in get_form_kwargs
web_1       |     'initial': self.get_initial(),
web_1       |   File "/code/Seeder/contracts/views.py", line 156, in get_initial
web_1       |     'source': self.object.source,
web_1       | AttributeError: 'Contract' object has no attribute 'source'
web_1       | [27/Apr/2016 11:51:42] "GET /contracts/3981/schedule HTTP/1.1" 500 142713

**Comment by Visgean** [comment]
fixnuto v jinem issue
