### ISSUE TITLE
Edit Publisher error

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#229]
Pokud chci upravit vydavatele tak hlásí chybu:

![seeder-error publisher](https://cloud.githubusercontent.com/assets/12845130/14850532/0da1da80-0c7a-11e6-83a5-d53b536adc14.png)

**Comment by Visgean** [comment]
Vypada to na nevalidniho publishera, Vydavatel s ID 714 byl uz asi smazany nebo neco, ostatni by meli fungovat.
