### ISSUE TITLE
Contract number

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#230]
Jak se přidělují čísla smluv? Musí uživatel sám vybrat číslo? Měly by se přiřazovat automaticky posloupně, vždy začít od znova od začátku každého nového roku.

**Comment by Visgean** [comment]
Prirazovani je automaticke a deje se od potvrzeni platnosti smlouvy, ale jeste to zkontroluji.

**Comment by Visgean** [comment]
d63c55f
