### ISSUE TITLE
Contract replacement

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#231]
Jak bude možné vyměnit smlouvu za novou? Např. v případě změny vydavatele. Ve starém Adminu to fungovalo výměnou smlouvy (tzn. přiřazením nového čísla smlouvy s odkazem na původní smlouvu):
![vymena smlouvy](https://cloud.githubusercontent.com/assets/12845130/14850908/7c0e5d70-0c7c-11e6-97ea-f74960c96d96.jpg)
Myslela jsem, že by to bylo možné tím způsobem, že nyní jde v Seederu přiřadit více smluv k jednomu dokumentu - vytvořila bych tedy novou smlouvu, jenže je nutné tu původní nějak deaktivovat (časově nyní omezit jde?).

**Comment by Visgean** [comment]
Casove jde omezit jde, automaticky se expiruje az prekroci danou lhutu, Zdroj muze mit libovolny pocet smluv, potom co nebude mit ani jednu validni tak se mu nastavi stav na ``Contract expired``
