### ISSUE TITLE
Seeder error

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#232]
Vůbec se do Seederu nedostanu - při zadání adresy hlásí chybu viz:
![error-seeder](https://cloud.githubusercontent.com/assets/12845130/14882613/e2dee9e4-0d39-11e6-9531-eaa8745ba49e.jpg)

**Comment by westfood** [comment]
Ahoj, zkus tohle:

http://195.113.134.20 <http://195.113.134.20/>

r.

**Comment by bjackova** [comment]
Na této adrese taky hlásí stejnou chybu.

**Comment by westfood** [comment]
Okej, nahodím tu opravenou verzi.

r.

**Comment by westfood** [comment]
Nová verze je online.

r.

**Comment by bjackova** [comment]
OK, teď už běží.
