### ISSUE TITLE
Add source  - URL duplicity

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#236]
Při vkládání nového vydavatele Seeder netestuje na duplicitu u URL adresy (stejně důležité jako název, obojí se může změnit) - tzn. nenajde duplicitu u zadané již existující URL adresy (řetězce)

**Comment by Visgean** [comment]
![screenshot from 2016-05-04 17-12-22](https://cloud.githubusercontent.com/assets/193832/15018801/8679a1d0-121b-11e6-9f7d-b5588ce799c2.png)


Nevim, url to prohledava vzdy, je ale mozne ze to nic nenajde...
