### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#237]
Podle čeho se vyhledává v search boxu? Hledám např. "staré město", měl by najít zdroj obec Staré Město (web http://obecstaremesto.cz/), místo toho najde 4 jiné zdroje (př. Staré město u Uherského hradiště, ale i např. kontaktTomáš Maňásek). Přes hledání pomocí filtru (name) v "Sources" mi to zdroj najde.
![search-seeder](https://cloud.githubusercontent.com/assets/12845130/14950937/d029a1c6-1055-11e6-9636-42da9ae1168f.jpg)

**Comment by Visgean** [comment]
vyhledava se podle jmena, anotace a komentare. Je to trochu nepresny a budu muset poladit elastic search...

**Comment by bjackova** [comment]
OK, dík.

**Comment by Visgean** [comment]
@westfood bude muset rebuildnout docker-compose.
