### ISSUE TITLE
Hlasování

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/Seeder#238]
Nelze uzavřít hlasování u nově vloženého zdroje (např. Staré Město). Jsem jeho správcem

**Comment by Visgean** [comment]
Co presne se stane ze nelze uzavrit? Nemuzu to nasimulovat, me zavirat jdou. Zobrazuji se tlacitka na uzavreni? Nebo to hodi chybu po kliknuti na uzavreni?
