### ISSUE TITLE
Contract Error

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#244]
Hlásí chybu při vytváření nové smlouvy - přesto vytvoří smlouvu ve stavu Contract in negotiation - při rozkliknutí opět hlásí chybu: 
![smlouva-chyba](https://cloud.githubusercontent.com/assets/12845130/15214579/0f9991ea-184e-11e6-8832-b8e7bbf3b7a1.jpg)

Podobnou chybu hlásí také při pokusu o přiřazení stávající smlouvy ke zdroji.

**Comment by Visgean** [comment]
Musi se provest migrace @westfood

**Comment by westfood** [comment]
Co myslíš migrací?

**Comment by Visgean** [comment]
./manage.py migrate

**Comment by westfood** [comment]
A ten se nesputí automaticky při docker compose, když přihodím sql dump?

**Comment by westfood** [comment]
jo takže takhle? docker-compose run web --rm ./manage.py legacy_sync ?

**Comment by Visgean** [comment]
Ne, to se nespousti automaticky. Muzes to spustit z predpripraveneho souboru: 
`docker-compose run --rm web bash prepare.sh`
