### ISSUE TITLE
Překlady

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#246]
Jakým způsobem se aktualizují překlady z Transifexu? Děje se to automaticky nebo se musí manuálně? Díky

**Comment by Visgean** [comment]
https://seeder.readthedocs.io/en/latest/translation.html

https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/pull_locales.sh

tx prikaz je stahne z transifexu a compilemessages je zkompiluje do .mo souboru, pak je jeste potreba restartovat server.

**Comment by kvasnicaj** [comment]
díky
