### ISSUE TITLE
module Harvests 

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#247]
Ahoj několik přípomínek k modulu Harvests: 

1.) prosím Date of harvests v českém tvaru při zadávání sklizně (v editaci již je v českém tvaru)
2.) jazyk kalendáře je pouze česky i v anglické verzi

3.) prosím o přidání nepovinného pole "Anotace sklizně" při zadávání nové sklizně. Bude se zobrazovat na www stránkách

4.) mohl předělat určování barevnosti tečky podle statusu? (Success zelená; succes with failures > tmavší odstín zelené, running > žlutá; planned > šedá; cancelled, failed > červená //// díky těm barvám by u ročního zobrazení u kalendáře vznikl super grafický přehled za celý rok

5.) označení týdne ti zajíždí pod navigace při jakékoliv velikost okna viz screenshot 

![snimek obrazovky 2016-05-13 v 15 10 00](https://cloud.githubusercontent.com/assets/10117117/15248881/df2bb306-191c-11e6-9187-27503065b700.png)

**Comment by Visgean** [comment]
1. pull messages by mel pomoc, viz deployment..
2. uz ok
3. ok 
4. ok, vicemene jsem ty barvy udelal stejne, myslim ze je to srozumitelne jak to je ted
5. hmm zkusim tam dat jenom cisla.
