### ISSUE TITLE
kalendar hover -> dat jenom cisla

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#249]

**Comment by Visgean** [comment]
Znamenalo by to updatovat na novou verzi coz by zabralo moc casu :(

**Comment by kvasnicaj** [comment]
za mě to tam nemusí být vůbec 👍

**Comment by Visgean** [comment]
ok, ja jsem to zkousel i schovat ale ta stara verze toho kalendare to neumi.
