### ISSUE TITLE
dynamic table generation

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#25]
django-tables2.readthedocs.org ?

**Comment by michaelkuty** [comment]
hi, here is my fw builded on top of Horizon(part of OpenStack Dashboard)

i have integrated generation of tables(AngularJS), please se my doc or source code is really simple
https://github.com/michaelkuty/horizon-contrib
doc lives here http://horizon-contrib.readthedocs.org/en/latest/
main Horizon https://github.com/openstack/horizon
here is quickstart with Horizon http://docs.openstack.org/developer/horizon/quickstart.html

if you have django content types every model has own table with CRUD actions by default (generic)
without model horizon-contrib provide way for doing same as with CT

Tables has AJAX-UPDATE, Filtering(client/server), actions, Sorting pagination and many more
by default is AngularJS table , but 
In the Contrib is initial implementation of React table which can handle thousand of rows without client lags

yes, with Horizon we get more than tables, workflows, modals, tabs, ..

please feel free for contact me with any questions or issues
i have created more than ten apps on these frameworks

if you want, can i create sample build on this application, for example some view can be rewritten to horizon tables
please specify your demands where you want implement tables

**Comment by michaelkuty** [comment]
and provide Bootstrap 3 with compress
every CSS and JS is used as Xstatic this has many benefits for us

**Comment by Visgean** [comment]
I have already implemented django-tables2 and they seem sufficient. Your project seems nice but I dislike the heavy integration which is kind of overkill for the one single table I need in this project...
