### ISSUE TITLE
Transifex

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#253]
```(seeder) [rudolf@curator02 Seeder]$ tx pull -a
/home/rudolf/.transifexrc not found.
Exception: No user credentials found for host https://www.transifex.com. Edit ~/.transifexrc and add the appropriate info in there.```

Ok našel jsem template. Ale moc nevím, proč to chceme. K čemu nám to je - teda chápu tu webovku ale je to placená služba. Máme si nahodit vlastní transifex server nebo si ho máme předplatit?

**Comment by westfood** [comment]
ten jejich open source tier zadáčo na jejich webu nevidím

**Comment by Visgean** [comment]
transifex uz funguje, https://www.transifex.com/webarchivecz/public/ je to zdarma na open source projekty, vyhoda je ze to ma fakt dobre rozhrani na prekladani. Musis byt prihlaseny a pak to bude fungovat, teoreticky to nutne - muzou se prekladat normalne .po soubory a mit je v gitu ale imho je to lepsi takhle.

**Comment by westfood** [comment]
ok, mám tam účet a připojil jsem se.
