### ISSUE TITLE
Zasílání mailů

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#257]
Ta aplikace by měla zasílat maily. Teď to maily vypisuje jen do konzole: django.core.mail.backends.console.EmailBackend.. Ostrá půjde z toho defaultního SMTP backend?

Jaký je vlastně plán, ty maily se budou posílat za webarchiv@nkp.cz?

**Comment by westfood** [comment]
Testoval jsem ještě tohle ale na reset hesla mi to nic neposlalo - zkoušel jsem to i přes localhost.

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.nkp.cz'
EMAIL_PORT = 25
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'seeder@webarchiv.cz'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#EMAIL =  {
#    'default': {
#        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
#       'HOST': 'smtp.nkp.cz'
#    }
#}

**Comment by Visgean** [comment]
Zalezi jak ktery maily, jsou tam i nejake co se budou posilat vydavatelum

**Comment by Visgean** [comment]
Potom co si tam hodil ty smtp settings to udelalo co? Reloadnul si ten server?

**Comment by westfood** [comment]
jj, restartoval jsem uwsgi a to opět spawanulo seeder

**Comment by Visgean** [comment]
hmm ok, a email se vypsal do konsole? Koukni jeste do logu smtp serveru nebo tak jestli ho to neodmitlo, se smptp problem nikdy nebyl.

**Comment by westfood** [comment]
konzoli jsem netestoval, nevím ani kterou myslí..

právě že to na smtp server to ani nedorazilo..

**Comment by westfood** [comment]
hele posílám to teď přes localhost, co má postfix s relay na smtp.nkp.cz

jednak je divný, že je to ```from=<root@localhost> a hlavě o=<i>```

```
Jun  8 10:43:51 curator02 postfix/smtpd[16169]: NOQUEUE: reject: RCPT from localhost[::1]: 550 5.1.1 <i>: Recipient address rejected: User unknown in local recipient table; from=<root@localhost> to=<i> proto=ESMTP helo=<curator02.webarchiv.cz>
```

```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
#EMAIL_PORT = 25
#EMAIL_HOST_USER = ''
#EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'rudolf@localhost'
```

**Comment by westfood** [comment]
stejná konfigurace, pustím si ./manage.py shell a zpráva se pošle..
```
Python 3.4.3 (default, Jan 26 2016, 02:25:35)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.core.mail import send_mail
>>> send_mail('Důvod', 'Zpráva', 'seeder@webarchiv.cz', ['rudolf.kreibich@nkp.cz'], fail_silently=False)
1
```
```
Jun  8 11:18:13 curator02 postfix/qmgr[16155]: D8E8F421D1C1: from=<seeder@webarchiv.cz>, size=493, nrcpt=1 (queue active)
Jun  8 11:18:13 curator02 postfix/smtp[16336]: D8E8F421D1C1: to=<rudolf.kreibich@nkp.cz>, relay=smtp.nkp.cz[10.1.2.183]:25, delay=0.09, delays=0.05/0.02/0.01/0.01, dsn=2.0.0, status=sent (250 2.0.0 u589HvCE024337 Message accepted for delivery)
Jun  8 11:18:13 curator02 postfix/qmgr[16155]: D8E8F421D1C1: removed
```

**Comment by Visgean** [comment]
hmm to by imho znamenalo ze se to poradne nereloadlo. Zkus rekurzivne smazat vsechny pyc soubory po zastaveni serveru

> find . -name "*.pyc" -exec rm -rf {} \;

a pak ho nahodit. Jestli ti to funguje v konzoli a ne v bezici instanci tak to musi byt tim ze v instanci jsou jine settings.

**Comment by westfood** [comment]
stále stejný

**Comment by Visgean** [comment]
Jeste pridej ``SERVER_EMAIL = 'django@my-domain.com'``

**Comment by Visgean** [comment]
Ok pridal jsem view na crashnuti serveru ``/crash_test``. Zaroven jsem otestoval reset hesla, blbla tam template. Jestli se jedna o war.webarchiv.cz tak tam mas blbe nastaveny backend (to se vypsalo pri crashnuti templaty)

`EMAIL_BACKEND	
'django.core.mail.backends.console.EmailBackend'`

**Comment by Visgean** [comment]
+ jestli chces tak muzem dat skype, to by asi mozna bylo jednodusi...

**Comment by westfood** [comment]
ee.. mám to na lokálu.. spíš uploadnu poslední verzi ansible skriptu.. jeslti ansible + vagrant, tak budeš mít stejný prostředí jako já.. ale dej mi ještě hoďku, trochu přepsal dvě role a teď to testuju.

**Comment by westfood** [comment]
píšu jako prase

**Comment by Visgean** [comment]
Tak zkus deploynout k sobe na lokal tu novou verzi a nastav si ten server_email.

**Comment by westfood** [comment]
posun je, že to už korektně píše from, ale to to: je stále na "i"

```
Jun  8 16:15:25 localhost postfix/smtpd[31118]: NOQUEUE: reject: RCPT from localhost[::1]: 550 5.1.1 <i>: Recipient address rejected: User unknown in local recipient table; from=<seeder@webarchiv.cz> to=<i> proto=ESMTP helo=<curator02.webarchiv.cz>
```

```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_USE_TLS = False
SERVER_EMAIL = 'seeder@webarchiv.cz'
````

**Comment by westfood** [comment]
Jo a testuju to přes ten reset hesla - a jede z branche production.

Mám clonovat z main?

// ansible už dneska nedodělám, zítra!  tak si když tak zavoláme.

**Comment by Visgean** [comment]
clonuj zatim z masteru

**Comment by westfood** [comment]
vďka! z master branch to fachá, tak to asi bylo tim template..

**Comment by Visgean** [comment]
:) proto chci ten sentry, abych vzdycky videl cely log chyby..
