### ISSUE TITLE
Integrace s WA-KAT

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#259]
Ahoj, 

a.) Jak nastavím URL na WA-KAT? Nějaká proměná do 

b.) Pro jakého uživatele je ideální vygenerovat token pro WA-KAT? // Na nějakého superadmina nebo na kohokoliv?

**Comment by Visgean** [comment]
https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/settings/base.py#L247 to zmen v local settins. 

token vygeneruj idealne pro noveho uzivatele, nemusi byt super user..
