### ISSUE TITLE
hlasování

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#260]
Teď jsme tu měli studenty, kteří aplikaci testovali a zjistili jsme, že se hlasování chová nekorektně. 

Studentům se podařilo založit několik souběžných hlasování u jednoho zdroje, některé hodnocení se házely do různých hlasování v rámci zdroje.

Nicméně aplikace by si měla ohlídat, aby nešlo otevřít nové hlasování, pokud již nějaké otevřené existuje.

Při založení zdroje defaultně vytvoř první hlasování. 
Pokud je otevřené nějaké hlasování nedovol otevřít nové.
Pokud je hlasování ukončené umožni otevřít nově. 
Kurátor, který vytvořil zdroj, musí mít práva hlasování uzavřít **(to při testech taky nefungovalo)**

**Comment by Visgean** [comment]
fixed in ef1a079

**Comment by mariehaskovcova** [comment]
hodnotit (hlasovat) lze i u zdrojů, na které už máme smlouvu, tzn. lze zpětně měnit hodnocení, které by mělo být už uzavřené - kurátor nemá práva hlasování uzavřít
 “Vytvoření hlasovacího kola” a “Probíhá hodnocení” - vypadá v tuto chvíli stejně

**Comment by kvasnicaj** [comment]
Prosím o zamezení možnosti vytvořit nové hlasovací kolo, když je u zdroje již jedno otevřené. 

Pokud má zdroj uzavřené hlasování, tak je v pořádku, že je možné vytvořit nové hlasovací kolo. Ale nemělo by docházet k tomu, že je souběžně otevřeno více hlasovacích kol najednou.

**Comment by Visgean** [comment]
" Open round already exists. Round not created. " tohle uz existuje. Nevim mozna stara verze?

**Comment by mariehaskovcova** [comment]
hlasování a vytváření nových kol vypadá ok, ale lze hodnotit (vytvářet nová kola hlasování) i u zdrojů ve stavu "v jednání" - tam by měla být možnost hlasovat (vytvářet nová kola) pozastavena

**Comment by Visgean** [comment]
nevim, ja jsem to nechaval na zodpovednosti kuratoro. Neni podle me potreba vsechno mechanizovat a formalizovat.

**Comment by kvasnicaj** [comment]
máš pravdu, nic se nemá přehánět 👍
