### ISSUE TITLE
Smlouvy v jednání

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#262]
Do smluv jsou zařazeny i zdroje, kde je smlouva pouze v jednání (Contract in negotiation) - ty by tam neměly být, pouze přehled skutečně uzavřených smluv.

**Comment by Visgean** [comment]
Od toho jsou tam filtry. 


![screenshot from 2016-06-16 23-17-51](https://cloud.githubusercontent.com/assets/193832/16133521/a2763e38-3418-11e6-8a9b-bf9b8977345b.png)
