### ISSUE TITLE
New contract fail

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#263]
nejde přidat nová smlouva ke zdroji, vždy to skončí v chybě. Testováno u různých zdrojů.
[ProgrammingError at :contracts:4000:detail.pdf](https://github.com/WebArchivCZ/Seeder/files/315741/ProgrammingError.at.contracts.4000.detail.pdf)

**Comment by kvasnicaj** [comment]
to samé u pokusu editovat již existující smlouvu

**Comment by Visgean** [comment]
Imho je to spatne syncnuta databaze. Nebyla aplikovana tahle https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/contracts/migrations/0016_auto_20160504_1845.py#L16 migrace.

**Comment by westfood** [comment]
hm.. takže jaký je postup.. legacy_sync / migrate?

**Comment by Visgean** [comment]
git pull 
pak obsah souboru
https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/prepare.sh
https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/pull_locales.sh

**Comment by westfood** [comment]
kromě pull_locales.sh všechny kroky proběhly. Pull_locales je imho jen stáhnutí překladových souborů.

**Comment by Visgean** [comment]
jj, proc spadlo? chyby login?

**Comment by westfood** [comment]
nic nespadlo.. ještě jsem transifex neřešil, tak tx pull a compilemessages nespoušítm

**Comment by Visgean** [comment]
ok

**Comment by westfood** [comment]
to že jsem nepustil tx pull / compile messages je blocker pro přidání nové smlouvy?

**Comment by Visgean** [comment]
ne, to ze si pustil ten zbytek fixuje tu chybu ;)

**Comment by westfood** [comment]
jo, takže tahle chyba by už neměla nastat. Hele, hodil jsem k tomu label test. Jára si to otestuje a když tak uzavře. Je to tak ok?

**Comment by Visgean** [comment]
OK

**Comment by kvasnicaj** [comment]
tato je chyba je opravena :)
