### ISSUE TITLE
Po tx pull a compilemessages je potřeba restartovat uwsgi, aby se promítla lokalizace.

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#269]
Mám crontab pro uživatele uwsgi: cd /opt/Seeder/Seeder && /opt/virtualenv/seeder/bin/tx pull -a && /opt/virtualenv/seeder/bin/python /opt/Seeder/Seeder/manage.py compilemessages

.. problém je, že aby se změny promítly musím restart uwsgi.. je nějaký elegantnější způsob?

**Comment by Visgean** [comment]
Restart je overkill, reload se na tohle hodi vic http://uwsgi-docs.readthedocs.io/en/latest/articles/TheArtOfGracefulReloading.html 

melo by pak stacit se dotknout reload souboru..

**Comment by westfood** [comment]
Cajk, nastaveno.
