### ISSUE TITLE
Naplánovat emaily

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#271]
Při kliknutí na tlačítko naplánovat emaily, to hodí error: 

Server Error (500)

**Comment by westfood** [comment]
mělo by být, ok, prosím otestovat..

**Comment by bjackova** [comment]
pořád nefunguje - hlásí: Server Error (500)

**Comment by westfood** [comment]
jsme stále na téhle revizi: https://github.com/WebArchivCZ/Seeder/commit/4bb5d33e4aa23d5c42b901efd009ef9867fa22ca

novější mi hází chybu při instalaci. @Visgean Tuhle chybu řeší asi tenhle další commit? https://github.com/WebArchivCZ/Seeder/commit/215dc03eaf89a40a07b227424abd2e4b6a018e3c

**Comment by mariehaskovcova** [comment]
Naplánované emaily - fungují
