### ISSUE TITLE
unikátní zdroj (významný vydavatel)

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#272]
při vkládání nového zdroje (Landscape Festival), po zkontrolování duplicit, chce systém potvrdit, zda se jedná o unikátní zdroj (v Adminu „významný vydavatel“) a nepustí dál, pokud není zaškrtnuto, že se o unikátní zdroj jedná… (není varianta pro neunikátní zdroj)

https://cloud.githubusercontent.com/assets/19947819/16267213/d74d695a-3888-11e6-869e-61fa9ba142a5.png

**Comment by kvasnicaj** [comment]
významný vydavatel již v seederu neexistuje :)
