### ISSUE TITLE
překlady do češtiny

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#273]
http://prntscr.com/bjk120
přeložit   Quality assurance checks (Zjištění stavu kontroly kvality)

http://prntscr.com/bjk1fw
přeložit Main url (Hlavní url)

http://prntscr.com/bjk20p
přeložit Name (Jméno)
	Created (Vytvořeno)
	Last Changed (Poslední změna)
	Publisher (Vydavatel)

http://prntscr.com/bjk36f
přeložit Name (Jméno)
	Created (Vytvořeno)
	Last Changed (Poslední změna) 
 

http://prntscr.com/bjk4dq
přeložit Contact name (Kontaktní osoba)
	Position (Pozice)

http://prntscr.com/bjk5cm
Přeložit  Link (Číslo)
 	     Publisher (Vydavatel)
             Created (Vytvořeno)
             Last Changed (Poslední změna)

http://prntscr.com/bjk6sm
Přeložit   Created (Vytvořeno)
               Last Changed (Poslední změna)

**Comment by Visgean** [comment]
Preklady se resi na https://www.transifex.com/webarchivecz/seeder/ = mimo tenhle repozitar.

**Comment by kvasnicaj** [comment]
@Visgean zde nejde o překlady, ale tyto slova nejsou zanesená v Transifexu, takže je nemáme, jak přeložit

**Comment by Visgean** [comment]
hmm ok
