### ISSUE TITLE
chyba při vkládání nového zdroje

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#274]
Při vkládání nového zdroje těsně před uložením - „error“.  Zdroj není k nalezení (http://prntscr.com/bjkl73), ale když jsem ho zkusila znovu vložit, hlásí duplicitu (http://prntscr.com/bjkkoc)...

**Comment by Visgean** [comment]
Tohle neni chyba vkladani zdroje ale vyhledavani resp indexace. To uz jsem resil v jednom issue. Vyhledavat lze i prez tabulkove zobrazeni vsech zdroju...

**Comment by westfood** [comment]
Co to pro nás znamená?
