### ISSUE TITLE
WA KAT - datum vzniku

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#281]
WA KAT negeneruje datum vzniku, je tam pokaždé [XXXX?]-

**Comment by Bystroushaak** [comment]
To je defaultní hodnota. Když kurátor ten záznam nevyplní, tak se tam vkládá tohle.

**Comment by Bystroushaak** [comment]
Nebo teď nechápu. V kterém případě? Myslíš při čtení dat ze seederu, nebo při zápisu do seederu?

**Comment by bjackova** [comment]
Ahoj, Marie to nespecifikovala úplně přesně - jde o to, že se nenačítají hodnoty z té analýzy data vzniku (v rozbalovacím menu nic není)

**Comment by Bystroushaak** [comment]
Ehm. Asi pletu víc věcí dohromady - myslel jsem, že když je issue založena v Seeder projektu, tak že se týká propoje se Seederem. Zpětně asi chápu, že myslíš že to nenačítá.

**Comment by bjackova** [comment]
Sorry za chaos, samozřejmě, issue se týká WA KATu

**Comment by Bystroushaak** [comment]
V pohodě, to už dořešíme tady.

Já jsem teď ve vlaku, na cestě z Ostravy do Prahy, tak mám jen omezený přehled. Teď jsem to kontroloval na adrese dema (http://forpsi.kitakitsune.org:8080/) a tam to vypadá, že funguje v pohodě (třeba seznam.cz to načetlo).

Chyba s načítáním datumů tam byla dřív, nevím jestli @westfood už updatoval, viz https://github.com/WebArchivCZ/WA-KAT/issues/85

**Comment by Bystroushaak** [comment]
Tedy asi Ruda by měl na serveru sjet cosi jako ``sudo pip install -U wa-kat``, tam já bohužel nemám přístup.

**Comment by westfood** [comment]
Ahoj, tak pro upřesnění. Tohle se týká WA-KATu a je stále otázka, jestli wa-kat generuje datumy.

**Comment by mariehaskovcova** [comment]
ok, přesouvám k wa-katu, ať to tu nestraší  :) 
(jinak testuju a datumy negeneruje)

**Comment by kvasnicaj** [comment]
WebArchivCZ/WA-KAT#89
