### ISSUE TITLE
uzavření starého zdroje 

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#283]
jak můžu uzavřít starý zdroj a vytvořit smlouvu? (Český volejbalový svaz – ohodnocený a schválený k archivaci už před 7 lety, znovu jsem oslovila vydavatele a už jsme uzavřeli i smlouvu)

políčko "Probíhá hlasování" se tu objevuje 2x

políčko "WA-KAT" po rozkliknutí ukazuje 404: nenalezeno

políčko "Historie" po rozkliknutí Server Error (500)

záznam zdroje "Český volejbalový svaz" se objevuje v Přehledu 2x (ve WA Adminu byl jen jednou)

**Comment by Visgean** [comment]
Tlacitko editovat, a zmenit stav zdroje na adekvatni polozku. Hlasovani bylo mozne vytvorit vicekrat, to uz bylo opravene.

**Comment by Visgean** [comment]
Historie 500 opraveno.
