### ISSUE TITLE
uzavření zdroje - smlouva

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#284]
ještě k předešlému dotazu na uzavření zdroje - manuální editace zdroje funguje, ale předpokládám, že výběr položky „Archivuje se“ by měl směřovat k vygenerování čísla smlouvy, což se nedaří

**Comment by Visgean** [comment]
nn, smlouve se priradi cislo az v momente co uzivatel smlouvu zedituje na editaci smlouvy, nikoliv zdroje...

**Comment by mariehaskovcova** [comment]
díky, číslo smlouvy vygenerováno :) nedala jsem předtím jen uložit...
