### ISSUE TITLE
Je možné zakládat TOKENy z příkazové řádky?

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Seeder#285]
Ahoj,

potřeboval bych kvůli automatizaci, nastavit společný TOKEN pro WA_KAT i Seeder.

**Comment by Visgean** [comment]
Neni, ale muzu to udelat.

**Comment by westfood** [comment]
To by bylo super, pokud tím teda není moc práce.

**Comment by westfood** [comment]
vďaka!
