### ISSUE TITLE
Smlouvy

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#286]
nevím, jestli je to systémová chyba, ale v přehledu smluv je uložená 6x Matice svatokopecká. Je uložená pod čísly smluv – 37, 38, 39, potom 3 x je evidovaná jako v jednání, přičemž v jednom případě (přestože je uvedená jako v jednání) má po rozkliknutí číslo smlouvy 40… 
http://prntscr.com/c8uwm7
Český volejbalový svaz je v „Přehledu“ také dvakrát…

**Comment by Visgean** [comment]
Netusim, myslim ze to spis byl test? @kvasnicaj v puvodnich datech neni.

**Comment by kvasnicaj** [comment]
vyřešeno, byla to chyba v datech
