### ISSUE TITLE
Zdroj – historie

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#287]
Zdroj – historie
po rozkliknutí – Server Error (500)

**Comment by Visgean** [comment]
nemuzu replikovat. @westfood

**Comment by mariehaskovcova** [comment]
slova nejsou zanesená v Transifexu, takže nemůžeme přeložit

**Comment by mariehaskovcova** [comment]
zdroj - historie - už se zdá ok, nehází Error...
