### ISSUE TITLE
Naplánované maily

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#288]
Naplánované maily
Po rozkliknutí – Server Error (500)

**Comment by Visgean** [comment]
@westfood nemuzu u sebe replikovat.

**Comment by kvasnicaj** [comment]
#271

**Comment by Visgean** [comment]
Trochu me to ztezuje ze nefunguje sentry server - 400 :(

**Comment by westfood** [comment]
Vím, nějaký trouble.. ale neslibuju, kdy se k tomu dostanu. Zkusím do konce týdne.

**Comment by Visgean** [comment]
jeste jsem docasne vypnul branch production, vsiml jsem si ze jsem to zapomel mergovat :( takze jeste pls checkni z jake branche vlastne vychazis...

**Comment by mariehaskovcova** [comment]
naplánovat emaily - už funguje
