### ISSUE TITLE
stav smlouvy

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#289]
Zdroje – stav smlouvy – možnost smlouva vypršela je tam 2x

https://cloud.githubusercontent.com/assets/19947819/17853075/e048fb5c-686a-11e6-8d41-b09820795bf9.png

**Comment by Visgean** [comment]
Chyba prekladu. @kvasnicaj "contract terminated" a "contract expired" jsou prelozene stejne.

**Comment by mariehaskovcova** [comment]
opraveno :)
