### ISSUE TITLE
otevírání oken

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Seeder#292]
při rozkliknutí čehokoli v Chromu se vytváří další okno (až na Github, Nahlásit chybu a Dokumentaci), ve Firefoxu je to ok

**Comment by Visgean** [comment]
Nove okno by se melo vytvorit jenom na dashboardu. Vyzkousel jsem v chromu a nevytvari okna pro menu atp. V dashboardu je to chovani cilene tak aby clovek mohl otevrit nove veci v novem okne a ale stale mit k dispozici dashboard. Muzu zmenit.

**Comment by kvasnicaj** [comment]
už to funguje korektně, bez tak chyba na straně google 👎
