### ISSUE TITLE
Plánování emailů

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#293]
Proč je možné naplánovat emaily, když už je uzavřená smlouva? Plánování lze zrušit zaškrtnutím políčka Odstranit, ale pokud se záznam znovu otevře, maily se znovu automaticky naplánují, tzn. nejde zrušit plánování emailů (např. zdroj abcd: art brut). U zdrojů, u kterých naopak maily plánovat chceme (ještě před uzavřením smlouvy), to nejde (např. Lesnicko-dřevařská komora ČR)

**Comment by westfood** [comment]
Jestli tomu rozumí správně, tak se to týká funkcionality aplikace. Přesouvám to na Martina

**Comment by kvasnicaj** [comment]
Možná zde vznikly nějaké chybky vadnými daty. Házím na sebe a ještě otestuji, když tak pak hodím zpět na Martina

**Comment by Visgean** [comment]
"Odstranit, ale pokud se záznam znovu otevře" co znamena otevrit zaznam? Ted jsem si naplanoval emaily a pak je smazal v editaci a slo to v pohode. 

Proc presne nejde naplanovat u lesnicko drevarske komory? Co presne se deje? Jde mi o to abych to chovani mohl replikovat.

**Comment by mariehaskovcova** [comment]
plánovat jde maily i tam, kde máme už uzavřenou smlouvu – např. zdroj abcd : art brut (smlouva 45/2013).  Šlo by to plánování mailů zrušit – ve chvíli, kdy už je smlouva uzavřená?

zkusila jsem plánování mailů otestovat:

- zdroj "Rudolfinum" OK
- zdroj "Lesnicko-dřevařská komora ČR" - když chci plánovat maily, objeví se Error 500
- zdroj "Kruh" - objevuje se v seznamu smluv 2x, což by nemělo být možné + při plánování mailů Error 500
(všechny zdroje - stav přijato wa, smlouva v jednání)

**Comment by Visgean** [comment]
Emaily se neodeslou kdyz je smlouva uzavrena.

**Comment by mariehaskovcova** [comment]
ok, naplánovat totiž maily lze i když je smlouva už uzavřená, pokud se neodešlou, tak je to ok

**Comment by westfood** [comment]
Hele a ta 500 ad. zdroj "Lesnicko-dřevařská komora ČR" - když chci plánovat maily, objeví se Error 500? To je košér?

**Comment by Visgean** [comment]
Kouknu se do sentry co to zpusobuje

**Comment by westfood** [comment]
Něco mi říká, že naše sentry je rozbité. Ale jestli máš svoje tak cajk.

**Comment by Visgean** [comment]
No a neslo by spis spravit?

**Comment by Visgean** [comment]
:D

**Comment by westfood** [comment]
Pán by chtěl komfortní vývojové prosředí;-)

**Comment by westfood** [comment]
Kouknu se na to dneska a dám vědět;-)

**Comment by Visgean** [comment]
Ano ;) takhle se k tem logum nedostanu...

**Comment by Visgean** [comment]
Ok dik

**Comment by Visgean** [comment]
Emaily se nyni posilaji pouze v pripade ze je smlouva ve vyjednavani.

**Comment by kvasnicaj** [comment]
stále error 500, prosím @westfood o kontrolu

**Comment by westfood** [comment]
Prosím @Visgean o analýzu;-)

```
gaierror: [Errno -2] Name or service not known

AttributeError: 'NoneType' object has no attribute 'email'
```

http://sentry.webarchiv.cz/sentry/Sentry/issues/24/
http://sentry.webarchiv.cz/sentry/seeder/issues/15/

**Comment by westfood** [comment]
Tady mám template konfigurace Seeer:

https://github.com/WebArchivCZ/machines/blob/master/webarchiv.cz/roles/seeder/templates/local_settings.py.j2

Ale pro mail:
```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'webarchiv@nkp.cz'
SERVER_EMAIL= 'webarchiv@nkp.cz'
```

mám na serveru v /etc/postfix nastavený:
relayhost= [smtp.nkp.cz]
relayhost= [10.1.2.183]

tj. předpokládám, že django přes localhost mail přepošle na smtp.nkp.cz -- ale možná se mýlím a mám rovnou směřovat na smtp.nkp.cz?

**Comment by Visgean** [comment]
je to chyba dat. zkouknu to. Nejaky vydavatel nema urceny email.

**Comment by Visgean** [comment]
jinak to nastaveni by melo byt v pohode.

**Comment by kvasnicaj** [comment]
data opravíme a pak můžeme vyzkoušet nahrát nový dump

**Comment by kvasnicaj** [comment]
@Visgean koukám, že docela hodně kontaktů mají v jednom poli email více než jednu adresu. Nebude to dělat problém?

**Comment by Visgean** [comment]
hmm kde treba?

**Comment by kvasnicaj** [comment]
no já koukám, že je to dost běžná praxe. Odhadem by to mohla být třetina, čtvrtina kontaktů. Většinou jsou ty emaily oddělené středníkem nebo čárkou. 

Asi bude nejlepší, když ty data vyčistím 👍

**Comment by kvasnicaj** [comment]
Některý obsahují fakt velký kuriozity :D např: horejsova@euractiv.cz pro EurActiv i pro Europeum.org;dkral@europeum.org pro Europeum

**Comment by Visgean** [comment]
:/ ... :( ... :-1:  OK. proto se asi vetsina nezmigrovala.

**Comment by Visgean** [comment]
Myslim ze to bylo zpusobene vadnou migraci dat, nyni uz by to melo byt v pohode.

**Comment by mariehaskovcova** [comment]
stále je možné plánovat maily, přestože už je u zdroje uzavřená smlouva... Emaily by se měly posílat jen tam, kde je smlouva "v jednání" (viz předchozí komentáře). 
V tuto chvíli se tak může stát, že se zdroj ocitne ve dvou stavech - má číslo smlouvy (31/2017, 32/2017) a zároveň je v jednání... - viz zdroj "COOLna..aneb dědictví času a kultury" http://prnt.sc/ejf6zn nebo "Bal"  http://prnt.sc/ejf43b

http://prnt.sc/ejf8ml

(s Járou jsme pročistili Admin - ty položky, kde bylo více kontaktů, takže to by už neměl být problém)

**Comment by Visgean** [comment]
Emaily se odeslou jenom v pripade ze je smlouva v jednani. Planovat jdou kdykoliv.

**Comment by mariehaskovcova** [comment]
ok :), ale stejně by neměly být zároveň "v jednání" a zároveň  "s uzavřenou smlouvou". I v seznamu smluv jsou dvakrát... (viz screenshoty), dík

**Comment by Visgean** [comment]
Ne. Je mozne vytvorit novou smlouvu v jednani i kdyz uz je uzavrena jina. Pro takovou smlouvu je mozne naplanovat emaily. Takove dve smlouvy se pak zobrazi v seznamu dvakrat protoze jsou dve. Jsou to dva rozdilne objekty. Nechci takovehle situace omezovat protoze pak to vede k vyjimkam atp. 

Napriklad tady si dovedu predstavit, ze existuje smlouva ktera je podepsana do roku 2018 a v roce 2017 se bude planovat obnoveni v ramci cehoz by se poslali ty emaily. Atp.
