### ISSUE TITLE
Hledání

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#295]
nefunguje hledání podle části slov nebo bez diakritiky
funkce Hledání není totožná s vyhledáváním přes Filtry (viz např. zdroj Na zemi)
nelze hledat přes více filtrů - např. hledat zdroj současně přes konspekt a subkonspekt, hází to Error (500)

**Comment by kvasnicaj** [comment]
tak aktuálně hledání nefunguje vůbec, vždy to nenajde vůbec nic.

**Comment by westfood** [comment]
Jestli vůbec nic, tak možná chyba mého deploymentu. Ke konci týdne nahodím novou bázi a zkontroluji, zda je cajk nasazení.

**Comment by Visgean** [comment]
Ja to proverim ke konci mesice

**Comment by westfood** [comment]
ansible mi nepustil manage.py/rebuild_index - pustil jsem to růčo, tak prosím otestovat.

**Comment by kvasnicaj** [comment]
hledání funkčně funguje, ale budeme k němu mít do konce týdně konkrétní přípomínky. Tak je sem pak hodíme a uvidíš, co s tím půjde nebo nepůjde udělat @Visgean

**Comment by kvasnicaj** [comment]
1.  doplnit vyhledávání i v semínkách (nejen v url v hlavním záznamu), v komentáři a v hodnocení kurátorů

2. část názvu - aby bylo možné všude vyhledávat i jen podle části názvu

3. diakritika - doplnit, aby bylo možné vyhledávat i bez diakritiky (časopis = casopis)

**Comment by holoubkovamonika** [comment]
Pěkně prosím jak jsme na tom s tímto? @Visgean 
viz Jára 
(3) vypadá to, že funguje 
(2) vypadá to, že nefunguje - badatel - není schopen najít zdroj "badatelé", ale zato najde např. odbornou skupinu termické analýzy, geneu nebo astrologickou společnost čr... (slovo badatel/ům/e je v tomto případě v anotacích)
(1) vypadá to, že nefunguje - v jenom z komentářů je slovo "šlamastyka", vyhledávání však nenašlo nic

Díky

**Comment by mariehaskovcova** [comment]
nefunguje políčko "Hledání" u aktuálně vložených zdrojů (nevyhledá ani název zdroje, ani vydavatele). Je to chyba? V rámci testování jsme založili zdroj "bal", vydavatel "BlaBlaBla", dík

**Comment by Visgean** [comment]
ano, od toho jsem to rozdelil do vic issues. Na vyhledavani se pracuje ale je to slozita zalezitost.

**Comment by mariehaskovcova** [comment]
vím, že jsou jednotlivé problémy rozdělené do více issues, tento se žádného z nich netýkal, proto jsem ho hodila sem.  Ruda teď nahodil aktuální verzi. Když jsme zdroj „bal“ v pondělí vytvořila, hledání nefungovalo – nenašla jsem ho ani podle názvu, ani podle vydavatele. Teď po aktualizaci už je to ok. Založila jsem další cvičný zdroj „Kaktus“ a je to stejné – v tuto chvíli hledání nefunguje.

zkusila jsem cvičně otestovat všechny ostatní issues týkající se vyhledávání (diakritika, část názvu, semínka), zatím nefunguje, asi na tom pracuješ :) zatím dík

**Comment by Visgean** [comment]
hledani ted zcasti funguje, ale jsou tam presne ty problemy, ale musim nejdriv zmenit tu infrastrukturu aby tam bylo mozne dat podporu pro diakritiku a rozdelovani slov.

**Comment by mariehaskovcova** [comment]
ok, dík, ještě jsem narazila na jeden dílčí problém týkající se vyhledávání – tentokrát přes filtry u zdrojů, asi to s tím také souvisí, založím na to vlastní  issue

**Comment by Visgean** [comment]
je to zpusobene https://github.com/WebarchivCZ/Seeder/issues/387
