### ISSUE TITLE
Migration legacy database (WA Admin -> Seeder)

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#300]
V minulých dnes proběhla zevrubná kontrola dat, nejnovější dumb databáze na čistou instalaci Seederu. 

Chyby, které jsme našly: 

1) **Creative commons zdroje**: (#298 #287) zjistili jsme, že je chyba u nás v db. Informace o tom, že je zdroj pod CC licencí se ukládá jen u smlouvy, ale ne u zdroje. Pro ilustraci dotaz, kterým zdroje s CC exportuji.

`SELECT r.url, r.title, c.cc FROM resources r, contracts c WHERE c.cc=1 AND r.`contract_id`=c.id `

Řešením může být úprava migrační šablony nebo mohu k odpovídajícím zdrojům doplnit nějakou hodnotu do sloupce creative_commons, např. 1. Co myslíš @Visgean?

2) **U dodatků smluv** chybí informace, že jde o dodatek smlouvy: 

![dodatek](https://cloud.githubusercontent.com/assets/10117117/20891837/44de19f0-bb0c-11e6-8c8e-1c002894ee86.png)

3) **personalizace zdrojů** uživatel nevidí pouze "svoje" zdroje např. zdroje ke katalogizaci, kontrolu kvality, ale vidí všichni všech kurátorů.

**Comment by kvasnicaj** [comment]
Vytvořil jsem převodní tabulku statusů zdrojů, některé nemají ekvivalent jedna ku jedné. V tabulce je v prvním sloupci status v Seederu, ve druhým jeho ekvivalent (pokud existuje) ve WA Adminu a ve třetím sloupce, pak vysvětlení pomocí SQL, jaká data patří k novému statusu. Snad to bude pochopitelné. 

[resource status migration.pdf](https://github.com/WebArchivCZ/Seeder/files/636898/resource.status.migration.pdf)

**Comment by kvasnicaj** [comment]
nová verze migrační tabulky, první obsahovala chybu u technického review 
[resource.status.migrationv2.pdf](https://github.com/WebArchivCZ/Seeder/files/639755/resource.status.migrationv2.pdf)

**Comment by Visgean** [comment]
migrace CC licensi vyresil 3413971934017129d44a2d37cc3f5222198881ca, zbytek je rozdelen do detailnich issues.

**Comment by kvasnicaj** [comment]
v tom případě toto issue uzavírám
