### ISSUE TITLE
personalizace zdroju

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#302]
rozdeluji z #300 @kvasnicaj

**Comment by kvasnicaj** [comment]
je zde nějaká nejasnost? @Visgean

**Comment by Visgean** [comment]
V dashboardu je v soucasnosti par takovych widgetu - muzu udelat dalsi nebo muzu udelat samostatnou stranku v menu kde bude mit kazdej svoje zdroje.

**Comment by kvasnicaj** [comment]
problém je, že v těch widgetech vidí kurátoři i zdroje, které by neměli vidět. Například zdroje ke katalogizaci, tam by měl kurátor vidět, jen ty které jsou jeho, aby věděl, kolik má práce

**Comment by Visgean** [comment]
ok, nyni se filtruje vse krome otevrenych voting rounds podle uzivatele.

**Comment by kvasnicaj** [comment]
ještě to vypadá, že to není úplně ok. Já si neuvědomil, že widgety mají různá nastavení viditelnosti.
Bohužel, nejsem schopný dát dohromady všechny widgety, co tam máš. Tak jen na ty, co si vzpomenu.

**Zdroje je katalogizaci** -> kurátor vidí, jen ty svoje. Obdobně to bude u widgetu V jednání, osloveno atd. 

**Zdroje k hodnocení** -> kurátor vidí všechny zdroje, které nemají uzavřené hodnocení a on v nich ještě nehodnotil

**Quality assurance** -> kurátor vidí zdroje, které mu přidělí systém ke kontrole (nemusí být jen jeho). Systém přiděluje zdroje automaticky, v pravidelných internvalech a od nejstarších zdrojů...

**Comment by Visgean** [comment]
zkontroluji to, ale myslim ze takhle to funguje.
