### ISSUE TITLE
     U dodatků smluv chybí informace, že jde o dodatek smlouvy:

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#303]
z #300

**Comment by Visgean** [comment]
V databazove skukture jsou v soucasne dobe dva sloupce - ``parent_id`` a ``addendum``. Ja jsem to pochopil tak, ze je-li smlouva dodatek tak ma vyplnene ``parent_id``. Tuhle informaci uchovavam. Nechapu k cemu je ``addendum``. Ja to beru tak, ze je-li smlouva dodatek tak ma rodice. Tenhle relationship se uchoval. Muzu klidne udelat dalsi policko ``addendum`` a vyplnit ho podle toho, jen mi to prijde zbytecne. 


@kvasnicaj prosim o upresneni co s tim.

**Comment by kvasnicaj** [comment]
Ohledně dodatků jsme zjistili hned několik problémů. 

V prvé řadě jsme k tomu přistupovali stejně jako ty s tím ``parent_id``,  ``addendum`` je něco, co vypadá, že není využívané (stejně jako ``creative_commons`` v tabulce ``resources``)

Největší problém je v tom, co je za identifikátor smlouvy zapsaný u zdroje v poli ``contract_id``. Protože někdy je tam ta hlavní smlouva a někdy dodatek. To pak způsobí chybu při migraci dat, že se několik smluv nenaimportuje... Moc nevíme, co teď s tím, protože nevíme co je správná varianta.

**Comment by Visgean** [comment]
Posli mi seznam co se nenaimportuji. Muzu to poupravit aby to proste nechalo nevyplneny parent_id.

**Comment by kvasnicaj** [comment]
Tak jsem to podrobil další analýze a zjistil jsem, kde je chyba. 

Doplňky, které se správně naimportovaly, rozšiřovaly stávající smlouvu o nový zdroj. Tzn. id smluv se nacházejí v tabulce ``resources`` v poli ``contract_id``

Zatímco doplňky, které se nenaimportovaly upravují smlouvu jiným způsobem = nepřidávají nový zdroj. Tzn. ``id`` hlavní smlouvy není uvedeno v tabulce ``resources``, ale je nahrazeno právě ``id`` doplňku. Ta hlavní smlouva je stále přítomna systému, ale už "nepatří" žádnému zdroji (což je v pořádku, protože patří k tomu doplňku). Takže by to chtělo vypnout kontrolu, která hlídá vztahy smlouva - zdroj při importu a mělo by to být OK.

**Comment by Visgean** [comment]
Jak jsem psal do commitu. Upravil jsem migracni skript. Ted hazi chybu jenom dva konrakty - predtim byl problem ze se ke kontraktu nenasli linkujici zdroje takze se nevytvoril. A kdyz se nevytvoril kontrakt tak pak hazeli chybu i vsechny dodatky. 

Pro ty dva co se spatne naimportovali doporucuji manualne je pridat pres web rozhrani.

**Comment by kvasnicaj** [comment]
Díky moc, mrknu na ně, až budeme zkoušet novou migraci.

**Comment by kvasnicaj** [comment]
tak jsme vyzkoušeli novou migraci, ale ty dvě vadné smlouvy to nenahlásilo. Mohl bys mi dát jejich nějaký identifikátor?

**Comment by Visgean** [comment]
```
ContactsConversion
Skipped objects: 33, 112, 156, 169, 199, 253, 337, 352, 353, 377, 381, 564, 720, 894, 899, 1238, 1265, 1367, 1804, 1833, 1841, 1907, 2052, 2099, 2224, 2315, 2538, 2737, 2827, 3076, 3104, 3127, 3258, 3320, 3512, 3529, 3546, 3583, 3610, 3678, 3710, 3721, 3744, 3839, 3864, 3869, 3959, 3962, 3965, 3990, 4069, 4100, 4126, 4134, 4137, 4149, 4180, 4223, 4237, 4256, 4277, 4282, 4308, 4332, 4407, 4493, 4742, 4759, 4840, 4842, 4875, 4910, 4939, 4940, 4967, 5038, 5046, 5072, 5077, 5086, 5198, 5304, 5324, 5325, 5360, 5361, 5444, 5445, 5446, 5447, 5448, 5495, 5522, 5570, 5616, 5681, 5741, 5777, 5840, 5870, 5915, 5922, 6103, 6138, 6225, 6286, 6493, 6635, 6636, 6637, 6646, 6894, 6933, 6977, 7001, 7142, 7221, 7366, 7408, 7536, 7552, 7617, 7736, 7989


VoteConversion
Skipped objects: 528, 537, 550, 586, 629, 646, 670, 2103, 2232

Invalid contract no fixed: 114 2011
Skipped contracts:  [140, 3821]
Broken parent relationships:  []
```

ale mam starsi data nez vy.

**Comment by westfood** [comment]
Podle posledních dat, screenshot.

![screenshot 2017-01-25 15 14 37](https://cloud.githubusercontent.com/assets/315436/22334441/1a5b0e0c-e3db-11e6-99e2-c3a0ae7a16f8.png)

**Comment by Visgean** [comment]
tak v tom pripade je to ok.

**Comment by Visgean** [comment]
jestli tam teda neni nejaky jiny problem...

**Comment by kvasnicaj** [comment]
vypadá to ok :)
