### ISSUE TITLE
www - admin specifikace

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#307]
Prosim specifikuj: 

Novinky
- tam je vzdy aktivni jenom jedna?
- ma to nejaky detailni view? 
- ma to nejaky view i archivovanych novinek?

Selected resource  / vyber z katalogu: 
- tady se jedna primarne o ty veci co se zobrazuji na titulni strance, right?
- v obrazku editace jsou dole ty policka " rozhledny", " moderní architektura" atp. O co se jedna?
- pri pridavani zdroje se to pta na id zdroje, o jake id se jedna? O stary wadmin?

![tagy](https://cloud.githubusercontent.com/assets/193832/22064560/0b29e86e-dd7c-11e6-940d-85d6818ac98f.png)

Tematicke sbirky
- nasel jsem ze je to pristupne pres http://www.webarchiv.cz/cs/tematicke-sbirky
- je to pristupne i jinde?
- vybiraji se tam nejak zdroje? nebo je to ciste jenom pro info? - prijde mi to takove dost zbytecne kdyz tam nejsou odkazy na ty zdroje.

Nominace verejnosti
- tady to by asi nemuselo mit vlastni sekci v adminu ale proste by se to zalozilo rovnou v seederu. 

Zaznamy hledani
- tohle je asi straight forward, je otazka kolik by se toho melo uchovavat - nevim jestli je to potreba uchovavat az tak moc jak to je ted
- dalo by se z toho generovat nejake prehledy - resp seskupovat podle domeny a ukazat nehledanejsi atp. 

Staticke stranky
- myslim tim veci jako http://webarchiv.cz/cs/o-webarchivu atp
- ted je to v html souborech sablon, je to vyhovujici stav? (Me to prijde ok, ale nevim jak castlo to nekdo edituje a jaky maji technicky skill ti co to edituji)

blog
- blog je samostatny projekt ktereho se tohle nedotkne, right?

**Comment by kvasnicaj** [comment]
Novinky:
Novinka = levý sloupec na homepage. Vždy se zadává nadpis, titulní obrázek a text. Vše dvoujazyčně (jako vše na www). Také je zobrazena vždy jenom jedna. Archivní nemají žádný view. 

Selected resources: 
Vybírají se stránky z veřejně přístupných. Jedná se o středový sloupec. Vždy dva zdroje. Políčka jsou klíčová slova, které jsou u každého zdroje. Kurátoři mají možnost zobrazit jen některá (např. pokud jich je tam příliš mnoho). 
ID zdroje je ID ze starého adminu. Tohle bude asi třeba nahradit, asi nejlépe fulltextem?

Ad. Novinky & Selected resources - myslím, že by bylo nejlepší toto sjednotit do jednoho rozhraní. Vybrané zdroje se vždy váží k novince a naopak. Není důvod to držet separátně.

Záznamy hledání: 
přehledy by byly určitě super, my se to teď snažíme analyzovat přes excel, takže by nám to ulehčilo naši práci. Co se týče kvantity, tak si nejsem jistý. :)

Nominace veřejnosti:
Může to být klidně integrované v seederu, resp. jsem si myslel, že se celý admin integruje do seederu, bylo by to tak asi nejlepší. Zbytečné mít dvě rozhraní. 
Nominace veřejnosti chodí z formuláře, které je zde: http://www.webarchiv.cz/cs/pridat-web

Poprosili bychom ještě přidat emailovou notifikaci viz #308

Statické stránky jsem vždy upravoval rovnou v HTML, nemám s tím problém, aby to tak zůstalo i nadále.

Blog běží samostatně na bloggeru.

**Comment by kvasnicaj** [comment]
Tematické sbírky viz #309

**Comment by kvasnicaj** [comment]
Mohl bys přidat u správy veřejnosti jednoduché tlačítko, které by sloužilo k označení již vyřešených nominací?

**Comment by Visgean** [comment]
Kouknu na to, predpokladam ze admin se mirne zmeni..

**Comment by kvasnicaj** [comment]
jj s tím počítám a nejsem proti :)

**Comment by Visgean** [comment]
"Ad. Novinky & Selected resources - myslím, že by bylo nejlepší toto sjednotit do jednoho rozhraní. Vybrané zdroje se vždy váží k novince a naopak. Není důvod to držet separátně."


OK. Navrhuji nasledujici sjednoceni:

Novinka bude mit:
1. titulek
2. text 
3. obrazek. 

a pak dva (pouze dva) zdroje. Je nutna anotace ke kazdemu zdroji? 

Kde presne se berou klicove slova u zdroje?

**Comment by Visgean** [comment]
diskuzi o novinkach prosim do #316
