### ISSUE TITLE
www- tematické sbírky

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#309]
Tematické sbírky jsou připraveny k přepracování. Nově se budou jmenovat tematické kolekce a budou přímo spolupracovat se tematickými kolekcemi v Seederu (ty jsou zatím schované ve Sklizních, ale chtěli bychom je dále rozpracovat.) => tematické kolekce se kompletně budou administrovat v Seederu.

Na WWW vznikne úvodní stránka, kde budou seznam s tematickými kolekcemi a jejich popisem:

![wa-sklizne-prehled](https://cloud.githubusercontent.com/assets/10117117/22068667/09fe481c-dd96-11e6-9c09-2e3b880f7ff4.png)

A každá tematická kolekce pak bude mít svoji page, kde budou vypíchnuté veřejné zdroje a seznam těch neveřejných:

![wa-sklizne-prehled-detail](https://cloud.githubusercontent.com/assets/10117117/22068709/2baa722e-dd96-11e6-972a-4c06175ec5d4.png)

**Comment by kvasnicaj** [comment]
Grafické návrhy nejsou ještě finální, čekáme na zapracování našich připomínek ze strany grafiků.

**Comment by Visgean** [comment]
Aha OK, ono to nevypada prilis slozite ten datovy model.

**Comment by kvasnicaj** [comment]
Není, je to jen název, obrázek, anotace a seznam webů 👍

**Comment by Visgean** [comment]
Az bude k dispozici sablona / graficke navrhy tak zaloz dalsi issue.
