### ISSUE TITLE
www - pěkné odkazy

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#310]
Jedna s funkcí, která nemusí být na první pohled zřejmá. Pěkný odkaz na jednotlivé zdroje. Nyní je to děláno improvizovaně přes fulltextové vyhledávání. Používáme to ke sdílení zdrojů s uživateli, abychom nelinkovali přímo do waybacku, když to není nutné.

Dnes ten odkaz vypadá takto:

http://webarchiv.cz/cs/zdroj/essentia

**Comment by Visgean** [comment]
A odkud by se na tuhle stranku melo odkazovat? jenom z administracni casti?

**Comment by kvasnicaj** [comment]
ne ne, to je hlavně po uživatele. Třeba na naši FB stránce to používáme

**Comment by Visgean** [comment]
ok
