### ISSUE TITLE
www - vyhledávání

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#311]
Ještě ti sem do jednotlivých issue naházím popis, některých "složitějších" funkcí webu. Ono jich moc není :)

Vyhledávání dnes může skončit na třech různých místech:

1) Uživatel hledá libovolné slovní spojení, které má **více než jeden** výsledků. Např. http://webarchiv.cz/cs/zdroj/noviny
Zobrazí se mu výčet veřejně dostupných zdrojů s možností přepínat mezi vizuálním a textovým zobrazením. Vyhledávání tedy proběhne v databázi seederu, ve zdrojích, které mají smlouvu 

2) Uživatel hledá libovolné slovní spojení, která má **přesně jeden** výsledek Např. http://webarchiv.cz/cs/zdroj/essentia
Uživateli se zobrazí jakási landing page pro zdroj, oproti předchozímu vyhledávání obsahuje více informací. Používáme ji pro sdílení zdrojů viz #310

3) Uživatel zadá URL. Je přesměrován přímo do waybacku - odpadá tudíž zobrazovací krok na našich stránkách, ale výsledky jsou zobrazeny přímo ve waybacku. Např. zkusit hledat nkp.cz

**Comment by Visgean** [comment]
implementovat cosi jako https://github.com/WebarchivCZ/WWW/blob/master/app/presenters/BasePresenter.php#L100
