### ISSUE TITLE
www - pravý sloupec

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#312]
Pravý sloupec na homepage obsahuje dvě základní informace: velikost archivu v TB a počet veřejných webových stránek resp. počet smluv

Velikost archivu v TB: načítá se z textového souboru, který se nachází: webarchiv.cz/app/templates/util/webarchiveSize.txt
původní vize byla, že ho @westfood bude automaticky aktualizovat, což se nepodařilo naplnit, takže ho jednou za čas přepisuji manuálně 

Počet smluv: výsledné číslo počítá skript z databáze WA Admin

**Comment by Visgean** [comment]
vyreseno.
