### ISSUE TITLE
News / selected resource sjednoceny model

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#316]
pokracovani z #307  

@kvasnicaj 

> Novinky:
> Novinka = levý sloupec na homepage. Vždy se zadává nadpis, titulní obrázek a text. Vše dvoujazyčně (jako vše na www). Také je zobrazena vždy jenom jedna. Archivní nemají žádný view.
> 
> Selected resources:
> Vybírají se stránky z veřejně přístupných. Jedná se o středový sloupec. Vždy dva zdroje. Políčka jsou klíčová slova, které jsou u každého zdroje. Kurátoři mají možnost zobrazit jen některá (např. pokud jich je tam příliš mnoho).
> ID zdroje je ID ze starého adminu. Tohle bude asi třeba nahradit, asi nejlépe fulltextem?
> 
> Ad. Novinky & Selected resources - myslím, že by bylo nejlepší toto sjednotit do jednoho rozhraní. Vybrané zdroje se vždy váží k novince a naopak. Není důvod to držet separátně.
> 
> "Ad. Novinky & Selected resources - myslím, že by bylo nejlepší toto sjednotit do jednoho rozhraní. Vybrané zdroje se vždy váží k novince a naopak. Není důvod to držet separátně."
> 

navrh: 
> OK. Navrhuji nasledujici sjednoceni:
> 
> Novinka bude mit:
> 
> - titulek
> - text
> - obrazek.
> - a pak dva (pouze dva) zdroje. Je nutna anotace ke kazdemu zdroji?
> 
> Kde presne se berou klicove slova u zdroje?
>

**Comment by Visgean** [comment]
(predpokladam ze si nemusim delat starosti s migraci starych novinek vzhledem k tomu, ze neni nikde celkovy vypis.)

**Comment by Visgean** [comment]
Takhle to ted vypada / funguje.


![screenshot-ocean visgean me-2017-01-30-02-48-05](https://cloud.githubusercontent.com/assets/193832/22410974/b5302eea-e696-11e6-9bca-c554d44f6ae7.png)
![screenshot-ocean visgean me-2017-01-30-02-48-55](https://cloud.githubusercontent.com/assets/193832/22410973/b52f9d40-e696-11e6-9edc-c7f2f16b80f6.png)

**Comment by kvasnicaj** [comment]
Anotace ke každému zdroji je nutná, protože je občas nutné ji zkrátit nebo upravit (některé mohou být z roku 2005). Klíčová slova bys měl mít v databázi a měl bys je brát ze stejného zdroje jako anotaci (z wa-katu?)

Jinak myslím, že je to super :) a s migrací starých novinek si opravdu dělat starost nemusíš.

**Comment by Visgean** [comment]
Anotace ke zdrojum neni problem, zkontroluju klicova slova ale fakt myslim
ze je v db nemam

**Comment by kvasnicaj** [comment]
to je blbý, protože na klíčovech slovech je postavená celkem zásadní část katalogu... 

viz http://www.webarchiv.cz/cs/klicove-slovo?keyword=1399&display=text

**Comment by Visgean** [comment]
Ok zapomel jsem je zmigrovat, pridelam to do migrace.

**Comment by Visgean** [comment]
Dneska je zmigruju.

**Comment by kvasnicaj** [comment]
do budoucna je u nových zdrojů, ale musíš získávat buď od WA-Katu nebo z Alephu. Kurátoři vytvářejí klíčová slova při katalogizaci, tedy ve WA-Katu.

**Comment by Visgean** [comment]
Zaloz na to issue prosim
