### ISSUE TITLE
pridat web

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#320]
http://www.webarchiv.cz/cs/pridat-web + pozdeji emaily v #308

**Comment by holoubkovamonika** [comment]
Dá se řešit? @Visgean 
Háže mi to hlášku 404: nenalezeno
viz https://drive.google.com/open?id=0BxWJijTKLjDDM1h2WER2d3E3RVE

Děkuju

**Comment by Visgean** [comment]
ANo, aktalne se to resi. viz https://github.com/WebarchivCZ/Seeder/issues/354

**Comment by mariehaskovcova** [comment]
issue #354 je uzavřené, přidání webu se ale řeší i v issue #308. Zatím stále ve stavu 404: nenalezeno
