### ISSUE TITLE
wysiwiigiitiyiiyitiitg editor pro novinky

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#321]

**Comment by holoubkovamonika** [comment]
Můžu se zeptat jak vypadá? @Visgean 

Zatím pravděpodobně vidím news v seederu: 

V seederu vidím "News", které se dají přidat/editovat... ale nikde tam nevidím, možnost nastavit nějaké datum - nebo "tlačítko" které by označovalo konkrétní Aktualitu/novinku/news, že je ted venku - veřejně viditelná na webu...? 

mimo jiné je taky ještě pořád v angličtině (news - aktuality, title - název, created - vytvořeno, last changed - posledí změna...) 

v konkrétní aktualitě je možnost podívat se na historii a upravit - tlačítko historie mě dostane na server eror 500 - http://war.webarchiv.cz/seeder/news/1/history

děkuju

**Comment by Visgean** [comment]
na preklady je samostatne issue - https://github.com/WebarchivCZ/Seeder/issues/369

**Comment by holoubkovamonika** [comment]
a na ten zbytek?

**Comment by Visgean** [comment]
v jinych issues, tohle issue bylo a wysiwig editoru.

**Comment by holoubkovamonika** [comment]
možná to jen nevidím, v kterých konkrétně prosímtě? Díky moc
