### ISSUE TITLE
advanced vyhledavani

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#324]

**Comment by kvasnicaj** [comment]
pozor, advanced vyhledávání teď nefunguje úplně dobře.
Prosím @westfood o upřesnění parametrů pro vyhledávání ve waybacku

**Comment by Visgean** [comment]
@kvasnicaj jaky je rozdjil mezi advanced vyhledavanim a normalnim? normalni hleda v db zatimco advanced hleda ve waybacku?

**Comment by kvasnicaj** [comment]
advanced vyhledává přímo ve waybacku pomocí URL, @westfood měl upřesnit ty parametry v URL :)

**Comment by westfood** [comment]
Ahoj, teď netuším co se ode mě chce, ale tady je popis: https://github.com/iipc/openwayback/wiki/OpenWayback-Replay-API

**Comment by Visgean** [comment]
ok.

**Comment by mariehaskovcova** [comment]
asi je to v procesu v společně s dalšími issues o vyhledávání, ale pro info - pokročilé vyhledávání u nás stále chyba 404 (viz Mončiny printcreeny – issue #375)

**Comment by kvasnicaj** [comment]
pojďme přesunout advanced vyhledávání do další etapy vývoje a zatím ho tam nemít (skrýt odkaz na www)

**Comment by Visgean** [comment]
ok, to neni problem.

**Comment by kvasnicaj** [comment]
toto je věc, ke které se již nebudeme vracet, proto issue uzavírám.
