### ISSUE TITLE
Klíčová slova

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#325]
Uložení klíčových do databáze ke každému zdroji. 

Klíčová slova se vytvářejí při katalogizaci ve aplikaci WA-KAT a slouží zejména pro katalog na www + pro katalog Aleph.

**Comment by Visgean** [comment]
ve www branchi uz je migrace ae5f1fb5c8fe1bdf87b02dfcbbdbceb7ce8a31d0
