### ISSUE TITLE
Editovat kontakt u vydavatele

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#326]
u editování kontaktu vydavatele - šlo by nastavit jako povinné políčko jen "E-mail"?
A "Jméno" by bylo nepovinné? (mnohdy ho nevíme)

http://prnt.sc/e29p3r

**Comment by holoubkovamonika** [comment]
Je možné vložit jen e-mail, ale automaticky se tam pak hodí ještě "e-mail" jako jméno, viz https://drive.google.com/open?id=0BxWJijTKLjDDMzd3OF9STm5VU0k 

Dalo by se to řešit tak, aby tam byl opravdu jen ten e-mail? 
Děkuju

**Comment by mariehaskovcova** [comment]
pokud nezadáme (protože nevíme) jméno vydavatele, automaticky se místo jména objeví adresa (viz předchozí Monči print screen), nevím, jestli to jde řešit, není to zásadní funkční problém, ale vypadá to divně :)

**Comment by Visgean** [comment]
ok, upraveno.
