### ISSUE TITLE
klicova slova tvorba

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#328]
- [x] z wakatu
- [x] pri vytvoreni
- [x] pri editaci

**Comment by Visgean** [comment]
https://github.com/WebarchivCZ/Seeder/commit/cb84920ab604ba810cf50fce5581cf4e334b0b88
https://github.com/WebarchivCZ/Seeder/commit/653aaab12e58e465ad6deed2950f424d6adbdac6

**Comment by holoubkovamonika** [comment]
Můžu se zeptat o co přesně se jedná? Co by tohle mělo dělat/umět - případně jak se kouknu/zkontroluju, že to dělá, co má? Díky
