### ISSUE TITLE
meta tagy include

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#332]

**Comment by holoubkovamonika** [comment]
Můžu se zeptat o co přesně se jedná? Co by tohle mělo dělat/umět - případně jak se kouknu/zkontroluju, že to dělá, co má? Díky

**Comment by Visgean** [comment]
jedna se o prevod www sablon - meta tagu.

**Comment by Visgean** [comment]
@kvasnicaj odstranil jsem tag og:title (http://ogp.me/). V django template systemu nejde uplne duplikovat to chovani jako bylo drive. Musel by se tedy doplnovat pro kazdou templatu coz se mi nechce. 

Ale obecne mam za to ze ten tag je naprosto zbytecny protoze si to facebook stejne vytahne z <title> tagu.
