### ISSUE TITLE
replikovat chovani paginatoru

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#339]
tri stranky na obe strany, pak 4 nahodne elementy doprava, ale je to potreba jeste vyzkouset.

**Comment by holoubkovamonika** [comment]
Jestli správně chápu funkčnost paginátoru, tak to ještě nefunguje...  @Visgean 
zobrazí se nejdříve první dvě stránky (1 2) a pak dál (2 3 4) (3 4 5) atp... viz
(první strany) https://drive.google.com/open?id=0BxWJijTKLjDDUmlrOEl4S01jTlk
(další strany) https://drive.google.com/open?id=0BxWJijTKLjDDR3JEdXA1djdoUVU

Jak to pokračuje prosím? Díky

**Comment by Visgean** [comment]
Ano. Toto chovani neni jeste realizovane a proto nefunguje.

**Comment by Visgean** [comment]
(Viz stav tohoto issue.)

**Comment by holoubkovamonika** [comment]
Díky :-) stav issue (open/closed) chápu...

Můžu se asi teda zeptat, kdy zhruba by ty otevřené věci mohly být hotové? Tak nějak směr ke všem otevřeným issues? ;-) Děkuju 
říkal Jára, že až se 20. března vrátí, tak by bylo hezké, kdyby to fungovalo :) Tak zjištuju průběžné stavy :)

**Comment by Visgean** [comment]
nevim, jedu prioritne podle toho co je nejpalcivejsi problem.

**Comment by kvasnicaj** [comment]
chování paginátoru není třeba replikovat 1:1, stačí jakékoliv funkční stránkování v našem designu

**Comment by Visgean** [comment]
Ok

**Comment by Visgean** [comment]
![screenshot from 2017-03-10 23-22-51](https://cloud.githubusercontent.com/assets/193832/23817108/966cfca6-05e8-11e7-9705-fff455efcb43.png)
