### ISSUE TITLE
www - tematické sbírky

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#342]
Nový grafický návrh je zde: 

http://clients.kofila.com/webarchiv/2017/webarchiv-web-sklizne-01.png
http://clients.kofila.com/webarchiv/2017/webarchiv-web-sklizne-02.png

Jenom doplním, že u stránky s detailem tematické sbírky jsou modré zdroje veřejně přístupné a černé pouze z referenčního centra. Pro tematické sbírky v rámci seederu založím ještě vlastní issue.

**Comment by Visgean** [comment]
ok

**Comment by Visgean** [comment]
jak zjistim co je verejne pristupne?

**Comment by kvasnicaj** [comment]
to je správná otázka, 

musíme použít stejný klíč napříč celými www, protože na nich se pracuje jen s veřejně přístupnými zdroji. 

Problém je ten, že tak jak jsou teď nastavené statusy zdroje, tak z nich to bohužel nejde vyčíst. To vzniklo historicky z WA Adminu, kde to taky nebylo úplně logicky vytvořené.

Obecně lze říct, že teď je to tak, že všechny zdroje, které mají smlouvu a ta smlouva není vypovězená, jsou veřejně přístupné. 

Ideální stav by byl, kdyby bylo možné lehce poupravit datový model u zdrojů a to tak, že všechny zdroje, které mají status **Archiving accepted** jsou veřejně přístupné. 

S tím, že by se ze statusů zdroje musel odstranit status **Contract expired** a vytvořit se nový příznak nebo políčko u zdroje, kde by zaškrtávaly zdroje, které již nejsou na internetu, ale my je máme v archivu -> tyto zdroje se již nesklízejí, ale stále jsou veřejně přístupné.

Co myslíš? Bylo by to proveditelné?

U těchto zdrojů by se pak při migraci legacy databáze nastavil status Archiving accepted a zároveň by se jim zaškrtlo, že jsou to mrtvé zdroje viz tabulka migrace dat, co už jsem sem dával :)

[resource.status.migrationv2.pdf](https://github.com/WebarchivCZ/Seeder/files/783341/resource.status.migrationv2.pdf)

**Comment by Visgean** [comment]
momentalne jsem to bral tak, ze budu zobrazovat jenom ty co jsou archiving accepted, ale neni problem tam pridat i polozky z contract expired,

**Comment by kvasnicaj** [comment]
jo, ale mě právě štve ta nekonzistence, protože z toho pak vznikají ty zmatky, které už jsou v adminu. Ono i to pojmenování contract expire v seederu není přesné, protože neznamená, že vypršela smlouva, ale že se web již nenachází na živém webu. 

Přimlouval bych se k tomu, aby se ten status vyjmul a stal se z něj samostatná položka :)

**Comment by kvasnicaj** [comment]
aktualizovaná verze grafických návrhů od grafiků. Už je to finální verze 
![wa-sklizen-detail](https://cloud.githubusercontent.com/assets/10117117/23164309/c136bb76-f836-11e6-9503-0009fd1ccc30.png)
![wa-sklizen-txt](https://cloud.githubusercontent.com/assets/10117117/23164310/c139454e-f836-11e6-9415-714c10408b1d.png)
![wa-sklizen-viz](https://cloud.githubusercontent.com/assets/10117117/23164308/c135d800-f836-11e6-9f44-ca9be811c946.png)

**Comment by Visgean** [comment]
odstranit ten status uplne nemuzu, muzu ho nahradit nebo prejmenovat - jde o to ze se na nej migruji uz stara data...

**Comment by kvasnicaj** [comment]
no to byl nebyl problém zařídit, aby se na něj nic nemigrovalo. My bychom ty zdroje mohli nastavit na jiný status. Těch zdrojů není nijak moc. 

Nebo by se při migraci mohly ty zdroje, které by měly mít tento status mohli nastavit na _Archiving accepted_ + příznak _mrtvý web_

**Comment by Visgean** [comment]
hmm, a jaky status to je?

**Comment by kvasnicaj** [comment]
**`resource_status_id` = 9** (_vydávání ukončeno_) a v seederu je to teda _Contract expired_

**Comment by Visgean** [comment]
ok, tak ja to proste zmenim na "publishing discontued"

**Comment by holoubkovamonika** [comment]
Můžu poprosit, jak jsme na tom? @Visgean 

Po vložení několik temtických sklizní do seederu nevidím úplně to, co bych chtěla vidět

- nefunguje textová verze - je pouze obrazová - viz https://drive.google.com/open?id=0BxWJijTKLjDDTDdXUlBPdHE0TFU
- natřískáno do jedné tematické kolekce cca 21 zdrojů, ale neprojeví se to na stránkách - je jen jedna dlouhá dlouhá stránka s celým výčtem, takže nic, že by se to třeba po 10 dalo na druhou stránku... viz první obrázek od grafiků - versus realita https://drive.google.com/open?id=0BxWJijTKLjDDd2VQaE9TRnNZdVE 
- není tu možnost stáhnout soubory u konkrétní sklizně - viz xml/json/atd u prvního obrázku u grafiků versus realita - viz předchozí obrázek... zkoušela jsem formáty xlsx, png, pdf... v administraci vidět jsou, ale reálně ne viz https://drive.google.com/open?id=0BxWJijTKLjDDZ1dyZXp0UlRsVXM

Díky

**Comment by Visgean** [comment]
Ano, proto je toto issue otevrene.

**Comment by mariehaskovcova** [comment]
ahoj, co jsou prosím tě v administraci „mimosystémové URL  semínka“? „Přiřazené zdroje“ jsou – předpokládám - ty, na které máme smlouvu a můžeme je zveřejňovat on-line (v návrhu grafiků jsou modré).  Pak bychom chtěli zveřejnit i ty, které jsou sice součástí kolekcí, ale budou dostupné jen z referenčního centra (smlouvu nemáme) – jsou to tedy ta mimosystémová semínka? Jestli jo, měly by být také vidět na webu (v graf. návrhu černé). V tuto chvíli jsou vidět jen "Přiřazené zdroje". Díky :)

**Comment by Visgean** [comment]
seminka ktere jsou v kolekci ale nejsou v seederu. Budou zahrnuty do sklizne ale nebudou zobrazeny na webu (protoze k nim zadne dalsi informace)

**Comment by mariehaskovcova** [comment]
@Visgean 
při vytváření tematické kolekce, u přiřazování zdrojů, se některé zdroje objevují víckrát (např. Česká komora architektů 6x), v adminu je jen jednou, posílám pro info printscreen  http://prnt.sc/el2xln
![screenshot - architektura](https://cloud.githubusercontent.com/assets/19947819/24044613/4d296a82-0b1c-11e7-8655-f8e79b1dbba4.png)

připomínám, že u tematických kolekcí by měla být zveřejněná i semínka (graf. úprava černě), která jsou součástí kolekce, ale nemůžeme je zpřístupnit veřejně (mimosystémová URL semínka) – v tuto chvíli tam vidět nejsou

nelze stáhnout soubory u konkrétní sklizně - viz xml/json/atd (v administraci byly do záznamu vloženy)

díky

**Comment by Visgean** [comment]
> při vytváření tematické kolekce, u přiřazování zdrojů, se některé zdroje objevují víckrát (např. Česká komora architektů 6x),
fixnuto
