### ISSUE TITLE
Tematické sbírky - administrace

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#343]
V současné době všechny sklizně včetně tematických jsou vkládány pomocí kalendáře v záložce Sklizně. 

Ale jelikož chystáme novou formou tematických sbírek, tak bude potřeba jejich administraci rozšířit.

V Seederu by tedy měla vzniknout nová záložka: "Tematické sbírky", která bude obdobně jako když kliknu na "Zdroje" nebo na "Smlouvy", obsahovat výpis všech dosud evidovaných sbírek.

Po kliknutí na Sbírku se objeví stránka Sbírky, která bude vypadat dost podobně jako u Zdroje. Viz. nákres

![2017-02-08](https://cloud.githubusercontent.com/assets/10117117/22741519/c895cfec-ee13-11e6-82eb-01c88811a676.png)

V levém sloupci info se nacházejí základní informace, podobně jako u zdrojů.  Vpravo pak zkrácený seznam semínek s možností jej editovat a vedle toho odkazy na editaci, historii atd. 

U výpisu sbírek by měla být možnost přidání nové sbírky, nákres formuláře:

![2017-02-08 1](https://cloud.githubusercontent.com/assets/10117117/22742084/c95634d8-ee15-11e6-96a5-d3cf73730266.png)

A teď k jednotlivých informacím, které jsou u jednotlivých tematických sbírek.

Název, název (en), anotace, anotace (en): obyčejný text, bez možnosti formátování - vše povinné

Obrázek: nahrání obrázku (povinné)

Datové soubory: datové soubory mohou být v různých formátech, ze začátku počítáme s .xml, .csv, .txt, .json; souborů může být 0 až N 

Klíčová slova: klíčová slova mohou být použita pouze ty, které již máme v databázi. Omezený výběr, bez možnosti vytvoření nového klíčového slova

Klíčová slova (en): obdobná situace (ale zde si nejsme jisti, jestli držíme v db i ang slova)

Semínka: textový seznam semínek, kurátoři nahrají celý seznam. Seeder by měl po odeslání formuláře zkontrolovat url vůči databázi, zda některé url se v dabázi nenacházejí. Pokud semínko najde a má platnou smlouvu, pak se semínko musí nějak označit. Důležité zejména pro uživatele na www.

Volné (checkbox): pokud je zaškrtnutý checkbox, tak jsou všechny zdroje v kolekci volné (např. pro tematické kolekce skládající se výhradně ze zdrojů Creative Commons), tudíž se označí všechny zdroje

///

**Frekvence** se defaultně nastavuje jako "manuálně" (kurátoři sklizně zadávají ručně do kalendáře), ale je možné ji nastavit podle běžných pravidel jako u zdrpjů a tímpádem se tematické sklizně přidají k semínkům s obdobnou frekvencí a objeví se v kalendáři

**Stav** jsou jen tři: nová, archivuje se, ukončeno. Nová: k dnešnímu datu není v kalendáři sklizní žádná provedená sklizeň této sbírky, archivuje se již byla provedena alespoň jedna sklizeň, ukončeno (zadávají ručně kurátoři -> nepředpokládají se další budoucí sklizně)

Zobrazení pro koncového uživatele #342

**Comment by kvasnicaj** [comment]
obrázek formuláře (nějak se nedaří upload u hlavního postu)
![2017-02-08 1](https://cloud.githubusercontent.com/assets/10117117/22742120/f0ed61c4-ee15-11e6-8958-c5f42e0b454e.png)

**Comment by Visgean** [comment]
> Frekvence se defaultně nastavuje jako "manuálně" (kurátoři sklizně zadávají ručně do kalendáře), ale je možné ji nastavit podle běžných pravidel jako u zdrpjů a tímpádem se tematické sklizně přidají k semínkům s obdobnou frekvencí a objeví se v kalendáři 

Takhle to nefunguje. Musi mit vyplnene datum a pak se objeci v kalendari.

**Comment by Visgean** [comment]
OK, rozsirim model harvestu aby do nej bylo mozne ukladat tyhle informace a pridam novou administraci pro harvest typu tematicka sbirka.

**Comment by kvasnicaj** [comment]
> Takhle to nefunguje. Musi mit vyplnene datum a pak se objeci v kalendari.

Ale takto by to přeci mělo fungovat, protože Seeder by měl automaticky naplánovat pravidelné sklizně viz např. #165

**Comment by Visgean** [comment]
seeder automaticky naplanuje sklizne ale tohle je mimo ten cyklus. 

Mohl bych tam k tomu pridat nejake rozhrani aby to slo planovat i takhle.

**Comment by kvasnicaj** [comment]
No já právě myslel, že když bych nastavil u tematické sklizně např. frekvenci 12x ročně, tak by ji Seeder automaticky doplnil do kalendáře k dalším sklizním se stejnou frekvencí, jestli mi rozumíš. 

Protože reálně v praxi se tyto pravidelné sklizně se stejnou frekvencí dělají všechny najednou.

**Comment by kvasnicaj** [comment]
Když na nějaký měsíc vyjde to, že se dělá sklizeň pro frekvence 12x ročně, 6x a 2x, např. nějaký červenec, tak se stejně vezmou všechny semínka najednou a sklidí se to.

**Comment by Visgean** [comment]
zamyslim se nad tim.

**Comment by holoubkovamonika** [comment]
Můžu poprosit o info, jak je tohle issue na tom? 

v seederu vidím, že ještě není celé přeložené do češtiny, aktuálně tam mám
- Topic collections - Tematické kolekce
- title - název
- created - vytvořeno
- Last Changed - poslední změna

když chci přidat novou kolekci, tak
- něco je stále v angličtině (title (název), annotation (anotace), image (obrázek), keywords (klíčová slova), attachements (přílohy), All sources are under open license or contract (Všechny zdroje jsou pod CC nebo mají smlouvu))
- nikde není možnost zadat termíny sklizně
- přílohy následně nejsou vidět na webu

Díky
@Visgean

**Comment by Visgean** [comment]
https://github.com/WebarchivCZ/Seeder/issues/370 and https://github.com/WebarchivCZ/Seeder/issues/369
