### ISSUE TITLE
Seznam URL adres u sklizně

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#344]
Při kliknutí na Seznam URL adres u sklizně to hodí err 500

Url:
http://war.webarchiv.cz/harvests/1/urls

**Comment by westfood** [comment]
http://war.webarchiv.cz/seeder/harvests/1/urls

**Comment by Visgean** [comment]
kde je problem?

**Comment by westfood** [comment]
nene, je to v cajku.. ale ten předchozí odkaz nefachal, tka jsem prdnul funkční..
