### ISSUE TITLE
Sklizně - úprava pro tematické sbírky

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#345]
Přidat k formuláři zadávání nové sklizně do kalendáře v sekci Sklizně nový prvek s možností výběru tematické sbírky (viz obrázek). Pokud kurátor vybere tematickou sbírku, tak pak už by měl zadat pouze datum a ostatní prvky by měly zmizet nebo zamezit možnosti editace.

![sklizen](https://cloud.githubusercontent.com/assets/10117117/22742834/7bf6e11c-ee18-11e6-88b4-1b12b8bb4b28.png)

![sklizen](https://cloud.githubusercontent.com/assets/10117117/22742970/e716974e-ee18-11e6-840b-8340dbd7193e.png)

**Comment by Visgean** [comment]
aha ok, no ja bych tam nechal i ty ostatni veci - pro manualni upravy...

**Comment by kvasnicaj** [comment]
To si právě nemyslím, že je dobrý nápad, protože pak by se to rozcházelo s tím, co je v administraci tematických sklizní

**Comment by Visgean** [comment]
zaviram tohle issue, feedback na novy system do separatniho issue prosim.
