### ISSUE TITLE
hledani - nice url

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#348]

**Comment by holoubkovamonika** [comment]
url adresa vypadá na starém i na novém webu jinak - což není extra na škodu https://drive.google.com/open?id=0BxWJijTKLjDDSUpJRkJZdnQtTmc

spíš mě tam ale zaráží, že mi to vyhledá úplně rozdílný počet položek - dá se s tím něco dělat/kde případně může být chyba? na novým webu je toho mnohem méně - je možné že tam není nahraná celá databáze? 
Díky ti

**Comment by Visgean** [comment]
Url adresy se daji prekladat, lze je upravit v transifexu. 

tady se jedna spis o problem s vyhledavanim. Podle katalogu je ve starem 5128  webu a v novem 4827. Tady se jedna o to, ze stale neni vyresene ktere zdroje muzou byt zobrazene verejne.

**Comment by Visgean** [comment]
(je to rozepsane v jinem issues tak zaviram.)

**Comment by holoubkovamonika** [comment]
V kterém prosímtě? :-)

**Comment by Visgean** [comment]
https://github.com/WebarchivCZ/Seeder/issues/342
