### ISSUE TITLE
view: url sklizni podle data

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#351]

**Comment by holoubkovamonika** [comment]
Můžu se zeptat o co přesně se jedná? Co by tohle mělo dělat/umět - případně jak se kouknu/zkontroluju, že to dělá, co má? Díky

**Comment by Visgean** [comment]
sjednocuje to libovolne seminka sklizni podle data. Spojuje to dohromady topic colections a sklizne.

**Comment by kvasnicaj** [comment]
bude řešeno jiným způsobem, je to zahrnuto v zadání pro novou verzi
