### ISSUE TITLE
Korektní postup upgrade

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#353]
Ahoj,

úplně nevím, jak udělat koretkní upgrade.. teď jsem si všiml, že migrate hlásí, že mám nejdřív dát makemigrations.. tak jsem udělal.. ale nemáš někde v Dockerfile popsané přesně ty kroky?

teď ./manage.py pouští
  - "makemigrations"
  - "migrate"
  - "collectstatic --noinput"
  - "rebuild_index --noinput"
  - "compilemessages"
  - "crontab add"

**Comment by Visgean** [comment]
takhle je to v pohode, az na ty makemigrations, ty prosim nikdy nezpoustej. 

na ten deployment jsem vytvoril scripty: https://github.com/WebarchivCZ/Seeder/blob/master/Seeder/pull_locales.sh a https://github.com/WebarchivCZ/Seeder/blob/master/Seeder/prepare.sh

**Comment by Visgean** [comment]
makemigration vytvori soubory migrace., kdyz je nedas do gitu tak se pak vytvori duplicity. ted jsem pushnul migracni soubor, takze migrate vytvori potrebnou strukuturu.

**Comment by westfood** [comment]
cajk, makremigrations jsem pustil jen jednou a poté migrate.

**Comment by Visgean** [comment]
ja prave myslim ze migrate neprobehlo, viz http://sentry.webarchiv.cz/sentry/seeder/issues/

**Comment by Visgean** [comment]
http://sentry.webarchiv.cz/sentry/seeder/issues/46/

**Comment by westfood** [comment]
```
(seeder) [rudolf@war Seeder]$ ./manage.py migrate
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'legacy_seeder'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.10/ref/databases/#mysql-sql-mode
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0004_auto_20170223_1425, 0004_auto_20170223_1457 in www).
To fix them run 'python manage.py makemigrations --merge'
```

**Comment by Visgean** [comment]
hmm to je presne o cem jsem mluvil, ten merge by to mel vyresit.

**Comment by westfood** [comment]
ok, mergnuto..
