### ISSUE TITLE
WWW - náhledy

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#356]
Při zobrazení katalogu nebo výsledku vyhledávání se nezobrazují náhledy stránek. 

Nevím, jak to máš teď vymyšlené. 

Ale aktuální stav je:
Screenshoty se nacházejí ve složce: webarchiv.cz/images/resource/thumb/

a párují se pomocí datumu, id z waadminu, název je teď takto: _small_<id>_<datum>.<přípona>_ např. small_453_20120502.jpg

http://www.webarchiv.cz/images/resource/thumb/small_453_20120502.jpg

btw: datum u screenshotu je poměrně důležitý kvůli tomu, že se dělá ze živého webu v době archivace. A máme tam .jpg .png

**Comment by Visgean** [comment]
tohle je issue https://github.com/WebarchivCZ/Seeder/issues/19 ale zaroven tedy zkusim vyuzit i existujicich screenshotu.

**Comment by kvasnicaj** [comment]
akorát jsem ho sem chtěl nalinkovat. Určitě těch existujících screenshotů využij, protože aktuálně jsou tam screenshoty pro všechny stránky, které je mají mít.

Problém s těma screenshotama je v tom, že automatické generování ne vždy funguje na 100% (hlavně u většího vzorku) a je potřeba manuální kontrola výsledku, což u těch našich proběhla

**Comment by Visgean** [comment]
ok

**Comment by holoubkovamonika** [comment]
Vypadá to, že tohle mi taky nefunguje (náhledy zdrojů na webu) , je chyba u mě nebo se na tom ještě pracuje? Díky

https://www.dropbox.com/s/m5yj6qudile039d/Screenshot%202017-03-07%2016.01.41.png?dl=0
