### ISSUE TITLE
Tlačítka přidat/nový

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#359]
Po posledním update jsem si všiml, že hlavní boční menu, už začíná přerůstat mez přehlednosti, tak mě napadlo vyjmout z něj položky Přidat zdroj a Přidat vydavatele a přesunout je na Dashboard. Viz screenshot:
![dashboard](https://cloud.githubusercontent.com/assets/10117117/23365048/baaccb90-fd01-11e6-8e62-b3460b7c9c9e.png)

U té příležitosti by bylo fajn sjednotit tlačítka u všech tabulek a to je všechny zarovnat vpravo: 
![topic-col](https://cloud.githubusercontent.com/assets/10117117/23365074/e18397f8-fd01-11e6-98cd-84f665cf9671.png)

A také poprosím přidat tlačítka s vytvořením nového zdroje resp. vydavatele k vydavatelům a přehledu zdrojů:
![zdroje](https://cloud.githubusercontent.com/assets/10117117/23365093/f274f9bc-fd01-11e6-9844-6043abc9017b.png)

**Comment by holoubkovamonika** [comment]
@Visgean 
v přehledu tlačíko nový zdroj/nový vydavatel nevidím - domlouvali jste se s Járou nějak jinak? že bude stačit, když tahle tlačítka budou pod položkou Zdroje a Vydavatelé? 

tlačítko přidat a zobrazit filtry ve zdrojích a vydavatelích je modré, místo zelené, ale to mi osobně přijde v pořádku :) 

Díky

**Comment by Visgean** [comment]
presunul jsem je do zalozek protoze je to konzistentni a dava to vetsi smysl.
