### ISSUE TITLE
klicova slova wakat api

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#364]

**Comment by mariehaskovcova** [comment]
@Visgean týká se to klíčových slov při zadávání tematických kolekcí? Vyhledávání je v tuto chvíli nefunkční, resp. lze jen listovat nabídkou, ale ne zadávat požadovaná slova

**Comment by Visgean** [comment]
Ne netyka.

**Comment by Visgean** [comment]
Vyhlwdavani je nefunkcni v jakem smyslu? Zadavani klicovych slov imho
funguje

**Comment by mariehaskovcova** [comment]
když chci přidat klíčové heslo architektura (je to věcná autorita, mělo by být ok), nenajde se mi nic, resp. vypadá to takto
![screenshot - klicova slova](https://cloud.githubusercontent.com/assets/19947819/24045428/5cea8516-0b1f-11e7-9a80-fddd0143fd86.png)

**Comment by Visgean** [comment]
Mozna chybi diakritika.

**Comment by mariehaskovcova** [comment]
"architektura" by asi neměla v tomhle smyslu (diakritika) být problém...? I kdyby tam ta architektura nebyla, zkoušela jsem hledat i jiná slova, která určitě v nabídce jsou (vidím, je, když nabídkou listuju níž) a také se mi nenašla!

Taky bych čekala, že hesla za sebou půjdou abecedně, ale třeba zrovna tohle problém není, nevím :)

**Comment by Visgean** [comment]
Ok potvrzuji, nove issue prosim

**Comment by mariehaskovcova** [comment]
ok, založím :)

**Comment by mariehaskovcova** [comment]
zavírám, viz issue #380
