### ISSUE TITLE
www a seeder

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#365]
Ahoj,

je teď nějak upravená konfigurace?

teď je defautní www http://war.webarchiv.cz/

seeder běží tady: http://war.webarchiv.cz/seeder/

Ale třeba ten seeder hází chybovky holkám, ale jen když kliknou na přehled.. u mě to fachá cajk (nemám asi žádné úkoly).. ale 

```
[pid: 5459|app: 0|req: 34/55] 195.113.132.25 () {42 vars in 906 bytes} [Mon Mar  6 15:22:30 2017] GET /seeder/ => generated 27 bytes in 115 msecs (HTTP/1.1 500) 4 headers in 145 bytes (1 switches on core 0)
```

**Comment by westfood** [comment]
jo a dotaz en future.. jak bude těžký provozovat seeder app a www app na oddělených serverech?

**Comment by Visgean** [comment]
ano, upravil jsem adresy aby to bylo pristupnejsi a ilustrovalo realny provoz. seeder app a www app lze provozovat na oddelenych serverech ale je potreba aby sdileli soubory (screenshoty a media) a aby sdileli databazi. je mozne nastavit pak v databazi jenom read only na tu www app.

**Comment by westfood** [comment]
Díkes..

nepadá tě něco s tím Dashboardem co holkám nefachá?

**Comment by Visgean** [comment]
Checknu sentry, tam by to melo byt videt

**Comment by holoubkovamonika** [comment]
Ahoj, 
jak to prosím vypadá, pořád nám to nefunguje :-(

**Comment by Visgean** [comment]
fixed in face7ad. @westfood

**Comment by Visgean** [comment]
@holoubkovamonika uz by to melo fungovat, az @westfood nasadi novou verzi.

**Comment by westfood** [comment]
Nasazeno
