### ISSUE TITLE
sync screenshots

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#367]
Pridal jsem novou manage command na sync screenshotu ze stareho webu, Muzes ji pustit @westfood?

``./manage.py legacy_sync_screenshots``

**Comment by westfood** [comment]
Můži pustit vícekrát?

**Comment by westfood** [comment]
Můžu ji pustit vícekrát?

**Comment by Visgean** [comment]
myslis paraelne?

**Comment by Visgean** [comment]
nn, tohle je v pohode.

**Comment by westfood** [comment]
tváří se, že cajk.. ale imho to by mělo vysolit changed namísto ok.. zkusím to ještě přímo ze stroje..

ok: [war] => (item=legacy_sync_screenshots)

**Comment by westfood** [comment]
jo, tak asi cajk..

**Comment by westfood** [comment]
Hele a jak je domluvná ta fyzická migrace těch screenshotů?

**Comment by Visgean** [comment]
fyzicka? tohle proste stahne vsechny screenshoty ktere to najde

**Comment by westfood** [comment]
jo, takže zkontaktuje manet a grabne screenshot?

**Comment by Visgean** [comment]
ne, tohle taha screenshoty z http://www.webarchiv.cz/images/resource/thumb/ , na manat je tam command ``generate_screenshots``.

**Comment by Visgean** [comment]
jeste jsem zapomel ze jsem trochu menil migraci, musis pred tim pustit znova legacy_sync.

**Comment by westfood** [comment]
kej, pustil jsem ji.

**Comment by westfood** [comment]
hele, asi to nic nedělá;-)

**Comment by Visgean** [comment]
pri nasazovani finalni verze se budou mazat stavajici data provede se cela migrace znova? jde mi o to jestli se timhle zabyvat do hloubky protoze to je proste tim, ze byla jinak syncnuta db..

**Comment by westfood** [comment]
hele, co se týče obrázků netuším.. Ale databáze se budu migrovat znova.

**Comment by Visgean** [comment]
ok tak to by ty pak melo byt v pohode.

**Comment by westfood** [comment]
Hele a funguje ta synchronizace obrázků nebo ne? Nám to tady neběží, tj. nemáme žádné náhledy.

**Comment by Visgean** [comment]
funguje, otestoval jsem to nove zmigrovane db a slo to v pohode.

![image](https://cloud.githubusercontent.com/assets/193832/24007496/abc420ca-0a66-11e7-8300-6615c8aeac30.png)

**Comment by westfood** [comment]
Tj. pokud udělám čistou novou migraci, tak by to mělo jít. Ale dokud ji neudělám, tak to neotestuji?

**Comment by Visgean** [comment]
Ja jsem udelal cistou migraci u sebe a fungovalo to.

**Comment by mariehaskovcova** [comment]
ahoj, takže předpokládám, že dokud neproběhne čistá migrace, náhledy otestovat/zkontrolovat nemůžeme?

**Comment by westfood** [comment]
Jj, kouknu na to dneska nebo v pondělí. Pak to zkontrolujeme.
