### ISSUE TITLE
  diakritika - doplnit, aby bylo možné vyhledávat i bez diakritiky (časopis = casopis)

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#373]
https://github.com/WebarchivCZ/Seeder/issues/295

**Comment by mariehaskovcova** [comment]
ahoj, hledání celkově je super, jen jsme narazili ještě na dílčí věc týkající se diakritiky, pokud je celý název buď s diakritikou nebo bez diakritiky, je to ok, pokud je diakritika správně jen částečně, už se zdroj nenajde, ukážu na příkladech:

zdroj Havířov, když zadám Havirov, je to ok, pokud zadám Havírov, zdroj se nenajde

nebo Česká republika, Ceska republika – ok, Ceská republika - nenajde

**Comment by Visgean** [comment]
Ok, tohle by melo byt vcelku jednoduse opravitelne. 

poznamka pro me:

Pridat stripovani diakritiky do operatoru OR v https://github.com/WebarchivCZ/Seeder/blob/master/Seeder/search_blob/models.py#L31
