### ISSUE TITLE
www - pokročilé vyhledávání

### ISSUE THREAD

**Issue by holoubkovamonika** [WebarchivCZ/Seeder#375]
Nefunguje mi pokročilé vyhledávání

při kliknutí na pokročilé vyhledávání z hlavní stránky mi to hodí hlášku 404: nenalezeno (viz http://war.webarchiv.cz/cs/%7Bplink%20advancedSearch%7D) 

při kliknutí z vyhledávání na "pokročilé vyhledávání" mi to hodí následující: https://drive.google.com/open?id=0BxWJijTKLjDDbGF2TUx0X0dmQ0U

Díky

**Comment by Visgean** [comment]
https://github.com/WebarchivCZ/Seeder/issues/324
