### ISSUE TITLE
hledání pomocí filtrů u Zdrojů  - podkategorie

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#377]
nefunguje vyhledávání podle podkategorie konspektu (Sub category), objevuje se buď Server Error 500 (např. podkategorie Botanika), nebo 0 Záznamů (např. podkategorie  Architektura)

**Comment by Visgean** [comment]
http://sentry.webarchiv.cz/sentry/seeder/issues/25/ kouknu na to.
