### ISSUE TITLE
tematické kolekce – přidávání klíčových slov

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#378]
nefunguje zadávání klíčových slov při tvorbě tematických kolekcí. Nelze přímo zadávat slova, je možné jen listovat v nabídce a vybírat je přímo z ní (hesla nejsou řazena abecedně, nabídka slov - zdá se - není úplná)
(#364)
![screenshot - klicova slova](https://cloud.githubusercontent.com/assets/19947819/24047120/153f2388-0b25-11e7-83f6-5870554eea1b.png)

**Comment by Visgean** [comment]
https://github.com/WebarchivCZ/Seeder/commit/4c7c9a716d2b619f88e888f2de099149b37d70ab
