### ISSUE TITLE
www - co zobrazovat

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#385]
> jak zjistim co je verejne pristupne?

odpoved: 

> to je správná otázka,
> musíme použít stejný klíč napříč celými www, protože na nich se pracuje jen s veřejně přístupnými 
> zdroji.
> 
> Problém je ten, že tak jak jsou teď nastavené statusy zdroje, tak z nich to bohužel nejde vyčíst. To vzniklo historicky z WA Adminu, kde to taky nebylo úplně logicky vytvořené.
> 
> Obecně lze říct, že teď je to tak, že všechny zdroje, které mají smlouvu a ta smlouva není vypovězená, jsou veřejně přístupné.
> 
> Ideální stav by byl, kdyby bylo možné lehce poupravit datový model u zdrojů a to tak, že všechny zdroje, které mají status Archiving accepted jsou veřejně přístupné.
> 
> S tím, že by se ze statusů zdroje musel odstranit status Contract expired a vytvořit se nový příznak nebo políčko u zdroje, kde by zaškrtávaly zdroje, které již nejsou na internetu, ale my je máme v archivu -> tyto zdroje se již nesklízejí, ale stále jsou veřejně přístupné.
> 
> Co myslíš? Bylo by to proveditelné?
> 
> U těchto zdrojů by se pak při migraci legacy databáze nastavil status Archiving accepted a zároveň by se jim zaškrtlo, že jsou to mrtvé zdroje viz tabulka migrace dat, co už jsem sem dával :)
>

**Comment by kvasnicaj** [comment]
Já to zjednoduším:

1) na www stránkách se budou zobrazovat pouze zdroje, které mají stav **Archivuje se**

2) přidej prosím nový údaj ke všem zdrojů: **Mrtvý zdroj**. Ten bude mít hodnoty pouze **ano/ne** a defaultně bude u všech zdrojů nastaveno **ne**

**Comment by Visgean** [comment]
a mrtve zdroje se maji zobrazovat?

**Comment by kvasnicaj** [comment]
ano
