### ISSUE TITLE
Manage.py nezná příkaz rebuild index

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#387]
Ahoj,

nehrál jsi si s tím Haystackem? Manage.py nezná rebuild index.

**Comment by Visgean** [comment]
chtel jsem ti to napsat nekam, smazal jsem elastic. Pridal jsem command ``search_blob_initialize`` ktera dela v podstate to same. Staci ji spustit jenom jednou a pak se to bude synchronizovat inkrementalne.

**Comment by westfood** [comment]
done
