### ISSUE TITLE
Zadani opakovane sklizne

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#388]
Pri zadani opakovane sklizne sa v kalendari objavi len prvy datum, vid 5. dubna 2017 - Skuska fuska, frekvence: tydne, user: divokeprasata. User nastaveny s pravom pridavat harvest (skupina kance)

**Comment by Visgean** [comment]
zadani opakovane sklizne funguje trochu jinak. Sklizne se automaticky vygeneruji na cely rok 
pomoci prikazu 

$ ./manage.py schedule_harvests

a pak je mozne sklizne editotovat rucne.

**Comment by kvasnicaj** [comment]
takto je to správně 👍
