### ISSUE TITLE
Sklizen nezachycuje manualne pridane seminka

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#389]
Su tam len mimosystemova seminka, vid Skuska fuska, generovane cez http://war.webarchiv.cz/seeder/harvests/3/urls:

Manualne nadefinovane zdroje:

abcd : art brut
Academic Publishing Platforms
Česká síť permanentních stanic pro určování polohy
Český svaz chovatelů masného skotu
Český svaz vodního póla
Český svaz zpracovatelů masa

**Comment by Visgean** [comment]
Po přepnutí sklizně do stavu running dojde ke zmražení semínek a nelze je měnit.
