### ISSUE TITLE
hledání: filtry – navrženo - kurátor - zdroje z Adminu

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#390]
při hledání přes filtry u zdrojů nefunguje pole „navrženo“ – položka „kurátor“. Respektive funguje, ale objeví se tam jen 3 testovací zdroje vzniklé v Seederu a nevyhledá to všechny ostatní zdroje z Adminu

![5c69827d4e7d46e3bd6cabe1988528f6](https://cloud.githubusercontent.com/assets/19947819/24659148/2817a446-194c-11e7-9e34-03f3217432ab.png)

**Comment by kvasnicaj** [comment]
jen dodám, že ostatní filtry fungují: navrženo uživatelem i ISSN

**Comment by kvasnicaj** [comment]
při schůzce fungovalo
