### ISSUE TITLE
WWW - stránka se smlovu

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#394]
Na stránkách chybí stránka se smlouvu: 

http://www.webarchiv.cz/cs/smlouva
(nemá anglický ekvivatent)

není to úplně veřejná stránka, tak proto si ji asi přehlídl. Tento odkaz posíláme uživatelům emailem, aby se mohli mrknout na smlouvu.

**Comment by Visgean** [comment]
btw chtel jsem rict, ze v tech about strankach atp je celkove hrozny bordel. Jako uzivatel ktery tam stravil nemalo casu furt nevim kolik presne about stranek tam je.

**Comment by kvasnicaj** [comment]
to se ti jen zdá :)) chceš nakreslit strom? :)
