### ISSUE TITLE
klíčová slova u tematických kolekcí

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#398]
při tvorbě tematických kolekcí se stáhnou k anotaci na webu všechna klíčová slova všech zdrojů. Protože by jich u obsáhlejších sklizní bylo strašně moc, chtěli bychom, aby se na webu zobrazovaly jen ty, které si navolíme v Seederu (ty se tam teď nezobrazují  - viz screen shoty). Díky

![kw2](https://cloud.githubusercontent.com/assets/19947819/26246675/a37c13f8-3c9a-11e7-96eb-fd53b77cf959.png)

![kw1](https://cloud.githubusercontent.com/assets/19947819/26246677/a684538a-3c9a-11e7-9402-6af4b7058acb.png)

**Comment by kvasnicaj** [comment]
Dávám tohle ještě jako blocker, protože bez této úpravy, nemůžeme ty ostré tematické kolekce dát na veřejnost. Btw: proč je tohle assigned na mě? :)

**Comment by Visgean** [comment]
Vsechno co jsem dal assigned na tebe je vyreseno.

**Comment by kvasnicaj** [comment]
díky za info, do konce týdne na to mrknu a pozavírám to.

**Comment by kvasnicaj** [comment]
#413
