### ISSUE TITLE
seznam veřejných semínek (ne-whitelist)

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#403]
přes api

všechny semínka se statusem archivuje se

**Comment by JanMeritus** [comment]
1. generovane semienka maju oproti domacej norme navic htttp a https
Po ich odstraneni a setrideni obou suborov mame:

5785 (pred zotriedenim na unique 5870) semienok v APIexp a v nasom whiteliste mame 10619 (mame vic adres na jednu zmluvu, napr. CUNI)

2. otazkou je z akych zdrojov sa beru tieto a co reprezentuju. Ich spolocny zaklad je 4757 semienok (prikladam ako spolocne.txt) zatial co rozdielne su u API 1028 (rozdilne.seederAPI.txt) a 5826 u Whitelistu (rozdilne.Whitelist.txt)
 
3. bude treba zistit pri formulacii dotazu na DB odkial a preco sa beru dane rozdiely

[rozdilne.seederAPI.txt](https://github.com/WebarchivCZ/Seeder/files/1153226/rozdilne.seederAPI.txt)
[rozdilne.Whitelist.txt](https://github.com/WebarchivCZ/Seeder/files/1153227/rozdilne.Whitelist.txt)
[spolocne.sem.txt](https://github.com/WebarchivCZ/Seeder/files/1153225/spolocne.sem.txt)

**Comment by Visgean** [comment]
Ta query ktera se v soucasnosti pouziva na DUMP je 
```
SELECT "source_seed"."url" FROM "source_seed" INNER JOIN "source_source" ON ("source_seed"."source_id" = "source_source"."id") WHERE ("source_seed"."state" = inc AND "source_source"."state" IN (success, forced) AND (("source_seed"."from_time" >= 2017-07-17 AND "source_seed"."to_time" <= 2017-07-17) OR "source_seed"."to_time" IS NULL))
```

**Comment by kvasnicaj** [comment]
```
SELECT COUNT( * ) 
FROM seeds
INNER JOIN resources ON seeds.resource_id = resources.id
WHERE seeds.seed_status_id =1
AND (resources.resource_status_id =5 OR resources.resource_status_id =9)
```

= 6356

Tohle by měl být správný počet semínek, který by měl vylézt z databáze. 
Náš whitelist pak bude asi obsahovat individuální semínka, které byly přidány mimo DB.

**Comment by kvasnicaj** [comment]
Ještě přikládám vlastní semínka z naší db. 
[waadmin_seeds.txt](https://github.com/WebarchivCZ/Seeder/files/1155309/waadmin_seeds.txt)

**Comment by Visgean** [comment]
![image](https://user-images.githubusercontent.com/193832/28310735-b4f6dc20-6bad-11e7-8069-80b6d1ca33e3.png)
takze 9 se ma taky archivovat?

**Comment by Visgean** [comment]
Hele ja bych idealne potreboval jedno konkretni seminko a zdroj ktere je u vas a jste si jisti, ze by mel byt u me.

**Comment by JanMeritus** [comment]
Po zotrideni waadmin_seeds.txt (6356) na unique je to presne 6264. (http a https obsahuje take nas vypis z DB, whitelist ho nema) 

5577 maju spolocnych : 
[spolocne.txt](https://github.com/WebarchivCZ/Seeder/files/1155456/spolocne.txt)


687 ma naviac waadmin: 
[waadmin_naviac.txt](https://github.com/WebarchivCZ/Seeder/files/1155452/waadmin_naviac.txt)



208 ma API dump naviac: 
[dump_naviac.txt](https://github.com/WebarchivCZ/Seeder/files/1155449/dump_naviac.txt)





1x. problem u waadmin_seeds: htto://csbslidice.cz         spatny format protokolu (neodstranen)

ca 80x problem  u API dumpu (pre ucely vyssieho zrovnavani odstraneno): 

www.radioeng.cz/number.php?number=3**&amp**;year=1993

www.radioeng.cz/number.php?number=3;year=1993 (viz waadmin_dump.txt)

**Comment by Visgean** [comment]
Ok, tak treba ted jsem si vzal zdroj: airforce.cz

![image](https://user-images.githubusercontent.com/193832/28312395-461ba3d4-6bb3-11e7-9bba-e678a7c2ce6c.png)

![image](https://user-images.githubusercontent.com/193832/28312407-4de5327e-6bb3-11e7-8336-6b2e6489907e.png)

Tenhle zdroj by se teda mel zahrnout do archivovani nebo ne?

**Comment by kvasnicaj** [comment]
ano do whitelistu má být zahrnut tzn. do toho API ano. Je proto stejné pravidlo jako jsme řešili v issue #385


Při generování semínek pro sklizně se pak mrtvé zdroje nezahrnují.

**Comment by Visgean** [comment]
![image](https://user-images.githubusercontent.com/193832/28313985-32f333de-6bb9-11e7-9b8b-170292bb91b2.png)
:( ale ok, pushnul jsem fix ktery to nastavuje

![image](https://user-images.githubusercontent.com/193832/28314006-4abf9b1a-6bb9-11e7-86d2-d4cd7dfb3a79.png)
je to takhle ok?

**Comment by kvasnicaj** [comment]
ano to issue bylo napsané správně, protože jsme se domlouvali, že status contract_expired se vyjme a udělá se z něj separátní hodnota a všechny zdroje, které měly tento status dostanou status archivuje se. viz #385 :)

**Comment by Visgean** [comment]
Aha, jo takhle, ja jsem to pak bral tak, ze jemom ten komentar plati. Ok, tak ja ten status odstranim.

**Comment by kvasnicaj** [comment]
My si u nás ty mrtvé zdroje evidujeme, před finální migrací označíme všechny zdroje, co mají status CONTRACT_EXPIRED převedem na status Archivuje se, aby nedošlo při migraci k chybám.

**Comment by Visgean** [comment]
Ja ten contract expired pouzivam jeste na jednu vec: system automaticky checkuje jestli vypresela smlouva a kdyz ano tak prehodi status. co s tim?

**Comment by Visgean** [comment]
Muzes prosim stavajici filtry otestovat? ja myslim ze takhle by to melo byt ok.

**Comment by kvasnicaj** [comment]
Otestováno a funguje ok. 

Contract expired nemá žádný zdroje, uzavíráme všechny smlouvy na dobu neurčitou. Ale pokud si tam vytvořil ten automatický check, jestli vypršela. Tak to tam nechme, ničemu to nevadí a třeba nějaký jiný archiv použije seeder a bude mít smlouvy na dobu určitou. 

Takže, až si to přečteš, tak to zavři, dík :)
