### ISSUE TITLE
WWW - Katalog - zobrazování

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#415]
- [x] [ ] Nastavit vizuální zobrazení jako primární
- [ ] [ ] Zobrazit zdroje už při vybrání hlavní kategorie
- [x] [ ] V EN verzi zobrazit Kategorie v angličtině

**Comment by Visgean** [comment]
Ok, opraveno. EN verze kategorie se nahrajou pri synchronizaci databaze.
