### ISSUE TITLE
tematicke kolekce - zobrazené zdroje

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#417]
Na www se nezobrazují mimosystémová semínka
![tk-seeder](https://user-images.githubusercontent.com/10117117/27792534-7266b114-5ffa-11e7-9344-b79b3cb1a449.png)
![tk-www](https://user-images.githubusercontent.com/10117117/27792535-72880030-5ffa-11e7-8220-d77c9d883b61.png)

**Comment by Visgean** [comment]
Sorry ale jak je mam zobrazovat kdyz k nim nejsou zadne dalsi informace?

**Comment by kvasnicaj** [comment]
nepotřebuješ další informace, stačí url. První máš odkaz na živý web. Pod tím máš to url a archivovaná verze vytvoříš odkaz z url do waybacku`http://wayback.webarchiv.cz/wayback/query?type=urlquery&url=`

**Comment by kvasnicaj** [comment]
teda ještě jinak. Jestli to URL není u nás v systému, tak místo toho modrého názvu zobrazíš neaktivní  url a bude aktivní pouze odkaz na archivní verzi a nadpis nebude modrý. 
A mohl bys prosím automaticky ořezat zobrazené url na nějakých cca 30 znaků, aby to nevypadalo blbě? S tím, že tím malým písmem bude zobrazené celé. Díky

**Comment by kvasnicaj** [comment]
![wa-sklizen-detail](https://user-images.githubusercontent.com/10117117/27797655-baacdf98-600e-11e7-8043-26e16cc6a784.png)

**Comment by Visgean** [comment]
No stejne k tomu ale nemam titulek nebo nazev

**Comment by kvasnicaj** [comment]
nazev = url

**Comment by Visgean** [comment]
Nemam tam dat radsi jenom domenu teda?

**Comment by kvasnicaj** [comment]
okej

**Comment by Visgean** [comment]
![image](https://user-images.githubusercontent.com/193832/28550519-aa2da79a-70e1-11e7-9154-15b7571d570f.png)

**Comment by kvasnicaj** [comment]
přesně tak jsem si to představoval, díky! 🥇
