### ISSUE TITLE
Seeder a haystack/elasticsearch

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#420]
Čéšť,

chtěl bych mít Elastic na jiném hostu než běží Seeder,  chápu správně, že stačí 'INDEX_NAME': 'haystack',  zaměnit za 'seeder-production' a 'seeder-dev' a všechno poběží z jedné instance elastic?

**Comment by Visgean** [comment]
Elastic uz se imho nepouziva.

**Comment by westfood** [comment]
Máš v Docker compose: - elastic

**Comment by westfood** [comment]
ale jo teď vidím: https://github.com/WebarchivCZ/Seeder/commit/19e89017fb9432e432aad540c7a7ff07dfb02ad5

**Comment by westfood** [comment]
takže manage.py search_blob_initialize je deprecated a není třeba ho pouštět?

**Comment by Visgean** [comment]
Neni, to je na vyhledavani v postgresql...

**Comment by westfood** [comment]
Hehe, jen pro ujasnění;-)

Není, jakože není třeba ho pouštět, páč to řeší PostgreSQL.

Nebo Není, jakože je potřeba ho pouštět kvůli vyhledávání v PostgreSQL?

**Comment by Visgean** [comment]
Je treba ho poustet.

**Comment by westfood** [comment]
Díky;-)

2017-08-07 16:18 GMT+02:00 Visgean Skeloru <notifications@github.com>:

> Je treba ho poustet.
>
