### ISSUE TITLE
WWW - Katalog stránek

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#426]
na katalogu stránek se teď vůbec nezobrazují kategorie ani v české, ani v anglické verzi. 

![cat](https://user-images.githubusercontent.com/10117117/29366048-36664e60-8299-11e7-9ab9-861fa5a16817.png)

**Comment by Visgean** [comment]
A provedli jste znovu migraci?

**Comment by westfood** [comment]
```
(seeder) [uwsgi@war]/mnt/raid1/git/Seeder% ./Seeder/manage.py migrate
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'legacy_seeder'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.10/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: admin, auth, authtoken, blacklists, comments, contenttypes, contracts, harvests, legacy_db, publishers, qa, reversion, search_blob, sessions, source, thumbnail, voting, www
Running migrations:
  Applying legacy_db.0002_conspectusen_conspectussubcategoriesen... OK
  Applying source.0002_auto_20170725_0047... OK
  Applying source.0003_auto_20170725_0117... OK
(seeder) [uwsgi@war]/mnt/raid1/git/Seeder%
```

**Comment by kvasnicaj** [comment]
po updatu je tam teď nějaký bullshit 
![cat2](https://user-images.githubusercontent.com/10117117/29368188-4a033b8a-829f-11e7-939c-ceca4d27cd2e.png)

**Comment by Visgean** [comment]
Ok to je divny

**Comment by Visgean** [comment]
Teda pockej, myslel jsem to takhle: Jarda pred tim rikal, ze pred plnym nasazenim se bude mazat databaze a provede se znovu legacy_sync, nechtel jsem delat castecnou synchronizaci kdyz se bude delat uplna. Tzn, tohle by se melo vyresit po uplne migraci.

**Comment by kvasnicaj** [comment]
jj tak jsme se domlouvali, @westfood můžeš udělat znovu legacy_sync? :)

**Comment by westfood** [comment]
jj, během zítřka.. potřebuju ještě pořešit síťaře.

**Comment by kvasnicaj** [comment]
tohle už funguje
