### ISSUE TITLE
WWW - nice urls?

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#427]
Ahoj, jak to bude s "pěknými" url adresami? 
Nyní je např. http://war.webarchiv.cz/cs/categories_url

v Poeditu jsme pak  "categories_url" k přeložení, to jsme udělali, v repozitáři by to mělo být nahrané, už delší dobu. Otázkou je, jestli se to vztahuje k těm url a co je potřeba udělat, aby se to projevilo?

**Comment by Visgean** [comment]
Melo by stacit jenom zkompilovat preklady a restartovat server..

**Comment by westfood** [comment]
pustil jsem compilemessages, restartoval uwsgi, nginx a prej furt pěkný ty url nejsou.

```
(seeder) [uwsgi@war]/mnt/raid1/git/Seeder% ./Seeder/manage.py compilemessages
processing file django.po in /mnt/raid1/git/Seeder/Seeder/locale/cs/LC_MESSAGES
processing file django.po in /mnt/raid1/git/Seeder/Seeder/locale/en/LC_MESSAGES
processing file django.po in /mnt/raid1/git/Seeder/Seeder/locale/en_US/LC_MESSAGES
processing file django.po in /mnt/raid1/git/Seeder/Seeder/locale/en_GB/LC_MESSAGES
```

**Comment by Visgean** [comment]
Ok pushnul jsem, musel jsem zmenit system url aby se dali prekladat. Nektere budete muset asi prelozit znova, od ted se ale prekladaji cele regularni vyrazy tak na to bacha.

**Comment by kvasnicaj** [comment]
Pořád nefunguje. U české verze stále zůstávají URL typu: https://app.webarchiv.cz/cs/about_contact_url

V Seeder/locale/cs/LC_MESSAGES/django.po je to přeložený...

**Comment by Visgean** [comment]
imho to same issue jako #432

**Comment by kvasnicaj** [comment]
už funguje viz #432

**Comment by kvasnicaj** [comment]
teď jsme nahráli nové překlady a vše proběhlo v pořádku, až na to, že místo českých URL jsou anglické. Mohl bys na to prosím mrknout? @Visgean

**Comment by Visgean** [comment]
fix v db8b40a, menil jsem urls a tak ty ceske preklady potom nefungovali. Tak jsem zase musel vygenerovat nove pres makemessages.
