### ISSUE TITLE
čeština - seeder

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#432]
čeština nějak nefunguje. Teď to vypadá asi takto:
![cz-seeder](https://user-images.githubusercontent.com/10117117/30583941-9aa27198-9d28-11e7-9e71-8bbccb536ec9.png)

Na úvodní stránce je přeložený jedno slovo a dále ta frekvence není o moc větší. V souboru s češtinou je všechno přeložený.

**Comment by Visgean** [comment]
A je to zkompilovany?

**Comment by Visgean** [comment]
```
locale/
├── cs
│   └── LC_MESSAGES
│       ├── django.mo
│       └── django.po
├── en
│   └── LC_MESSAGES
│       └── django.mo
└── en_US
    └── LC_MESSAGES
        └── django.po
```
takhle to mam ja a funguje mi to.

**Comment by westfood** [comment]
jo compilemessages nebyl krok při deploy, přidal jsem ho.. teď jsem ho ručně spusti a reloadnul uwsgi

```
(seeder) -bash-4.2$ Seeder/manage.py compilemessages
processing file django.po in /opt/Seeder/Seeder/locale/en_US/LC_MESSAGES
processing file django.po in /opt/Seeder/Seeder/locale/cs/LC_MESSAGES
```

**Comment by kvasnicaj** [comment]
👍

**Comment by kvasnicaj** [comment]
ještě se zeptám, který soubor editovat, abychom mohli měnit původní anglické texty?

**Comment by Visgean** [comment]
edituj ten en soubor.

**Comment by kvasnicaj** [comment]
ok díky
