### ISSUE TITLE
generované odkazy u zdrojů

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#433]
nefungují generované odkazy do waybacku a na screenshot.
Viz: https://seeder.webarchiv.cz/seeder/source/detail/8273

WWW link vede někam sem: /en/www_source_url/8273-wwwabastaborislavcz

A screenshot sem https://seeder.webarchiv.cz/media/opt/Seeder/Seeder/media/screenshots/small_8532_2015-06-05.png

**Comment by westfood** [comment]
to bude na mě, důsledek reverzní proxy pro seeder..

tohle fachá: https://app.webarchiv.cz/media/screenshots/small_8532_2015-06-05.png

musím tyhle případy ošetřit..

**Comment by kvasnicaj** [comment]
těch případů tam bude asi docela hodně... viz #434

**Comment by kvasnicaj** [comment]
na této adrese to funguje :) app.webarchiv.cz/seeder/

**Comment by kvasnicaj** [comment]
ale když si ten screenshot chceš rozkliknout, tak hodí 404

**Comment by westfood** [comment]
jo, to možná taky na mě..

generuje to: https://app.webarchiv.cz/media/opt/Seeder/Seeder/media/screenshots/small_8532_2015-06-05.png namísto https://app.webarchiv.cz/media/screenshots/small_8532_2015-06-05.png 

za to může revezní proxy, pořeším to odpoledne..

**Comment by westfood** [comment]
hele, tak beru zpět:

vanilla seeder mi generuje:

http://10.3.0.60/media/opt/Seeder/Seeder/media/screenshots/small_8532_2015-06-05.png

namísto

http://10.3.0.60/media/screenshots/small_8532_2015-06-05.png

to /opt/Seeder/Seeder/ je cesta k instalaci Seederu.. o tom ví nginx prd.. zná jen sock.. tj. tohle nějak konstuuje aplikace.

@Visgean nenapadá tě něco?

**Comment by westfood** [comment]
@Visgean hele, podle mě je to trabl v appce.. nginx má správně nastavenou location

/media na root /opt/Seeder/Seeder

tj. požadvek si šáhne pro obrázek do /opt/Seeder/Seeder/media

ale seeder chce /media/opt/Seeder/Seeder/media/screenshots/small_8532_2015-06-05.png to si vygeneruje sama appka.. né nginx.

url pro thumbnaily se generuje správně, ale screenshoty špatně

v dockeru po legacy_sync jsem nenašel žádnej zdroj se screenshotem.. tak v něm neotestuji. Koukneš se na to?

**Comment by Visgean** [comment]
prosim otestovat po zmenach co jsem udelal dneska.

**Comment by kvasnicaj** [comment]
po rozkliknutí screenshotu u zdroje se pořád dostanu na nesmyslný odkaz: 
https://seeder.webarchiv.cz/media/opt/Seeder/Seeder/media/screenshots/

**Comment by kvasnicaj** [comment]
rozkliknutí screenshotu nefunguje z obou adres, další odkazy na web fungují pouze z webarchiv.cz/seeder a nefungují ze seeder.webarchiv.cz

**Comment by Visgean** [comment]
Tak mate blbe nastavenou MEDIA_URL.

**Comment by JanMeritus** [comment]
No media URL som zatim nenastavoval, ale v base.py mas:

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
tj. podla mojho nazoru je tohle zle, tym ze to bere MEDIA_ROOT, tje cestu BASE_DIR a media dokopy miesto MEDIA_URL, toz si myslim ze thumbsi to beru spravne, ale screenshoty maju MEDIA_ROOT ako odkaz

**Comment by Visgean** [comment]
media root je imho v pohode. Media url je mozna divna, nevim jake mate nastavani deploymentu, checkni https://docs.djangoproject.com/en/1.11/ref/settings/#media-root

**Comment by JanMeritus** [comment]
ja neviem, tam sa pise totok:

MEDIA_ROOT¶
Default: '' (Empty string)
Absolute filesystem path to the directory that will hold user-uploaded files.

_Example: "/var/www/example.com/media/"_

MEDIA_URL¶

Default: '' (Empty string)

URL that handles the media served from MEDIA_ROOT, used for managing stored files. It must end in a slash if set to a non-empty value. You will need to configure these files to be served in both development and production environments.

If you want to use {{ MEDIA_URL }} in your templates, add 'django.template.context_processors.media' in the 'context_processors' option of TEMPLATES.

Example: "http://media.example.com/"

Mne z toho vychadza, ze ak tam mas nieco navyse oproti default, tak to hadze tie divne odkazy.

**Comment by Visgean** [comment]
Ne nemam. Vy si musite na serveru v local settings nastavit nejakou cestu
kde vy mate endpoint

**Comment by JanMeritus** [comment]
Totok si tu zatial ulozim:

Sucasny stav
https://seeder.webarchiv.cz/media/opt/Seeder/Seeder/media/screenshots/small_8532_2015-06-05.png
: 404 Not Found

**Comment by Visgean** [comment]
Tak zkus nastavit media url na "https://seeder.webarchiv.cz/media"

**Comment by Visgean** [comment]
resp "https://seeder.webarchiv.cz/media/"

**Comment by JanMeritus** [comment]
jj, ted neco skusam, akurat som maznul pyc a uvidime co z toho vyleze :)

**Comment by kvasnicaj** [comment]
teď už se nezobrazují ani náhledy :)

**Comment by Visgean** [comment]
Hmm hele oredtim se zobrazovali? To je teda fakt problem u me

**Comment by JanMeritus** [comment]
#Visgean, to je u nas, zajtra poriesim

**Comment by kvasnicaj** [comment]
jj předtím se zobrazovaly náhled, ale po kliknutí na ně to nefungovalo

**Comment by Visgean** [comment]
Ok v tom pripade je media url v pohode

**Comment by Visgean** [comment]
Tak jak byla teda

**Comment by Visgean** [comment]
jj, to by mel byt v pohode

**Comment by JanMeritus** [comment]
tj v zasade ty u nich dynamicky generujes cesty?

@kvasnicaj pripravite s Andrejkou update db? poobede nahodim

**Comment by kvasnicaj** [comment]
@JanMeritus příští týden, Andrejka má dovolenou :)
