### ISSUE TITLE
News - image

### ISSUE THREAD

**Issue by holoubkovamonika** [WebarchivCZ/Seeder#434]
Zdravím,
když vkládám relativně velký obrázek do aktualit/news, tak mi to hodí hlášku "413 Request Entity Too Large". Dalo by se s tím prosím něco dělat? 

A pokud se mi obrázek povede nahrát, tak pak stejně není v záznamu vidět. To by taky bylo pěkné kdyby fičelo.

Díky

**Comment by kvasnicaj** [comment]
obrázek už je vidět, jen bych chtělo ošetřit to nahrávání obrázku, ať to nepadá do 413...

**Comment by westfood** [comment]
a tak to bude opět na straně nginx, upravím konfiguraci: client_max_body_size

**Comment by kvasnicaj** [comment]
spíš mi jde o to, aby to zahlásilo nějaký normální err, že je ten obrázek moc velký

**Comment by westfood** [comment]
nastavím větší velikost.. jaké chcete omezení 1 MB, 5 MB ?

Můžu pak nahodit custom message v nginx, asi takhle: https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04

**Comment by kvasnicaj** [comment]
1MB dej a s tou custom message  to bude ok

**Comment by Visgean** [comment]
1 mb je fakt malo.

**Comment by westfood** [comment]
Tak nahoďte numero. Klidně 5 MB

**Comment by kvasnicaj** [comment]
jo klidně dejte 5MB, mi jen šlo o to, abychom na titulku nedávaly 5MB obrázky pro novinku :)

**Comment by Visgean** [comment]
oni se daji zmensit thumbnailem

**Comment by westfood** [comment]
nastavil jsem na nginxu na backendu client_max_body_size 8m; mám to tak už na reverzní proxy..

**Comment by westfood** [comment]
prosím @holoubkovamonika ať otestuje větší soubor, pod 8 MB a nad 8 MB.. hezkou chybovku si dám jako úkol.

**Comment by holoubkovamonika** [comment]
Otestováno

do 6,2 MB mi to jelo krásně - nahrálo se
pak sem tam šupla 36 MB a buchlo to - resp opět hláška "413 Request Entity Too Large"

**Comment by westfood** [comment]
To je správné chování, předpokládám že 36 MB nepotřebujeme uploadovat? Připravil jsem si issue tady: https://github.com/NLCR/ansible-seeder/issues/3 - někdy se na to podívám, předpokládám, že to moc nespěchá. Asi nemá smysl to řešit na úrovni aplikace, páč je to nastavení HTTP serveru.

Takže bych to uzavřel, cajk?

**Comment by holoubkovamonika** [comment]
Těm slovům po issue zcela nerozumím, ale za mě cajk :) Obří věci uploadovat nepotřebujem :)

**Comment by westfood** [comment]
cajké finité
