### ISSUE TITLE
Označení: Dead Sources

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#436]
Mohl bys prosím změnit značení mrtvých zdrojů v tabulce, protože teď je to matoucí.
Teď je tam křížek pokud je zdroj živý a fajfka pokud je mrtvý. Mohl bys to změnit na křížek pokud je mrtvý a žádný symbol pokud je živý.

Dále není na kartě nijak označen mrtvý zdroj. Mohl bys přidat ke statusu nějaký symbol nebo text, aby to bylo zřejmé?

A poslední věc, ve filtrech máš pro vybrání mrtvých zdrojů tři možnosti, ale možnost 'unknown' nikdy nenastane. 

![ds](https://user-images.githubusercontent.com/10117117/30637376-70bc8e88-9df8-11e7-8f98-dfe2ed69ee60.png)

**Comment by Visgean** [comment]
Ve filtrech je unknown z toho duvodu kdyz chces zobrazit zive i mrtve.

**Comment by kvasnicaj** [comment]
přejmenujeme na 'all'?

**Comment by Visgean** [comment]
Hele to prave nejde udelat uplne jednoduse - ty filtry se generuji pomoci django-filters frameworku nad kterym nemam kontrolu, zkusim jim treba zalozit issue.

**Comment by kvasnicaj** [comment]
ok, o nic nejde. To je jen drobnost.
