### ISSUE TITLE
Tematické kolekce - detekce zdrojů

### ISSUE THREAD

**Issue by holoubkovamonika** [WebarchivCZ/Seeder#438]
Zdravím,

mám dotaz k rozšifrování zdrojů, s kterými máme smlouvu - nebo nemáme smlouvu.
Vize byla taková, že kupu zdrojů (at těch co máme i těch co nemáme) šoupneme do nějakého políčka a seeder si sám vyzobe/vyznačí ty se smlouvou... ale není tomu tak - máme pole na mimosystémová semínka (bez smlouvy) a pole pro přiřazené zdroje (se smlouvou)...

Bylo by potřeba to prosím změnit. 

Zároveň budeme přidávat i zdroje se smlouvou - ale jenom konkrétní článek (např. máme web Digizone, ale do kolekce budeme dávat jen tenhle článek: http://www.digizone.cz/clanky/vladni-krize-pomaha-ct24-i-tv-barrandov-tyden-s-prezidentem-vyskocil-o-164-tisic/) tak aby to bylo ošetřeno tak, že seeder bude schopen rozpoznat i tohle.

Děkujeme

**Comment by holoubkovamonika** [comment]
add "vtipná věc"

archivujeme např. krestandnes.cz
aktuálně máme v jedné z kolekcí i stránku krestandnes.cz/dan-drapal-vladni-krize-cesku což je super a cool, ale vlastně uplně nanic...

protože když ji chceme vložit jako "přiřazený zdroj" - tj. zdroj, který archivujeme, tak máme smolíka, protože "přiřazený zdroj" to bere jen a pouze jako "krestandnes.cz" což zas tak cool není...

díky za vyřešení :)

**Comment by Visgean** [comment]
Sorry tohle je komplikovana vec ktera imho nebyla puvodne v zadani a je to docela slozita uprava. Neni to mozne udelat ted hned.

**Comment by kvasnicaj** [comment]
v zadání to bylo viz #343 

> Semínka: textový seznam semínek, kurátoři nahrají celý seznam. Seeder by měl po odeslání formuláře zkontrolovat url vůči databázi, zda některé url se v dabázi nenacházejí. Pokud semínko najde a má platnou smlouvu, pak se semínko musí nějak označit. Důležité zejména pro uživatele na www.

Nicméně to není důležitý, není to třeba dělat hned. Ber to jako další věc, co je třeba dodělat.

**Comment by Visgean** [comment]
Ono se to i deje: https://github.com/WebarchivCZ/Seeder/blob/master/Seeder/harvests/models.py#L65 ale neumi to detekovat rozdilne url  na zaklade treba domeny.
