### ISSUE TITLE
Přidat web - err 500

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#441]
Po odeslání formuláře to hodí err 500

**Comment by westfood** [comment]
@Visgean není to společné s tímho: https://sentry.webarchiv.cz/sentry/seeder/issues/105/

**Comment by Visgean** [comment]
imho je.

**Comment by westfood** [comment]
a je to na mě nebo na tebe?

**Comment by Visgean** [comment]
na me, delam na tom.
