### ISSUE TITLE
Historie úprav

### ISSUE THREAD

**Issue by holoubkovamonika** [WebarchivCZ/Seeder#442]
zdravím,
mám dotaz k historiím úprav u jednotlivých zdrojů/aktualit/tematických kolekcí atp...

u tematických kolekcí/zdrojů když koukám na historii úprav a chci se kouknout kdo je udělal, tak je tam autor "none" - bylo by dobrý, kdyby tam byl **konkrétní člověk**, který tu změnu provedl...

u aktualit mi to pro jistotu při kliknutí na historii píše **server error 500**

ještě jeden bod navíc... u zdroje - při úpravě "kurátora" se mi v historii ukázalo **prázdno - žádná změna...** až pak ještě po další úpravě (frekvence sklízení) se mi teprve v historii zobrazilo info o změně kurátora i o změně frekvence sklízení... (původní pocit byl, že se historie ukazuje až po druhé úpravě, ale zjištěno, že u Marušky se to zobrazuje jinak - jí se tam sice až na druhou úpravu ukázala nějaká změna, každopádně ta první změna zaznamenána nebyla...)

kdyby se s tím dalo něco dělat, tak by to bylo super :)

**Comment by kvasnicaj** [comment]
https://sentry.webarchiv.cz/sentry/seeder/issues/59/

**Comment by Fasand** [comment]
Je tenhle issue porad aktualni? Na Sentry uz mi to nic nenajde a kdyz zkousim editovat a koukat na historii u tematickych kolekci nebo aktualit, tak se mi vse zobrazuje spravne na testovaci verzi.

**Comment by holoubkovamonika** [comment]
Issue je již aktuálně v pořádku.
