### ISSUE TITLE
Creative Commons zdroje

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#443]
při importu nedošlo k označení zdrojů, které jsou pod CC licencí. 

mohl bys je označit zpětně bez toho, aby se musel provádět znovu opravený import? 

seznam je tady
[cc-resources.csv.zip](https://github.com/WebarchivCZ/Seeder/files/1336502/cc-resources.csv.zip)

**Comment by Visgean** [comment]
ok udelam na to script, je to trochu komplikovany

**Comment by JanMeritus** [comment]
Bude ta vec frcat i pri novej inicializacii a prvemu umportu do vanilla instalacky?

**Comment by Visgean** [comment]
asi ano, ale jestli se bude delat znovu import tak by me spis zajimalo kde je problem.

**Comment by Visgean** [comment]
pridal jsem command 
```
./manage.py sync_cc_status
```
u me probehla v poradku, prosim o otestovani (idealne ne na ostrem serveru. )

**Comment by mariehaskovcova** [comment]
@westfood, @JanMeritus, dejte nám pak prosím vědět, kde můžeme zdroje Creative Commons zkontrolovat, dík

**Comment by westfood** [comment]
@visgean tady výstup z importu, který je teď na produkci.

https://github.com/WebarchivCZ/Seeder/issues/431#issuecomment-330576778

**Comment by westfood** [comment]
Když to Zdenko nestihne do víkendu, juknu na to víkendu. Nemám teď v hlavě, v jakém stavu je testovací prostředí.

**Comment by westfood** [comment]
Inicioval jsem legacy_sync na testovacím seederu: http://www-dev.webarchiv.cz/seeder/ poběží tak hodinu. 

Ráno prosím @holoubkovamonika @mariehaskovcova, aby se podívali, zda jsou ty CC rozbité (měli by být). Napište a Zdenko nebo já pustí ten ```./manage.py sync_cc_status```

jméno a heslo dám na slack testovacímu seeder dám na slack.

**Comment by kvasnicaj** [comment]
cc na testovacím seederu nebyly. Zkoušeli jste už to  ./manage.py sync_cc_status ? @JanMeritus

**Comment by kvasnicaj** [comment]
tak jsme to testovali a nefunguje, můžeš se na to ještě podívat @Visgean ?

**Comment by Visgean** [comment]
Hmm, jaky je tady status? Furt nic?

**Comment by Visgean** [comment]
Imho to bude mozna nejlepsi updatnout manualne...

**Comment by kvasnicaj** [comment]
ok, já zkusím něco vymyslet

**Comment by kvasnicaj** [comment]
vytvořil jsem sql a updatovali jsme databázi, takže už máme označené cc smlouvy. Můžeme si je vylistovat, ale když je rozklikneme, tak u cc mají prázdný řádek. (pokud nejsou cc, tak je tam _ne_)

![35077175_457402411356306_87174435810836480_n](https://user-images.githubusercontent.com/10117117/41349330-d9356352-6f0f-11e8-9336-9a3590313d22.jpg)

![35151647_10212176863443149_1206910617907101696_n](https://user-images.githubusercontent.com/10117117/41349355-eeb5bd3a-6f0f-11e8-8955-cd209cfb1c6c.png)


můžeš na to mrknout @Visgean ?

**Comment by Visgean** [comment]
aha to je svlastni, kouknu na to.

**Comment by Fasand** [comment]
Je tam jeste porad nejaky problem s tim `sync_cc_status` nebo necim podobnym nebo uz jde jenom o to zobrazeni CC typu?

**Comment by kvasnicaj** [comment]
už jde jen o tom, že se nezobrazuje 'ano' :) jinak vše funguje korektně

**Comment by Fasand** [comment]
Ok, ke smlouvam jsem misto toho prazdneho policka dal typ licence i s prolinkovanim na zdroj. (PR jeste neni)
