### ISSUE TITLE
URL - hledat - zdroj

### ISSUE THREAD

**Issue by holoubkovamonika** [WebarchivCZ/Seeder#444]
mám dotaz - prosbu - koukám ted na nějaký naše URL - běžně mi fičel (příklad) webarchiv.cz/cs/**zdroj**/chromatografie - uplně v cajku, ale ted už nee, ted uz mi to fičí jen na webarchiv.cz/cs/**hledat**/chromatografie

což jako není blbý (se slovem hledat se dá žít...), ale dost je to opruz protože fůru odkazů který máme minimálně na FB ted nefunguje - viz kolekce mrtvých webů a tak... nešlo by to vyřešit nějak jinak - než že bych se musela vrátit ke každýmu odkazu a přepisovat ho? pořešit to pouhým překladem nebo je třeba něco sofistikovanějšího...

(stejně tak ve verzi AJ, kterou ale nemám potřebu hrotit, protože to se směrem ven nepoužívalo...)

Díky

**Comment by Visgean** [comment]
Tady by se to imho nejlepe resilo redirectem na nginxu @westfood

**Comment by westfood** [comment]
Je s tím @kvasnicaj @JanMeritus zajedno?

**Comment by Visgean** [comment]
Sorry, ted jsem si uvedomil ze vlastne tam dost podobna funkcionalita je - https://github.com/WebarchivCZ/Seeder/blob/master/Seeder/urls.py#L116 takze je dost mozne ze je jenom spatne prelozena adresa.

**Comment by JanMeritus** [comment]
Ak to tam mas, radsej by som to upravil v seedru nez v nastaveniach nginxu (pri novej instalacii to pridava na komplexite krokov) a idealne co najmenej platoval lokalnymi nastaveniami. Ale nech si povie @kvasnicaj, pripadne @westfood ako experienced odbornik.

**Comment by kvasnicaj** [comment]
to bude chyba v překladu, problém je, že tam není úplně jasné, jaké url kam patří. Tudíž jsme to všechno přeložili jako 'hledat'. Ale určitě bude stačit

**Comment by kvasnicaj** [comment]
hele tak jsem koukal do překladu a překlad vypadá takto: 
<img width="598" alt="preklad-url" src="https://user-images.githubusercontent.com/10117117/32221485-ffa8d824-be35-11e7-9412-a7384d85feeb.png">


takže chyba bude asi někde jinde. @Visgean můžeš se na to podívat?

**Comment by Visgean** [comment]
vyresil jsem to tak, ze pokud zdroj nenajdu podle slugu tak to presmeruje uzivatele na vyhledavani.

**Comment by Visgean** [comment]
tzn vysledek je ze webarchiv.cz/cs/zdroj/chromatografie  bude fungovat ale uzivatel skonci na strance webarchiv.cz/cs/hledat/chromatografie
