### ISSUE TITLE
Seeder Redirect

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#445]
Ako som uz zmienoval na slacku, je tu problem s funkcnostou seedru pri vyhledavani adres:

napr. "zitbrno.cz", a cokolvek zadane v tomto tvare hadze podivnu redirect adresu s https. V pripade ze cez vyhladavacie menu bolo zadane len "zitbrno", zobrazili sa najprv v seedry len kategorie stranok cez ktorych vyber sa dostal odkaz na War ktory fungoval v pohode.

Vyzera, ze to bude problem skor na nasu infra, nez na Visgeana, ale bolo by fajn, keby si nam mohol povedat ako vyzera u teba hadzanie tej adresy z vyhladavania na landingC page a v akej forme to predava dalej.

```
10.1.6.111 - - [16/Oct/2017:15:06:49 +0200] "GET /wayback/query?type=urlquery&url=zitbrno.cz HTTP/1.1" 404 4987
10.1.6.111 - - [16/Oct/2017:15:17:39 +0200] "GET /wayback/query?type=urlquery&url=zitbrno.cz HTTP/1.1" 404 4987
10.1.6.111 - - [16/Oct/2017:15:17:42 +0200] "GET /wayback/query?type=urlquery&url=zitbrno.cz
```

Chyba sa vyskytuje na WaPublic-u a v zaujme docasnej opravy tejto kritickej issue som pozmenil konfigurak aggregatus.https.conf, kde som pridal nasledovne riadky: 

```
 #issue 445
 RewriteEngine On
 RewriteRule ^.*(wayback\/query.*)$ http://wayback.webarchiv.cz/$1 
```
tj. v pripade https to prepise na http a preda to na server War, ktory si s tymto uz poradi.

**Chyba je tymto zasahom eliminovana na produkcii** ale pride mi to ako nesystemove riesenie, obzvlast vzhladom k fungujucemu prepojeniu na Wayback z "standardneho" vyhladavania.

**Comment by Visgean** [comment]
No byl tak nejaky request ze kdyz je to url tak ho mam redirectnout na wayback - koukni sem https://github.com/WebarchivCZ/Seeder/blob/master/Seeder/www/views.py#L311 jestli ti to pomuze

**Comment by kvasnicaj** [comment]
@Visgean problém je jen ve špatném URL kam se přesměrovává. @JanMeritus sem hodí správné URL

**Comment by kvasnicaj** [comment]
řešení v #450
