### ISSUE TITLE
Seeder Redirect Excluded Seminka 

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#446]
Ahoj, 

mozno je to feature, mozno je to bug. Seminka (ale hlavne ich podseminka) co si holky v seedru oznacia ako exclude k vyjmuti ze sklizne by nam mali chodit emailom aby sme mohli nastavit podla toho Heritrix. Ale nechodi.

Vec II. su weby ktore proste sklizime, ale vydavatelia nechcu aby sa ich cast zobrazovala mimo NK vo Waybacku. To je v zasade trabl na mna (musim si poriesit tie linky), ale bolo by fajn, ze by mohli tak byt oznacene i v Seedru a nezobrazovat sa v tom zakladnom vyhladavani co mas na landing page, prip. to nepresmerovavalo na wayback v tychto pripadoch.

**Comment by mariehaskovcova** [comment]
semínka, která měla v Adminu stav excluded (části webu archivovaných zdrojů), jsou stále viditelná
konkrétně např:
http://poslouchej.net,  excluded: http://shop.poslouchej.net
http://mistoproprirodu.cz,  excluded: http://www.mistoproprirodu.cz/e-shop/

**Comment by Visgean** [comment]
kde presne jsou vyditelna?

**Comment by JanMeritus** [comment]
Ahoj, po zadani hledani, napr. "medo". Tomu by mal seeder zamedzit kedze ma v DB ze totok nie. Za Openwayback poriesim zatial rewritami.

![screenshot from 2017-10-18 19-35-15](https://user-images.githubusercontent.com/25201690/31734376-cefe7cc0-b43e-11e7-920b-dd50e0ad9e3c.png)

**Comment by mariehaskovcova** [comment]
to @Visgean Ty části webů, které mají stav excluded, by neměli vidět návštěvníci zvenčí na našem webu přes wayback (jen v budově NK). Ještě ale najdeme pár dalších zdrojů s excluded semínky a ověříme... A probereme pak s Járou

**Comment by Visgean** [comment]
ok checknu to.

**Comment by kvasnicaj** [comment]
tohle je deep shit... já to chápu tak, že excluded **semínka** jsou URL vyřazený ze sklízení, ale **zdroj** pokud má smlouvu jde na webu vidět, tzn. status **semínka** nemá vliv na zpřístupnění zdroje. Zatímco pokud chceme znepřístupnit nějaký web, tak se změní jeho status... Ale opravte mě, jestli ten problém špatně chápu :)

**Comment by Visgean** [comment]
Aktualne se do verejneho vyhledavani dostavaji vsechny tyhle zdroje: 
![image](https://user-images.githubusercontent.com/193832/32224763-a45cec3a-be3a-11e7-94f5-f25032233d7c.png)

mam to zmenit jenom tak aby ve verejnem vyhledavani byli jenom se stavem running?

**Comment by kvasnicaj** [comment]
my to ještě probereme a dáme ti vědět, zatím to nechej tak. Dík

**Comment by Visgean** [comment]
Ok, pripravil jsem zmenu do masteru https://github.com/WebarchivCZ/Seeder/commit/5264aba8dd8366fc06a51c53be9b02bf5327fd6d

**Comment by kvasnicaj** [comment]
změnu necháme, excluded semínka musíme vyřešit interně přes black a white listy.
