### ISSUE TITLE
www - přidat web - formulář - spam

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#447]
přes formulář chodí hrozný kvanta spamu, mohl bys prosím přidat nějakou re-captchu nebo něco (předpokládám, že Django  bude v sobě něco mít), abychom omezili odesílání formuláře spamovými boty? Díky

**Comment by Visgean** [comment]
hmm  ok dam tam recaptchu

**Comment by kvasnicaj** [comment]
ještě bych poprosil o úpravu emailu. Informační email pro nás teď má předmět 'Nový návrh', tak to prosím změnit na 'Nový návrh: http://example.com' a druhý email, který chodí uživateli jako potvrzení pro něj, tak již nás nedávat do kopie.

Texty v těle emailu jsme si upravili, ale s tímto si neporadíme. Díky

A dej tomu prosím prioritu, protože toho spamu chodí fakt hodně a my pak snadno přehlídneme emaily, které jsou důležité.

**Comment by Visgean** [comment]
![image](https://user-images.githubusercontent.com/193832/32384537-28f587ca-c0b3-11e7-9183-42e860e09aaa.png)
jak jste si to prelozili tak to mate, v puvodnim prekladu je url v titlu.

**Comment by Visgean** [comment]
nutno doplnit do settings podle: https://www.google.com/recaptcha/intro/index.html

```
RECAPTCHA_PUBLIC_KEY = ''
RECAPTCHA_PRIVATE_KEY = ''
```

**Comment by kvasnicaj** [comment]
v tomto titlu url bylo, ale v tom druhém ne. Do překladu jsem to doplnil takto: 

> Nový návrh %(url)s

Tak snad to bude ok :)

**Comment by kvasnicaj** [comment]
@Visgean kterou recaptchu mám zaregistrovat kvůli těm klíčům? reCaptcha V2 nebo invisible?

**Comment by Visgean** [comment]
V2

**Comment by JanMeritus** [comment]
@Visgean  Treba tam potom nieco aj prepnut (napr.: NOCAPTCHA = True na False
), alebo stacia tam len tie kody?

**Comment by kvasnicaj** [comment]
Teď to nefunguje, resp. captcha se nezobrazí, ale je vyžadována pro odeslání formuláře.

https://www.webarchiv.cz/cs/pridat-web

**Comment by JanMeritus** [comment]
rsp, nebude to nieco s Djangovskou cachi?

**Comment by JanMeritus** [comment]
uz to fungiruje, asi cache z base.py

**Comment by holoubkovamonika** [comment]
Zdenko ted nějak obnovil/spravil "are you a human" takže spamy nebudou přicházet, ale v předmětu e-mailu (s novým zdrojem) nám ted chodí hláška "Nový návrh %(url)s" kdežto předtím chodilo Webarchiv.cz - archivace webovych stranek "konkretni url"...

**Comment by Visgean** [comment]
To je asi preklad

**Comment by kvasnicaj** [comment]
@Visgean ano, je to překlad. Použil jsem `%(url)s` stejně jako je to u toho druhého předmětu, ale tady se to nenahradilo URL... viz obrázek

<img width="708" alt="predmety" src="https://user-images.githubusercontent.com/10117117/33030920-eb870af4-ce1c-11e7-814b-36710afaae4c.png">

@holoubkovamonika předtím chodili oba. "Nový návrh..." je pro nás a "Webarchiv.cz - archivace..." je pro uživatele. Ten už nám chodit nebude. Cílem je "Nový návrh www.example.com"

**Comment by Visgean** [comment]
Nenahradila se protoze v originale se taky nenahrazuje.

**Comment by kvasnicaj** [comment]
Jak to myslíš v originále a co s tím?

**Comment by mariehaskovcova** [comment]
ahoj, zmizela možnost potvrdit "Are you human?", bez čehož nejde přidat web...
![pridat_web](https://user-images.githubusercontent.com/19947819/33265906-c311376e-d373-11e7-9ece-b614b592142e.png)

**Comment by kvasnicaj** [comment]
už to zase funguje....

**Comment by JanMeritus** [comment]
Poprosim o presunutie `RECAPTCHA_PUBLIC_KEY = ''
RECAPTCHA_PRIVATE_KEY = ''`

Do local_settings.py

**Comment by Visgean** [comment]
proc? ty settings ktere vy pouzivate by to meli prepsat, takhle je tam default aby to slo spustit na locale..

**Comment by JanMeritus** [comment]
tj cokolvek z base si zanesiem do localu a bude to prepisane? ak jo tak supa.

**Comment by Visgean** [comment]
Jj

**Comment by JanMeritus** [comment]
ok, done
