### ISSUE TITLE
seeder/admin topic collections err 500

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#448]
při kliknutí na jakoukoliv tematickou kolekci v administraci to hodí 500. 

např. 

https://seeder.webarchiv.cz/seeder/admin/harvests/topiccollection/1/change/

**Comment by Visgean** [comment]
https://sentry.webarchiv.cz/sentry/seeder/ ja to v sentry nevidim :(

**Comment by Visgean** [comment]
Na localu ano

**Comment by kvasnicaj** [comment]
Já tu chybul zkusil vyvolat na testovacím a hodilo to tohle: 

`
Request Method: | GET
-- | --
http://10.3.0.120/seeder/admin/harvests/topiccollection/1/change/
1.10.4
KeyError
"Key 'slug' not found in 'TopicCollectionForm'. Choices are: active, all_open, annotation_cs, annotation_en, auto_created, custom_seeds, custom_sources, date_from, date_to, image, keywords, owner, scheduled_on, seeds_frozen, status, target_frequency, title_cs, title_en."
/opt/virtualenv/seeder/lib/python3.4/site-packages/django/forms/forms.py in __getitem__, line 150
/usr/sbin/uwsgi
3.4.5
['/opt/Seeder/Seeder/',  '.',  '',  '/opt/virtualenv/seeder/lib64/python34.zip',  '/opt/virtualenv/seeder/lib64/python3.4',  '/opt/virtualenv/seeder/lib64/python3.4/plat-linux',  '/opt/virtualenv/seeder/lib64/python3.4/lib-dynload',  '/usr/lib64/python3.4',  '/usr/lib/python3.4',  '/opt/virtualenv/seeder/lib/python3.4/site-packages']
út, 31 Říj 2017 13:06:34 +0000
`

`Environment:


Request Method: GET
Request URL: http://10.3.0.120/seeder/admin/harvests/topiccollection/1/change/

Django Version: 1.10.4
Python Version: 3.4.5
Installed Applications:
('raven.contrib.django.raven_compat',
 'dal',
 'dal_select2',
 'modeltranslation',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.postgres',
 'django_tables2',
 'django_filters',
 'bootstrap3',
 'mptt',
 'formtools',
 'reversion',
 'ckeditor',
 'ckeditor_uploader',
 'django_crontab',
 'sorl.thumbnail',
 'rest_framework',
 'rest_framework.authtoken',
 'core',
 'publishers',
 'source',
 'voting',
 'comments',
 'contracts',
 'legacy_db',
 'harvests',
 'blacklists',
 'qa',
 'www',
 'search_blob')
Installed Middleware:
('raven.contrib.django.middleware.SentryMiddleware',
 'reversion.middleware.RevisionMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.middleware.locale.LocaleMiddleware')



Traceback:

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/forms/forms.py" in __getitem__
  144.             field = self.fields[name]

During handling of the above exception ('slug'), another exception occurred:

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/contrib/admin/options.py" in wrapper
  544.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/contrib/admin/sites.py" in inner
  211.             return view(request, *args, **kwargs)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/contrib/admin/options.py" in change_view
  1512.         return self.changeform_view(request, object_id, form_url, extra_context)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/lib64/python3.4/contextlib.py" in inner
  30.                 return func(*args, **kwds)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/contrib/admin/options.py" in changeform_view
  1474.             model_admin=self)

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/contrib/admin/helpers.py" in __init__
  44.         } for field_name, dependencies in prepopulated_fields.items()]

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/contrib/admin/helpers.py" in <listcomp>
  44.         } for field_name, dependencies in prepopulated_fields.items()]

File "/opt/virtualenv/seeder/lib/python3.4/site-packages/django/forms/forms.py" in __getitem__
  150.                     ', '.join(sorted(f for f in self.fields)),

Exception Type: KeyError at /seeder/admin/harvests/topiccollection/1/change/
Exception Value: "Key 'slug' not found in 'TopicCollectionForm'. Choices are: active, all_open, annotation_cs, annotation_en, auto_created, custom_seeds, custom_sources, date_from, date_to, image, keywords, owner, scheduled_on, seeds_frozen, status, target_frequency, title_cs, title_en."
`

**Comment by Visgean** [comment]
To je zvlastni, ja vubec nemam tyhle url, pro seznam collections mam
http://127.0.0.1:8000/seeder/harvests/collections
pro detail: http://127.0.0.1:8000/seeder/harvests/1/collection_detail a pro edit http://127.0.0.1:8000/seeder/harvests/1/collection_edit

**Comment by kvasnicaj** [comment]
Jo tohle je ale v adminu, tam kde spravuješ třeba uživatelské účty :)

**Comment by Visgean** [comment]
:D aha ok, no tak to je jedno, ne? ja ani nevim proc v tom adminu ty topic collections jsou. oni by tam imho spravne byt nemeli.

**Comment by kvasnicaj** [comment]
no oni tam jsou asi hlavně, protože jedině z adminu jdou smazat, což je fajn, to bych tak nechal :) jinak to asi jedno je, ale i tak bych to chtělo nějak opravit, třeba je udělat neproklikávací :)
