### ISSUE TITLE
Nefunkční odkaz seeder - wa-kat

### ISSUE THREAD

**Issue by holoubkovamonika** [WebarchivCZ/Seeder#450]
Zdravím,
mám takový smělý dotaz. Nefunguje mi odkaz ze seederu do WA-KATu...

(Když si v Seederu otevřu nějaký zdroj a kliknu na odkaz do WA-KATu, tak mi to hodí 404)

https://seeder.webarchiv.cz/seeder/source/detail/kat.webarchiv.cz

Je možné to nějak oživit?

Díky

**Comment by Visgean** [comment]
v settings jsou dve lajny na odkazy, defaultne byli takhle:
```
WAKAT_URL = 'http://forpsi.kitakitsune.org:8080/?url_id={id}'
WAYBACK_URL = "http://wayback.webarchiv.cz/wayback/query?type=urlquery&url={url}"
```

na serveru je mate imho spatne, pravdepodobne chyby ta http cas, @JanMeritus

**Comment by Visgean** [comment]
tzn je potreba aby to melo podobny format. jinak se tam nedoplni idcka.

**Comment by JanMeritus** [comment]
tyhle nastaveni mas  v base.py?

**Comment by Visgean** [comment]
j

**Comment by kvasnicaj** [comment]
při kliknutí na ten odkaz ze Seederu by se měli přenést údaje ne? Teď se nic nepřenese, je ten odkaz takto správně? 

https://kat.webarchiv.cz/?url_id=76

**Comment by Visgean** [comment]
Wakat asi nema dobre nastaveny pristup na domeny seederu nebo se naopak
dotazuje nekam kam nema

**Comment by kvasnicaj** [comment]
komunikace se nám podařila rozjet :) opravdu pouze chyběl jen token ze Seederu v nastavení WA-Katu
