### ISSUE TITLE
zdroj - prolinkování do archivu

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#454]
u hlavního záznamu zdroje v Seederu by položka "Link na web" měla směřovat do našeho archivu. V tuto chvíli u všech zdrojů háže 404ku

**Comment by JanMeritus** [comment]
Toto je rekurentny problem. Myslim ze suvisi s celkovym generovanim liniek v seedru. Súvis s #450 #433 #445 #444 #440 .

**Comment by kvasnicaj** [comment]
ne ne, tady je i špatně vygenerovaná url + 

`/cs/zdroj/8273-wwwabastaborislavcz `

zdroj nyní nefunguje viz #444

a to vyhledavani s id `8273-wwwabastaborislavcz` podle mě nikdy nefungovalo

**Comment by Visgean** [comment]
Funguje jenom pro zdroje se stavem running.

**Comment by kvasnicaj** [comment]
funguje jen z adresy webarchiv.cz/seeder  -> #433
