### ISSUE TITLE
Nechodí e-maily mimo doménu NKP.cz

### ISSUE THREAD

**Issue by holoubkovamonika** [WebarchivCZ/Seeder#455]
Zdravím a prosím o opravu,
když nám navrhovatel/vydavatel pošle přes formulář nějaký zdroj, tak mu dřív chodil takový automatický e-mail, že ho bereme na vědomí a že děkujeme a že se mu budeme věnovat. Teď se po redukci spamu stalo to, že tento e-mail už nechodí - je třeba to napravit.

Díky moc

**Comment by Visgean** [comment]
Ted jsem to zkontroloval a u me chyba neni - email se odeslal v pohode, kdyby nefungovalo tohle tak by nemeli chodit zadne emaily. @JanMeritus mozna se jedna o chybne nastaveni serveru? 

@holoubkovamonika a notifikacni emaily vam dojdou?

**Comment by holoubkovamonika** [comment]
Na webarchivní e-mail přijde jen informace/notifikace, že někdo nám poslal návrh... ale už nepřijde ten e-mail, že mu taky bylo poděkováno...

to nám vlastně dřív na webarchiv chodily e-maily 2 - notifikace o návrhu a potvrzení toho, že vydavateli byl odeslán děkovný e-mail...

**Comment by Visgean** [comment]
Vzdyt to bylo v nejakym issues, ze vas to otravovalo tak jsem vas vyhodil z
prijemcu.

**Comment by kvasnicaj** [comment]
Problém v tom, že po nasazení nové verze Seederu, nechodí emaily mimo knihovnu. Takže je to na @JanMeritus - to samé se děje i při odesílání plánovaných emailů u smluv.

**Comment by Visgean** [comment]
Ok, s tim ja fakt nic nenadelam.

**Comment by JanMeritus** [comment]
Testovalo sa to mimo doménu predtým? A kedy naposledy?

**Comment by holoubkovamonika** [comment]
Pravděpodobně měsíc dva zpátky... minimálně nám ještě pár dní zpátky chodily ty informační e-maily o tom, že ten e-mail vydavatelům chodí...

**Comment by kvasnicaj** [comment]
poslední testy proběhly 25. 9. 2017 a emaily chodily ven...

**Comment by JanMeritus** [comment]
bola tu nekdy ta situace predtim @Visgean ? Napr #257 alebo #293, tj moze to byt nejakymi settingami?

**Comment by kvasnicaj** [comment]
293 určitě ne, 257 možná. Ale nechodí žádný emaily mimo síť, tudíž to bude určitě na naší straně. Dnes jsem to opět testoval s tou recaptcha a na pracovní email mi přišlo a na soukromý ne.

**Comment by Visgean** [comment]
toz jak, furt nic?

**Comment by mariehaskovcova** [comment]
bohužel pořád stejné - na pracovní mail mi odpověď přišla, na soukromý mail ne

**Comment by Visgean** [comment]
S tim ja nic neudelam :/

**Comment by JanMeritus** [comment]
Je to na @westfood ...

**Comment by westfood** [comment]
řeším to s Milošem, smtp serveru se nezdá zdrojová IP při odesílání mailu mimo nkp.cz

**Comment by westfood** [comment]
Vypadá to, že úprava od Pavla Kotrby klapla, chtělo by to ale masovjěji zkontrolovat. Zkuste to otestovat @kvasnicaj na maily na různých doménách.  Mě to zatím do gmailu nedorazilo, ale nkp.cz SMTP server to přijal k doručení, může tam být nějaký prodlava, než to gmail přijme.

```Apr 20 14:45:41 wa-app00 postfix/smtp[2453]: E39FD3139194: to=<westfood@gmail.com>, relay=10.1.2.183[10.1.2.183]:25, delay=0.08, delays=0.04/0.02/0.01/0.01, dsn=2.0.0, status=sent (250 2.0.0 w3KCmhcD007400 Message accepted for delivery)```

**Comment by westfood** [comment]
Holky otestovali a prej to frčí.
