### ISSUE TITLE
Změna vydavatele, přiřazení smlouvy Matematicko-fyzikální zdroj

### ISSUE THREAD

**Issue by Bilinova** [WebarchivCZ/Seeder#458]
Na Hlavní stránce je zdroj Matematicko-fyzikální fakulta zařazena do seznamu Smlouvy bez rozvrhnutého jednání a Smlouvy v jednání, viz. obr.
![image](https://user-images.githubusercontent.com/13220888/33258821-12cd815e-d35b-11e7-988a-fa56196d508e.png)

v sekci Smlouvy nemá Zdroj přiřazenou smlouvu a nestáhl se/nepropojil se vydavatel - Univerzita Karlova (je tam stále uvedený Univerzita Karlova.Matematicko-fyzikální fakulta)  obr,:
![image](https://user-images.githubusercontent.com/13220888/33258839-22eec94e-d35b-11e7-8362-26aac2e279ca.png)

přestože jsem vydavatele změnila na Univerzita Karlova a smlouvu přiřadila 28/20016 viz. obr. 
![image](https://user-images.githubusercontent.com/13220888/33259064-f17ab23c-d35b-11e7-857a-3b9fc91e8205.png)

Problém: nově upravený vydavatel se nepromítne do záznamu zdroje, myslím, že by neměla nastat situace, kdy je uzavřena smlouva a zároveň je u záznamu uvedeno Smlouva v jednání s Univerzita Karlova...

**Comment by kvasnicaj** [comment]
To by mělo být tohle: https://sentry.webarchiv.cz/sentry/seeder/issues/107/

**Comment by Bilinova** [comment]
Po aktualizaci seederu 23/7/ je to v pořádku
