### ISSUE TITLE
Zdroje ke katalogizaci

### ISSUE THREAD

**Issue by Bilinova** [WebarchivCZ/Seeder#459]
v seederu se mi na hlavní stránce objevily zdroje, které je nutno zkatalogizovat.  Při přechodu na seeder jsme všechny zdroje, kreé byly potřeba zkatalogizovaly, nerozumím, proč se mi to tam tobrazuje.

název zdroje | url | výsledek hodnocení WAAdminu | status zdroje
Bohemian Greenways - veřejně | http://www.greenways.cz/verejne/ | ne | schváleno vydavatelem
Centrum historie XVII. století | http://www.centrumhistorie.cz/ | ne | schváleno vydavatelem
Centrum pro výstup z komunistické strany | http://www.svetbezkomunismu.cz/ | ano | schváleno vydavatelem
Cesi Južnog Banata | http://www.cesijuznogbanata.net | ano | schváleno vydavatelem
Člověk hledá člověka | http://www.clovekhledacloveka.cz | ano | schváleno vydavatelem
DJ Orthodox | http://djorthodox.info | ne | schváleno vydavatelem
Egypt-cz.tk | http://egypt-cz.tk | ne | schváleno vydavatelem
Etnologie | ttp://morrigna.wz.cz/etnologie/etnologie.html | ne | schváleno vydavatelem
First Paleolithic Virtual Journal | http://www.iabrno.cz/vjournal.htm | ne | schváleno vydavatelem
Fond rozvoje vysokých škol | http://www.frvs.cz | ano | schváleno vydavatelem
Galaxie | http://galaxie.name | ne | schváleno vydavatelem
Gastro report Minutka | http://www.minutka.cz | ano | schváleno vydavatelem
Gastrorevue | http://www.gastrorevue.cz | ne | schváleno vydavatelem
Historie českých zemí | http://mujweb.cz/Zabava/historie/historie2.html | ne | schváleno vydavatelem
Historie jazzu | http://mujweb.cz/www/mirajs-jazzik/ | ne | schváleno vydavatelem
Historie místeckého náměstí | http://www.mujweb.cz/kultura/mistecke.namesti/ | ne | schváleno vydavatelem
Hlídací fena | http://www.hlidacifena.cz/service.asp | ano | schváleno vydavatelem
Intervalla delucida | http://www.prf.cuni.cz/intervalla | ne | schváleno vydavatelem
Itrend | http://www.itrend.cz | ne | schváleno vydavatelem
Komunistické stránky | http://www.fankscm.estranky.cz | ano | schváleno vydavatelem
Lisabonská smlouva.cz | http://www.lisabonskasmlouva.cz | ano | schváleno vydavatelem
Marienbad : Alte Stiche, Bilder, Postkarten und Fotos bis 1950 | http://www.marienbad-postcards.com/ | ne | odmítnuto wa
Meus Orbis | http://www.vh-obrazy.com | ne | schváleno vydavatelem
Musicpress.cz | http://www.musicpress.cz | ne | schváleno vydavatelem
Národní strana | http://narodni-strana.cz | ano | schváleno vydavatelem
Naturnet-Redime Newsletter | http://www.naturnet.org | ano | schváleno vydavatelem
Radola Gajda | http://narodni-cest.cz | ne | schváleno vydavatelem
Rusko v globální politice | http://www.globalaffairs.cz | ano | schváleno vydavatelem
Specialista : military portál | http://magazin.specialista.info | ano | schváleno vydavatelem
Spolek proti nemravným cenám elektřiny, o. s. | http://www.sponel.cz | ano | schváleno vydavatelem
The New Presence | http://new-presence.cz | ano | schváleno vydavatelem
Virtuální pomník obětem komunismu | http://protikomunisticke.misto.cz | ano | schváleno vydavatelem
Vlastimil Ježek | http://www.vlastimiljezek.cz/ | ne | schváleno vydavatelem
Vulgo.net | http://vulgo.org/revue/ | ne | schváleno vydavatelem
www.skupiny.estranky.cz | http://www.skupiny.estranky.cz | ne | schváleno vydavatelem
9 komentářů k Čínské Komunistické Straně | http://9komentaru.cz | ano | schváleno vydavatelem

**Comment by kvasnicaj** [comment]
tyto zdroje patří mezi ty, které musíme upravit ručně
