### ISSUE TITLE
Seznam URL adres u sklizně - err 500

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#460]
Když chci zobrazit seznam URL adres u naplánované sklizně, tak to hodí Err 500

Dělá to u sklizně, která je tematická. U sklizní, které mají zdroje podle frekvence, to funguje. 

https://sentry.webarchiv.cz/sentry/seeder/issues/108/

**Comment by JanMeritus** [comment]
Stale issue aj u KarlovyUniverzity, blokuje to pouzivani pri skliznich, problem VSECH tematickych sklizni
![waerr2_2018-01-31 16-22-12](https://user-images.githubusercontent.com/25201690/35631150-748018aa-06a3-11e8-94ae-f998ead9ba01.png)
![waerr2018-01-31 16-21-39](https://user-images.githubusercontent.com/25201690/35631152-74b7113e-06a3-11e8-9af4-1d7a4172746f.png)
