### ISSUE TITLE
přehodnocení zdroje - datum

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#461]
Pokud kurátor zvolí pro zdroj stav „Čeká na přehodnocení“, mělo by být možné někde nastavit datum, ke kterému má být zdroj přehodnocen. Zdroj by se pak měl objevit v poli Otevřená hodnocení.

**Comment by Visgean** [comment]
Tohle je v nastaveni.

**Comment by kvasnicaj** [comment]
když změníme stav na Čeká na přehodnocení, tak to nikde nenabídne k vyplnění datum, kdy by se to mělo přehodnotit.

**Comment by mariehaskovcova** [comment]
teď jsme s Mončou zjistily, že to jde nastavit u hodnocení v Manažerských možnostech, automaticky se následně změní i stav u hlavního záznamu...  Takže asi ok. Zaujalo nás, že tam lze nastavit i mínusová hodnota - cestování časem :)
