### ISSUE TITLE
Harvest Section: Generovane semienka maju zdanlivo randomny format

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#465]
Niektore semienka maju v zdruzenom zozname su s protocolom, ine bez neho, bolo by to treba zjednotit (vid prilozeny list). U  jednoduchecho listu z jedneho zdroja je uprava v zasade pevna.

[seeds-2017-12-V2M.txt](https://github.com/WebarchivCZ/Seeder/files/1568025/seeds-2017-12-V2M.txt)

[seeds-2017-12-V1M_CUNI_Onesh.txt](https://github.com/WebarchivCZ/Seeder/files/1568024/seeds-2017-12-V1M_CUNI_Onesh.txt)

**Comment by kvasnicaj** [comment]
Tohle je na delší debatu, seeder generuje semínka podle toho, jak je vkládají kurátoři. Zvykem bylo, že se ke zdroji dávalo s http://, u tematických sklizní je to různé. Cuni kolekce je bez protokolu, protože je generovaná zpětně ze semínek pro crawler. Tím vznikají nekonzistence, budeme to muset nejprve vyřešit koncepčně a pak případně navrhnout úpravy pro Seeder.

**Comment by JanMeritus** [comment]
Jop, toz inventura semienok a ich protokolov :D
