### ISSUE TITLE
Tematické sklizně

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#466]
- [x] automatické rozpoznání interních semínek (po vložení seznamu semínek je porovnat z naší databází a vybrat ty, které máme v databázi a jsou ve stavu running)
- [x]  přidat možnost publikovat/nepublikovat (pro zobrazení na www)
- [x]  přidat možnost zadat frekvenci sklízení (stejné jako u klasických zdrojů)
- [x]  možnost změnit pořadí zobrazení sklizní na www

**Comment by Visgean** [comment]
rozpoznani internich seminek na zaklade jakych pravidel?

**Comment by Visgean** [comment]
přidat možnost publikovat/nepublikovat (pro zobrazení na www) - tohle by uz tam imho melo byt ale zkontroluji to.

**Comment by kvasnicaj** [comment]
rozpoznání semínek, nijak to nekomplikovat -> kurátoři nahrávají semínka ve formátu jedno url na řádek. Pak je třeba to projet, jestli se URL nachází v databázi a je pod stavem running. Pokud ano, tak to url "přesunout" z Mimosystémová semínka do Přiřazené zdroje. 

(Nebudeme řešit části domén, nebo konkrétní stránky na doméně. Prostě to URL musí být jedna k jedný. )

**Comment by kvasnicaj** [comment]
možnost publikovat je teď pouze u aktualit u tematických sklizní není
