### ISSUE TITLE
Správa zdrojů

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#469]
- [x] možnost smazání (případně jen zneviditelnění) zdroje - buď v administraci nebo pouze pro uži-
vatele s vyššími právy
- [x] rozšíření filtru u výpisu zdrojů o: vypsat zdroje s cc, vypsat zkatalogizované zdroje (zdroj má
vyplněné aleph id), vypsat periodika (zdroj má issn)
- [x] možnost exportovat vyfiltrovanou tabulku např. do csv, xls atd.

**Comment by Visgean** [comment]
@kvasnicaj pridal jsem moznost deactiovat zdroje pro uzivatele.

**Comment by mariehaskovcova** [comment]
deaktivovat zdroj jeho kurátor nemůže (zřejmě jen uživatel s vyššími právy? @kvasnicaj )

**Comment by kvasnicaj** [comment]
kurátor s vyššími právy může 👍

**Comment by kvasnicaj** [comment]
ad. filtry: přidat možnost vyhledat smlouvu/zdroj podle čísla smlouvy.

**Comment by Fasand** [comment]
To vypsani zdroju s CC by melo byt podle kontraktů? Samotny zdroj totiz zadnou vlastnost CC nema.
Takze pokud nejaky (klidne jenom jeden) kontrakt u zdroje je validni a ma zaskrtnute CC, tak by ho to melo najit pres to filtrovani, chapu to dobre?

**Comment by Fasand** [comment]
> ad. filtry: přidat možnost vyhledat smlouvu/zdroj podle čísla smlouvy.

@kvasnicaj To cislo smlouvy chces opravdu jenom Contract.contract_number (e.g. "64") nebo to, co se zobrazuje v Seederu i s rokem (e.g. "64 / 2017")?

**Comment by kvasnicaj** [comment]
jo jo, jestli je cc zdroje jsou označené pouze u smlouvy, týká se to i issue #505 

číslo smlouvy je i rokem tj. 10 / 2019, protože se to na začátku roku zase vynuluje a začíná se od 1.

**Comment by Fasand** [comment]
Vyřešeno v: a05a773e0b53a63f5ce891d0c704fdc3940edc93
