### ISSUE TITLE
Zobrazit počet zdrojů u všech tabulek v dashboardu

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#470]

**Comment by Visgean** [comment]
Pocet zdroju znamena co presne v tomhle kontextu? Jakoze treba v tabulce publisher by mel byt pocet zdroju s timhle vydavatelem?

**Comment by kvasnicaj** [comment]
Ne ne, jen prostě u těch tabulek s rozpracovanými zdroji, zobrazit počet zdrojů. 

![dashboard](https://user-images.githubusercontent.com/10117117/34406070-42b119ac-ebb7-11e7-98ed-ff2bbaaedf5e.png)
