### ISSUE TITLE
Tvorba názvu souboru se semínky

### ISSUE THREAD

**Issue by Visgean** [WebarchivCZ/Seeder#472]
vzor:

seeds-YYYY-MM-title.txt

## Pravidelné výběrové sklizně:
titles: V1M, V2M, V6M, V12M
příklad:
seeds-2017-11-V1M.txt

## Jednorázová sklizeň:
title: V-1
příklad:
seeds-2017-01-V-1.txt

## ArchiveIt sklizeň:
title: ArchiveIt
příklad:
seeds-2017-04-ArchiveIt.txt

## Tematické sklizně
title: prefix TM + název zadaný kurátorem
příklad:
seeds-2017-11-TM-VolbyPS2017.txt
seeds-2017-11-TM-cuni.txt

**Comment by Visgean** [comment]
Ok, tohle asi proberem po skypu.

**Comment by kvasnicaj** [comment]
ok, po Novým roce se spojíme

**Comment by JanMeritus** [comment]
pastnuto z 468, pre zrovnanie: 

(serials)
seeds-2018-01-08-V1M.txt
seeds-2018-01-08-VxM.txt (1,2,6,12)
seeds-2018-01-08-VNC.txt (NoContract)
seeds-2018-01-08-CUNI.cz
seeds-2018-01-08-OneShot.txt
seeds-2018-01-08-ArchiveIt.txt
(tests, topics, totals)
seeds-2018-01-08-T.txt (tests)
seeds-2018-01-08-TT.txt (topics)
(nepouzivat ale pridavam pre zaujimavost)
seeds-2018-01-08-CZNic.txt (totals)
Pod tymito dotazmi sa bude z danej url dat stiahnut semienka:

https://seeder.webarchiv.cz/seeder/harvests/typeOfHarvest/Y-m-d/seeds-Y-m-d-shortcutOfType.txt https://seeder.webarchiv.cz/seeder/harvests/serials/2018-01-08/seeds-2018-01-08-V1M.txt

**Comment by Fasand** [comment]
@kvasnicaj Tohle uz bylo vyreseno v #468, ne? Jenom se ty soubory nevytvareji ale URL dynamicky generuji.

**Comment by kvasnicaj** [comment]
jj vyřešeno v #468
