### ISSUE TITLE
Archivován bez smlouvy

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#475]
semínka zdrojů se statusem Archivován bez smlouvy/Archiving without publisher consent jsou na whitelistu, což se nesmí dít. Tyto semínka mají být je zařazeny do sklizní, ale nesmí být veřejně dostupné.

**Comment by Visgean** [comment]
O jakem whitelistu mluvis?

**Comment by kvasnicaj** [comment]
https://webarchiv.cz/seeder/source/dump
