### ISSUE TITLE
Nová vs přiřazená smlouva

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#477]
Pokud kurátor uzavře kladně hodnocení, vygeneruje se nová smlouva, to je ok. 
Pokud ale kurátor přiřadí tento zdroj k již existující smlouvě, tak ta nová rozpracovaná smlouva tam zůstane viset a nejde s ní nic dělat. 
Asi by to chtělo, aby se po přiřazení ke stávající smlouvě, ta nová smlouva smazala.

**Comment by kvasnicaj** [comment]
Podobná situace nastane i v případě, že smlouva je rozjednaná, ale jednání nakonec neklapne a my zařadíme zdroj k archivaci bez smlouvy, tak  rozjednaná smlouva zůstane v systému viset. 

Nejjednodušší řešení asi bude umožnit smazat smlouvu (pouze pokud nemá již přiřazení číslo)

**Comment by Visgean** [comment]
Ok sorry, trvalo to fakt dlouho, ale ted uz muzete mazat :)

**Comment by mariehaskovcova** [comment]
testujeme - mazání funguje :) (není omezené na kurátora, který zdroj spravuje)
