### ISSUE TITLE
Zdroje ke katalogizaci na Hlavní stránce 

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#478]
ve chvíli, kdy kurátor vytvoří smlouvu, měl by se zdroj objevit na Hlavní stránce (dashboard) v poli Zdroje ke katalogizaci, což tak v tuto chvíli není  (viz např. zdroj Duše domu, stav Archivován, smlouva č. 1/2018)

**Comment by Visgean** [comment]
Ne, nemel. tam jsou zdroje bez alephu.

**Comment by mariehaskovcova** [comment]
právě že se nezkatalogizované zdroje (bez Alephu) na hlavní straně se neobjeví

**Comment by Visgean** [comment]
hmm ok, mozna je tam chyba ve filtru, kouknu na to https://github.com/WebarchivCZ/Seeder/blob/master/Seeder/core/dashboard_data.py#L179

**Comment by kvasnicaj** [comment]
pro upřesnění: měly by se tam objevit zdroje, které mají status Archivován a nemají vyplněný Aleph no. a samozřejmě patří přihlášenému kurátorovi. (smlouva tu hraje sekundární roli)

**Comment by mariehaskovcova** [comment]
v poli Zdroje ke katalogizaci se mi objevují i zdroje, které mají status Archivován bez smlouvy. Měly by tu být jen zdroje se stavem Archivován a bez vyplněného Aleph id.

**Comment by Fasand** [comment]
Vyřešeno v: a05a773e0b53a63f5ce891d0c704fdc3940edc93
