### ISSUE TITLE
automatické odesílání dopisů

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#480]
když chci naplánovat automatické odesílání dopisů vydavatelům (u Smluv pole "Rozvrhnutí"), hodí to Server Error (500)

https://sentry.webarchiv.cz/sentry/seeder/issues/15/

**Comment by Visgean** [comment]
Je spatne vyplneny email

**Comment by mariehaskovcova** [comment]
omlouvám se, moje chyba... zkusím znovu a zavřu issue, dík

**Comment by Visgean** [comment]
Ono je to furt blbe tim, ze by to melo hodit nejakou hlasku nebo vykrcnik...

**Comment by mariehaskovcova** [comment]
to je fakt... kurátor by věděl, že musí zkontrolovat kontakt
