### ISSUE TITLE
Personalizace dashboardu hodnocení

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#484]
bylo by možné v dashboardu v tabulce otevřená hodnocení označit zdroje, ve kterých jsem již hlasoval? Třeba zelených podbarvením, takto musí kurátoři proklikávat zdroje pořád dokola, protože neví, kde už hlasovali.

**Comment by Fasand** [comment]
Prosím o znovuvysvetleni issue a pripadnou upravu, pokud to nahodou uz za tu dobu bylo vyreseno.

Pokud se opravdu jedná o kartu "Otevřená hodnocení" / "Open voting rounds", tak jakmile v jednom s vybranych hodnocenich hlasuji, hodnoceni mi zmizi z dashboardu.
V kódu je to znaceno pomoci `~Q(vote__author=self.user)` (https://github.com/WebarchivCZ/Seeder/blob/986532f3fb85ac6ca144456a76989fd90b47825b/Seeder/core/dashboard_data.py#L134), tedy se nezobrazi hodnoceni, ve kterych je prihlaseny uzivatel autorem jednoho z hlasování. Ten radek je tam ale uz 5 let, takze si nejsem jisty, jestli issue nebylo zamysleno jinak.

**Comment by mariehaskovcova** [comment]
taky se mi toto zdá ok, ještě to prověříme - proberu v pondělí s kurátory a buď doplníme nebo uzavřeme

**Comment by mariehaskovcova** [comment]
probírali jsme to s kurátory a doupřesnili si to - u pole "Hodnocení, která spravujete" - chtěli bychom barevně odlišit to, že kurátor svůj zdroj již ohodnotil, ale ještě neuzavřel celé hodnocení prostřednictvím manažerským možností (např. ohodnotil zdroj jako první a čeká ještě na ostatní)

**Comment by Fasand** [comment]
Pokud kurator v kole hodnotil, bude karticka podbarvena zelenou. Pokud jeste nevolil, bude vypadat stejne jako ted.
PR #539

**Comment by mariehaskovcova** [comment]
koukli jsme na test, zatím se nepodbarvuje
např: https://app.webarchiv.cz/seeder/voting/7872/detail
<img width="977" alt="Snímek obrazovky 2020-11-03 v 9 13 50" src="https://user-images.githubusercontent.com/19947819/97962212-f6640180-1db4-11eb-9a52-6763a4407265.png">

**Comment by Fasand** [comment]
Jj sorry, tech poslednich par uzavrenych issues jsem jeste nemergnul do masteru, takze je to zatim porad jenom v #539
Mrknu jeste na dve issues a potom to vsechno spolu mergnu.

**Comment by mariehaskovcova** [comment]
jasný, ok, v pohodě :)
