### ISSUE TITLE
Zdroj archivován bez smlouvy

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#485]
Status zdroje **archivován bez smlouvy** ještě úplně nefunguje, jak má. 

- Pokud je zdroj archivován bez smlouvy, tak se nekatalogizuje v Alephu, takže by se neměl objevit v tabulce Zdroje ke katalogizaci

- Tyto zdroje se "katalogizují" pouze na úroveň Seederu, takže se doplní anotace, klíčová slova a další údaje. Problém je, že nefunguje komunikace mezi WA KATem a Seederem. Ideálně by měla katalogizace proběhnout ve WA KATu a to se uložit do Seederu (včetně vytvoření nových klíčových slov) viz #364 #380 #450 

- Tyto zdroje by také neměly být zobrazeny v katalogu na webu

**Comment by kvasnicaj** [comment]
+ by se neměly zobrazovat na homepage ve výpisu posledních uzavřených smluv. Viz obrázek
<img width="1440" alt="snimek obrazovky 2019-03-08 v 10 47 31" src="https://user-images.githubusercontent.com/10117117/54021234-f353e080-418f-11e9-8944-f44cd614fc70.png">

**Comment by kvasnicaj** [comment]
už se nezobrazují na webu

**Comment by Fasand** [comment]
Vyřešeno v: a05a773e0b53a63f5ce891d0c704fdc3940edc93
