### ISSUE TITLE
Whitelist se nevygeneruje

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#492]
háže to jen prázdnou stránku
https://seeder.webarchiv.cz/seeder/source/dump

**Comment by kvasnicaj** [comment]
ani semínka pro sklizeň to nevygeneruje 
např. https://seeder.webarchiv.cz/seeder/harvests/35/urls

**Comment by Visgean** [comment]
ok fixed.

**Comment by JanMeritus** [comment]
fixed, diki
