### ISSUE TITLE
deaktivování zdroje

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#498]
nová funkce deaktivování zdroje (viz issue #469) nefunguje správně - deaktivace není úplná. Zdroj sice už nelze nalézt před Hledání, ale pořád se objevuje v poli Hodnocení, která spravujete. Po rozkliknutí se pak objeví chyba 404

konkrétně zdroj "Sokol : Česká obec sokolská"  
https://webarchiv.cz/seeder/source/detail/10576
https://webarchiv.cz/seeder/voting/7623/detail 

![404ka](https://user-images.githubusercontent.com/19947819/47497156-57b57980-d859-11e8-91f7-3a9a5016ed04.png)

**Comment by Fasand** [comment]
Vyřešeno v: a05a773e0b53a63f5ce891d0c704fdc3940edc93
