### ISSUE TITLE
Seeder nezobrazuje screenshot v .png

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#503]
Na kartě zdroje se zobrazují screenshoty pouze ve formátu .jpg. Pokud je screenshot v .png, tak se korektně zobrazí na webu pro uživatele, ale v Seederu ne. 

<img width="874" alt="Snímek obrazovky 2019-05-09 v 13 08 33" src="https://user-images.githubusercontent.com/10117117/57449320-dbfea580-725b-11e9-82ff-be162950a179.png">

Při upravování zdroje to ten screenshot vidí:
<img width="874" alt="Snímek obrazovky 2019-05-09 v 13 08 43" src="https://user-images.githubusercontent.com/10117117/57449333-e1f48680-725b-11e9-9d64-7a592d3bba8e.png">

u JPG je to v pohodě: 

<img width="874" alt="Snímek obrazovky 2019-05-09 v 13 09 01" src="https://user-images.githubusercontent.com/10117117/57449344-ea4cc180-725b-11e9-91a5-d0f994aede42.png">

**Comment by Fasand** [comment]
@kvasnicaj dělá to pořád problémy? Zkusil jsem to na své lokální verzi a png screenshot se mi v pohode nacetl jak v Seederu tak na webu.

![image](https://user-images.githubusercontent.com/1846915/60395383-d1ada900-9b32-11e9-9705-9cce6cfc61c0.png)
![image](https://user-images.githubusercontent.com/1846915/60395393-10436380-9b33-11e9-9485-21bb75023b3a.png)
![image](https://user-images.githubusercontent.com/1846915/60395397-19343500-9b33-11e9-8ee5-a8a5e0364873.png)

Ani me moc nenapada, v cem by mohl byt problem - jedine treba stara verze Djanga nebo toho thumbnailoveho pluginu. Zkuste to mozna na te testovaci verzi, jestli tam uz mate aktualni `master`

**Comment by Visgean** [comment]
Ja myslim, ze to bude spatne importovanou db...

**Comment by kvasnicaj** [comment]
jj dělá to pořád, viz ta Chrudim v prvním příspěvku. Na webu se to zobrazuje korektně https://www.webarchiv.cz/cs/hledat/Chrudim%20:%20oficiáln%C3%AD%20stránky%20města

a i když kliknu na ten odkaz v editaci (Screenshot
Aktuálně: screenshots/small_8372_2015-06-05.png) , tak se ten screenshot normálně zobrazí

**Comment by mariehaskovcova** [comment]
v aktuální testovací verzi to vypadá ok, super, uzavírám
