### ISSUE TITLE
Creative Commons 

### ISSUE THREAD

**Issue by kvasnicaj** [WebarchivCZ/Seeder#505]
Na základě právní analýzy musíme trochu upravit systém práce s licencí Creative Commons. Jedná se zejména o to, aby typ licence byl zobrazen v katalogu na webu, ale pojí se s tím taky změna ukládání licence.
1) Pokud je zdroj vystaven pod licencí Creative Commons, tak by u v katalogu měla být licence zobrazena. Viz screenshot 
![Snímek obrazovky 2019-05-27 v 14 49 47](https://user-images.githubusercontent.com/10117117/58421031-363a9b80-808f-11e9-83fb-3e3a5df7c6c3.png)

2) Aby licence byla platná, pak musí být zobrazena v konkrétním formátu a prolinkem na její ustanovení. V současné verzi se licence vkládá jako string, takže si myslím, že ideální by byl seznam, ze kterého se vybírá. Připravil jsem tabulku možných licencí i s jejich odkazy. 

[cc-creativecommons-list-31-5-19.xlsx](https://github.com/WebarchivCZ/Seeder/files/3241092/cc-creativecommons-list-31-5-19.xlsx)

3) A v neposlední řadě by bylo fajn, aby konkrétní licence byla vidět přímo u smlouvy, teď je jen vidět, pokud se klikne na upravit smlouvu.

**Comment by Fasand** [comment]
V tom seznamu pro vybrani typu u editace/vytvareni smlouvy chces mit jako text 
- zkratku licence (e.g. **CC BY-NC-ND 4.0**) 
- nebo ten text ze sloupce Seeder (e.g. **Attribution-NonCommercial-NoDerivatives   4.0 International (CC BY-NC-ND 4.0)**)?

**Comment by Fasand** [comment]
Měla by se licence zobrazit i ve vizuální verzi procházení nebo jenom v textové?

**Comment by kvasnicaj** [comment]
ta licence jen v textové. Na ten seznam se zeptám holek, co by se jim víc líbilo

**Comment by kvasnicaj** [comment]
tak ten celý text i se zkratkou bude lepší
