### ISSUE TITLE
sklizně - nové pole pro nesklizená semínka

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#520]
prosíme o nové pole, kam by se po skončení sklizně uvedlo, která semínka se nesklidila (např: https://webarchiv.cz/seeder/harvests/119/detail)

**Comment by Fasand** [comment]
Predpokladam tedy neco na zpusob noveho TextFieldu, treba `seeds_failed` (nebo pokud jediny duvoud nebude selhani, treba proste `seeds_not_harvested`?).

Melo by se toto pole zobrazit pri editovani sklizne, treba uplne na konci, podobne jako treba "Custom seeds URL"? To by taky znamenalo, ze je pole teoreticky uzivatelsky editovatelne, ale treba to nevadi.
Nebo je to zamysleno spis pro API pristup? (ktery teda pro sklizne zatim neni nijak implementovany)

**Comment by mariehaskovcova** [comment]
seeds_not_harvested by bylo ok, toto pole chtěl Jirka, cílem bylo, aby po ukončení sklizně bylo evidováno, která semínka se nesklidila, mělo to být myslím editovatelné, operátor sklizně by tam po skončení sklizně vložil seznam nesklizených semínek, myslím, jako API přístup to zamýšleno nebylo

**Comment by Fasand** [comment]
Ok, takhle jsem to ted pridal do PR #539, takze zatim zaviram. Kdyby bylo potreba to trochu rozsirit, tak bychom zase otevreli.
