### ISSUE TITLE
časové údaje

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#521]
časové údaje jsou uvedené ve tvaru např. “1 rok, 2 měsíce v minulosti”, uvítali bychom spíše přesné datum (např. záznam zdroje, položka vytvořeno: https://webarchiv.cz/seeder/source/detail/7915)

**Comment by Fasand** [comment]
Vyřešeno v další PR. Bude se zobrazovat přesné datum a po najetí kurzorem se zobrazí datum i čas.
