### ISSUE TITLE
Zdroje ke kontrole

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#522]
kontrola kvality (Zdroje ke kontrole) - potřebovali bychom, aby se kurátorovi ukazovali náhodně zdroje různých kurátorů, ideálně spíš starší, např. zdroje uzavřené před třemi lety a dříve. Každý den by kurátor dostal nabídku cca 3-5 zdrojů ke kontrole (aktuálně se ukazují kurátorovi všechny jeho zdroje)

**Comment by Fasand** [comment]
Ted se tedy kuratorovi zobrazuji vsechny jeho zdroje, ktere byly bud vytvoreny pred QA limitem (defaultne nastaveno na 24 mesicu) a jeste neprobeho QA nebo kterym posledni QA probehlo pred QA limited.
Respektive takto si to interpretuji, ze by to melo byt, realne pokud zdroj proste jeste nema QA (a je archivovan), tak by se mel vzdy zobrazit, coz je asi na zvazeni, jestli tam opravdu chcete i uplne cerstve zdroje nebo jenom ty starsi.

Ty nahodne zdroje na QA byste chteli **pridat** do karticky, **vymenit** za stavajici nebo pro ne **vytvorit novou karticku**?

Ten algoritmus na vybrani nahodnych zdroju mam zatim vymysleny takhle, kdyztak prosim o pripominky pokud se neco nezda:
1. Vyfiltruji pouze zdroje, ktere potrebuji QA a *nepatri uzivateli*
2. Nastavim random seed na "uzivatelske jmeno" + "datum", tedy kazdy uzivatel dostane trochu jine zdroje ale zaroven ty zdroje se budou menit pouze jednou denne.
3. Z cizich zdroju se pokusim vybrat 10 ruznych nahodnych zdroju. Pokud tam uz treba tolik ani neni, tak to prestanu zkouset po 20 pokusech (a treba se zobrazi jenom 1 zdroj nebo zadny)
4. Tech 10 nahodnych zdroju seradim od nejstarsiho a vyberu prvnich 5 a ty zobrazim

To teda znamena, ze i kdyz ten nahodny seznam zustane stejny po obnoveni, zmeni se bohuzel jakmile se jakykoliv zdroj co potrebuje kontrolu zkontroluje. Vzdy tedy kurator vlastne uvidi 5 nahodnych starych zdroju, ktere muze zkontrolovat a jakmile jeden zkontroluje, zobrazi se novych 5.

Pokud by to takhle bylo v pohode, tak super. Kdyby se melo kazdy den opravdu vybrat 5 nahodnych a potom postupne ubyvat, tak to bude trochu slozitejsi, protoze zkratka ta kolekce zdroju, ze kterych si nahodne vybiram, se meni – a to jak samotnym uzivatelem, tak dalsimi uzivateli.

**Comment by mariehaskovcova** [comment]
úplně čerstvé zdroje nechceme (teď mám na testu v QA dnešní zdroj https://app.webarchiv.cz/seeder/source/detail/10777), měl by to být náhodný výběr ze starších zdrojů všech kurátorů, těch 24 měsíců je myslím ok limit

nová karta/pole není potřeba, chtěli bychom, aby to takto fungovalo v již existujícím poli: "Zdroje ke kontrole" na Hl. stránce, takže vyměnit za stávající

1. - můžou patřit kterémukoli kurátorovi (klíčové je pro nás pouze to, aby byly starší a aby se nám zobrazovali zdroje všech kurátorů včetně těch, kteří už tu nepracují)
2. - ok
3. - ok
4. - ok

to, že tam má kurátor vlastně pořád pět zdrojů myslím nevadí, ubývání zdrojů by bylo asi motivující, ale není to vůbec nutný, takže to klidně nech takto

**Comment by Fasand** [comment]
Jj, tak mi to dava vetsi smysl tam mit jenom ty stare zdroje. Byl to uz asi docela stary bug, ze jedna z podminek pro zahrnuti do QA bylo, ze posledni QA check *nebyl* zmenen v poslednich dvou letech, coz ale znamenalo ze to zahrnulo i vsechny zdroje, ktere nemely **zadnou** kontrolu, tedy i vsechny nove. Otocil jsem tu podminku, takze ted by to melo ukazovat pouze zdroje opravdu starsi nez 2 roky.

Zdroje ke kontrole budou tedy zobrazovat pouze tech 5 nahodnych zdroju od jakychkoliv kuratoru.
Budou serazene od nejstarsiho nahore po nejnovejsi dole, at si kuratori pripadne muzou alespon castecne vybrat, ktery zdroj zkontroluji.

Co se tyce te motivace, taky by se mi libilo ubyvajici pocet zdroju, jenom mi to prijde trochu divne, kdyz by zdroje ubyvaly ale zaroven se menily. Takto zaroven kurator muze za jeden den zkontrolovat kolik zdroju chce, ne jen tech 5.
Prozatim jsem alespon vymenil cisilko v headeru karty na pocet kontrol provedenych uzivatelem v dany den, takze tam bude alespon nejaky maly ukazatel a motivace. (na screenshotu ta "3")
![image](https://user-images.githubusercontent.com/1846915/97997833-ab181600-1de9-11eb-9272-ad6564944c11.png)

**Comment by mariehaskovcova** [comment]
super, takhle je to myslím ideální :)
