### ISSUE TITLE
řazení semínek v katalogu

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#523]
pokud má zdroj více semínek - chtěli bychom, aby kurátor mohl vybrat to, které chce, aby se zobrazovalo v katalogu. V tuto chvíli je to první vložené semínko, které ale nemusí už být aktuální (některé zdroje jich mají hodně)

**Comment by Fasand** [comment]
Bude v novem PR. Zatim necham otevrene, kdyby nekdo mel pripominky treba ke vzhledu/zvyrazneni hlavniho seminka, viz screenshoty.

---

![image](https://user-images.githubusercontent.com/1846915/89283466-82974900-d64d-11ea-95f0-a819a03c7bfd.png)
Zelene je aktivni seed s nastavenymi "from" a "to" časy (to uz takhle bylo) a bílé tučné je hlavni seed.

![image](https://user-images.githubusercontent.com/1846915/89283497-8dea7480-d64d-11ea-8e3c-f41d223590bf.png)
Kdyz date edit, uplne nahore bude "Main seed". Po zaskrtnuti a ulozeni se ten predchozi hlavni seed "resetuje" na nehlavni a u toho noveho se to ulozi.

![image](https://user-images.githubusercontent.com/1846915/89283706-e1f55900-d64d-11ea-9748-c85a2584e8f7.png)
Na strankach uz to potom funguje stejne jako doted, jenom se prioritne bere seed s `main_seed=True`. (obrazek se mi nezobrazuje protoze to je z lokálu)
