### ISSUE TITLE
razeni katalogu stranek

### ISSUE THREAD

**Issue by zlodejpapiru** [WebarchivCZ/Seeder#525]
Přiblížím jak nad tím uvažuju: katalog nabízí pouze dva možné parametry filtrování - oborové a abecední. Proto bych rád oba zohlednil. Ale nekombinoval bych je. Abeceda by se zobrazovala pouze pokud bys v katologu měl zakliklé "vše", jakmile bys zvolil nějaký obor narazil bys na klasické stránkování..
.......
V /browse by se porad zobrazoval vyber podle predmetu/oboru a kdyz uzivatel vybere jeden z oboru, tak se mu zobrazi obycejne strankovani pod nim, 12-X zdroju na jedne strance, pripadne (jak to je ted) vyber pod-kategorie

Pokud ale vybere "Vše", tak se pod vyberem oboru zobrazi abeceda, ktera to bude filtrovat proste jenom zdroje, ktere zacinaji na vybrane pismenko.
Kdyz bude chtit ciselne a dalsi znaky (je jich tam nekolik), tak tam bude nalevo od "A" treba jeste "0-9" nebo "Ostatní"

V obou pripadech bude ale zachovano to strankovani, z cehoz jsem byl prvni trochu zmateny. Kdyz totiz vybere uzivatel vsechny zdroje od "A", tak se jich tam zobrazi treba 1000 a nejake strankovani je porad potreba
Jestli k tomu ostatni maji jeste nejake komentare, neotevreme issue? Staci zatim klidne jenom s nejakym takovymto shrnutim a jakekoliv dalsi poznamky.
..........
Přesně tak, s tím, že "vše" je defaultně nastavena výchozí pozice a tak by to mělo i zůstat.. pro weby začínající číslem by bylo vhodné dát #, taktéž diakritiku bych v abecedě asi neřešil..

**Comment by zlodejpapiru** [comment]
![Bez názvu](https://user-images.githubusercontent.com/62152053/83632405-7df7db00-a59f-11ea-9007-6698b0ca09ec.png)

Tady jsem udělal nákres. Velikosti písma zůstanou stejné jaké tam již jsou - myslím, že je to 12. Plus dole v řádkování bych přidal, aby se při počtu stránek více než 10 zobrazovalo také číslo poslední stránky.

**Comment by zlodejpapiru** [comment]
Stejná situace je také pri razeni v tematických kolekcích https://www.webarchiv.cz/cs/tematicke-kolekce/covid-19 Mohl bych pozadat o stejnou upravu? Tzn. dodat na konec  "poslední stránku" jako v případě předchozího screenshotu.

**Comment by Fasand** [comment]
Zmeny budou v PR #539 

## Stránkování
Strankovani upraveno na 1 ... `page range` ... `last page`.
![image](https://user-images.githubusercontent.com/1846915/98004211-efa6b000-1def-11eb-9bb0-bb954d31a761.png)
Pokud je `1` nebo `last page` obsahnuto v `page range`, tak se zobrazi spravne jen jednou, napr.:
![image](https://user-images.githubusercontent.com/1846915/98004379-28df2000-1df0-11eb-8bd9-01c9b5ad903a.png)
Toto strankovani je stejne upraveno i v tematickych kolekcich (detail i seznam) a v obou zobrazenich, pouziva se zde stejny template.

## Abecední třízení
Pokud neni vybrana zadna kategorie, tak se pod seznamem kategorii zobrazi "Vše / # / `abeceda...`", ktera umozni omezit katalog pouze na zdroje jimž nazev zacina na dane pismeno **plus diakritika** (tedy e.g. "E" najde i "É" a "Ě").

Specialni znak "#" zobrazi vše, co nezacina na pismeno (jelikoz jsem nenasel nejakou dobrou Python utilitku na diakritiku, tak jsou nastavene pouze ceske konverze pismeno->diakritika a "#" ma treba konkretne `[^A-ZÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ]`, aby obsahl i diakritiku).

Prepnutim na jine pismeno se strankovani vrati na zacatek.
![image](https://user-images.githubusercontent.com/1846915/98010852-7f039180-1df7-11eb-900f-9ffb24935082.png)

Nevypada to tak jako na navrhu @zlodejpapiru a to ne protoze by se mi nelibil, ale protoze mi to jak to je podle nej nesedelo do struktury templatu. Pokud vam to prijde zbytecne velke (trochu je, ale kategorie furt zabiraji daleko vice mista) nebo by chtelo zmenit ten popisek nebo neco, rad se o to pokusim.

**Comment by zlodejpapiru** [comment]
Petře, super, díky!
