### ISSUE TITLE
úprava stránky o Webarchivu - vývoj

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#526]
na stránku https://webarchiv.cz/cs/o-webarchivu, za FAQ bychom chtěli přidat položku vývoj, prolinkovanou sem: https://webarchiv.cz/vyvoj/

**Comment by Fasand** [comment]
![image](https://user-images.githubusercontent.com/1846915/83724830-388bea00-a641-11ea-98d4-06ed1d8f6c83.png)
Nejak uplne takhle jednoducheho nebo mas na mysli neco jineho? Pripadne v tom "Vývoj" headingu dat jenom ten link a pod to uz zadny odstavec?

**Comment by mariehaskovcova** [comment]
takhle je to super, díky
