### ISSUE TITLE
Update sekce webu "Grafické materiály"

### ISSUE THREAD

**Issue by zlodejpapiru** [WebarchivCZ/Seeder#527]
Vlozeni clipboard boxu s kodem.

`<font face="Times" size="5"; style="color: blue"> <a href="http://www.webarchiv.cz/cs/certifikovano">Webarchiv</a>ováno <br>Národní knihovnou <br>ČR </font> `

popisek: certifikát v html

umisteni: pod "certifikát" nad "naše logo v křivkách"

velikost: sirka max 500px, vysku zvol sam dle textu

**Comment by Fasand** [comment]
Mel by se ten text a link nejak menit pro anglictinu? Napr. "Webarchived by NKČR" nebo neco. Anglicky link pro certifikovano je http://www.webarchiv.cz/en/disclaimer ale obsahuje stejne informace (v CZ i EN)

**Comment by Fasand** [comment]
![image](https://user-images.githubusercontent.com/1846915/83745581-09d03c80-a65e-11ea-8896-3d35d767a1fe.png)
Zakladni zobrazeni, textarea je editovatelna a v CZ/EN se muze a nemusi zobrazovat jine HTML + popis.

![image](https://user-images.githubusercontent.com/1846915/83745597-118fe100-a65e-11ea-8cb9-07775211877e.png)
Jakmile se neco zmeni v textarea, je to hned propsano do toho preview. Po kliknuti na "Zkopírovat HTML" se aktualni obsah textarea zkopiruje to clipboardu.

Jak das vedet, jestli by tam teda mela byt jina verze pro CZ/EN, tak to spolu s dalsimi updaty muzu pushnout na master.

**Comment by zlodejpapiru** [comment]
Dobrá připomínka. Grafické materiály nemají na webu EN variantu.  Ale klidně bych ji vytvořil pro html - mohla by se zobrazovat jen v EN mutaci webu? Linkovat na disclaimer. 

Znění: 
Webarchived 
by National Library 
of the Czech Republic

**Comment by zlodejpapiru** [comment]
Super je to!

**Comment by Fasand** [comment]
Maji EN variantu, jenom neni na stejne URL: http://www.webarchiv.cz/en/graphics (pokud teda nemyslis ty samotne obrazky, ty jsou opravdu vsechny v cestine).

Kdyz si nekdo v EN strankach klikne dole na "Logo", tak se mu tedy tohle zobrazi se vsim v anglictine, vcetne teda toho widgetu.

![image](https://user-images.githubusercontent.com/1846915/83746340-3df82d00-a65f-11ea-934a-d891a34c843c.png)
Takhle nejak tedy. Jdu to tam hodit a uzavrit issue. Kdyby byly potreba nejake zmeny, tak ho jenom znovu otevri.

**Comment by zlodejpapiru** [comment]
Ano, myslel jsem obrázky. Takto ok, dík!
