### ISSUE TITLE
Tematické sbírky - obrázek

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#531]
v nejnovější test. verzi se začal po zadání nové sbírky objevovat formát obrázku (jpg) - jednak v seznamu tem. sbírek (https://app.webarchiv.cz/cs/tematicke-kolekce), jednak pod textem anotace (https://app.webarchiv.cz/cs/tematicke-kolekce/test), prosím o odstranění

**Comment by Fasand** [comment]
Co tak koukám, tak to neni novinka (urcite to bylo uz za Martina), jenom se asi doted nepouzivaly ty attachments. Ty se vybiraji pri vytvoreni kolekce nebo se daji nahrat i do existujici a jsou na jine urovni nez screenshot. Screenshot je jen jeden a zobrazi se jako nahled, attachments muze byt nekolik a zobrazuji se na ne spravne jenom ty linky.

Např. u https://app.webarchiv.cz/cs/tematicke-kolekce/pokusna-kolekce je ten attachment jiny nez screenshot, tak asi takhle to muzete pouzivat nebo nemusite. Kazdopadne k tem attachments se da aktualne pristoupit jenom pres ty linky.

Mam teda treba smazat ty linky v seznamu kolekci (https://app.webarchiv.cz/cs/tematicke-kolekce?page=1) a nechat v detailu? Nebo treba misto toho "png" dat neco jako "Příloha #1" atd.?

**Comment by mariehaskovcova** [comment]
jasný, už chápu, dělá to attachement, který aktuálně nepoužíváme, což mě zmátlo. Např. tedy sbírka https://app.webarchiv.cz/cs/tematicke-kolekce/test má obrázek i attachement. Koukám, že příloha (attachement) nejde smazat/nahradit (je v poli Files to delete) a nejde mi ani přidat nová (aby šlo vložit víc příloh).
Jinak jestli ty linky smazat a nechat jen v detailu nebo přejmenovat na Příloha 1 atd. ještě proberu s ostatníma a dám vědět. díky

**Comment by mariehaskovcova** [comment]
prosím linky nechat a pojmenovat jednotně **příloha** (případně příloha 1, příloha 2, jak píšeš), koukni prosím na to, aby šla příloha smazat (kdyby sem např. někdo omylem hodil obrázek), případně přidat

**Comment by mariehaskovcova** [comment]
ahoj, máš už toto zpracované?  ještě jsme tu trochu diskutovali jestli měnit ten název na příloha

**Comment by mariehaskovcova** [comment]
vyřešeno, názvy necháváme, editace příloh funguje
