### ISSUE TITLE
CC issues při migraci produkční databáze

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#536]
Tyhle bude potřebovat zkontrolovat
```
web_1        | Found 659 contracts with creative_commons_type set to an incorrect value.
web_1        | Updated 653 contracts to correct CC type
web_1        | Some contracts couldn't be matched automatically:
web_1        | format: (<pk>) <str> – <cc_type>
web_1        | (4511) 20 / 2020 – https://creativecommons.org/licenses/by-nc-sa/3.0/cz/
web_1        | (4457) 22 / 2019 – https://creativecommons.org/licenses/by-nc-sa/3.0/cz/
web_1        | (2498) 34 / 2012 – Uveďte původ-Neužívejte komerčně-Nezpracovávejte 3.0 Unported
web_1        | (2400) 517 / 2011 – Attribution 4.0 International
web_1        | (1384) 159 / 2010 – Attribution-NonCommercial 3.0 Unported
web_1        | (1245) 19 / 2010 – http://chameleoncharlie.cz
```

**Comment by westfood** [comment]
Migroval jsem produkční databázi a vypadli tyhle CC issues.. Moc nevím co s tím, možná to bude stačit upravit v adminovy.

**Comment by mariehaskovcova** [comment]
věděl bys @Fasand, co s tím? Souvisí to nejspíš s výběrem typu CC licence? Screenshot je už z ostrého Seederu (aktuálně na produkci) Díky.

<img width="1440" alt="CC-screen shot" src="https://user-images.githubusercontent.com/19947819/89167225-69be6300-d57b-11ea-9a10-842d56dd9e1b.png">

**Comment by Fasand** [comment]
Parada, jsem rad ze jich par vyskocilo, tedy by to melo spravne fungovat. Tohle jsou ty smlouvy, ktere se  nepodarilo sparovat automaticky, chce to tedy manualne ze Seedera.

Ten seznam 6 spatne zadanych je v tom specifikovanem formatu, tedy na zacatku `<pk>` a potom nazev a ta nastavena hodnota.
Ke kazdemu se da tedy pristoupit pres `https://webarchiv.cz/seeder/contracts/<pk>/edit` a tam manualne upravit CC na ten spravny. Stavajici hodnota je to posledni na radku, takze se da orientovat podle toho.
e.g. smlouva 20 / 2020 (pk 4511) bude `CC BY-NC-SA 3.0 CZ`

**Comment by mariehaskovcova** [comment]
ok :) Těch 6 špatně zadaných bych tedy měla upravit já přes https://webarchiv.cz/seeder/contracts/<pk>/edit, jak popisuješ, viď? Odkaz mi háže 404ku - asi je to aktuálně v procesu, viz konverzace ve Slacku

**Comment by Fasand** [comment]
To byl jenom URL template :) tady mas kdyztak ty opravdove url + ten nazev smlouvy pro kontrolu a aktualni hodnota, ze ktere ve vetsine pripadu vyctes, co by tam vlastne melo byt.

```
https://webarchiv.cz/seeder/contracts/4511/edit
20 / 2020 – https://creativecommons.org/licenses/by-nc-sa/3.0/cz/

https://webarchiv.cz/seeder/contracts/4457/edit
22 / 2019 – https://creativecommons.org/licenses/by-nc-sa/3.0/cz/

https://webarchiv.cz/seeder/contracts/2498/edit
34 / 2012 – Uveďte původ-Neužívejte komerčně-Nezpracovávejte 3.0 Unported

https://webarchiv.cz/seeder/contracts/2400/edit
517 / 2011 – Attribution 4.0 International

https://webarchiv.cz/seeder/contracts/1384/edit
159 / 2010 – Attribution-NonCommercial 3.0 Unported

https://webarchiv.cz/seeder/contracts/1245/edit
19 / 2010 – http://chameleoncharlie.cz
```

**Comment by mariehaskovcova** [comment]
ok, super, díky, opraveno, takže to tu už můžu nejspíš uzavřít :)
