### ISSUE TITLE
Rozbitá recaptcha při vkládání webu na produkci

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#541]
https://webarchiv.cz/cs/pridat-web

**Comment by westfood** [comment]
Vytvořil jsem nové klíče, vyexportoval jsem klíče pro docker runtime a na testu to běží. Až to hodím na produkci, vyřeším to tady.

**Comment by westfood** [comment]
Nasazeno na produkci via: https://github.com/WebarchivCZ/Seeder/pull/548

**Comment by mariehaskovcova** [comment]
recaptcha sice vypadá, že funguje - po vložení návrhu následuje kontrola (obrázky atd.), návrh se odešle, přijde poděkování, ale návrh už nedoputuje na mail webarchiv@nkp.cz...

**Comment by westfood** [comment]
Řeším to teď s Infra NK. Je potřeba aby nám povolili posílat SMTP zprávy.

**Comment by mariehaskovcova** [comment]
návrhy chodí, díky, uzavírám
