### ISSUE TITLE
Vyřešit hostování statických souborů v Django.

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/Seeder#544]
Jak jela produkce v debug módu, nevšiml jsem si, že django neservíruje static. Je potřeba to dořešit.

**Comment by Fasand** [comment]
Django by podle mě ani nemělo servírovat static/media, na to tam je nginx, ne? V hlavnim `urls.py` je teda uvedeny radek na servirovani media, ale to se myslim ignoruje kdyz je `DEBUG=False` a bezi tedy jenom na lokale.
Jinak debug je na produkci stále nastavený

**Comment by westfood** [comment]
jj vím, už jsem to dořešil na testu před pár týdny.. ale bylo třeba upgradovat docker z verze z roku 2017 do současnosti, protože nginx nechtěl připojit volume.. ještě to udělám na produkci a mělo být cajk.

**Comment by westfood** [comment]
nasazeno na produkci
