### ISSUE TITLE
certifikát

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#549]
po nasazení testu na produkci nefunguje odkaz na certifikát http://www.webarchiv.cz/cs/certifikovano (nefunkční cron?)

**Comment by Fasand** [comment]
Vyreseno hotfixem https://github.com/WebarchivCZ/Seeder/commit/986532f3fb85ac6ca144456a76989fd90b47825b, na testu jiz funguje spravne
