### ISSUE TITLE
při změně názvu zůstává v URL původní

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#554]
když změníme název kolekce, v URL se už nezmění, šlo by to změnit? Např.: původní název “Test”, změněn na “Komunální volby a volby do senátu 2020”, v URL zůstává test 

https://www.webarchiv.cz/cs/tematicke-kolekce/test

**Comment by Fasand** [comment]
Jde to dvema zpusoby:
1. Po kazdem ulozeni tematicke kolekce se vygeneruje nova URL podle ceskeho nazvu, tedy pokud se nazev jakkoliv zmeni, zmeni se i URL tematicke kolekce
2. Nebude se URL menit automaticky ale pribude tlacitko u tematicke kolekce jako "Aktualizovat URL" ktere zmenu jednorazove provede.

Moznost 1 je samozrejme jednodussi (pokud by to proslo migrací) a nemusi se potom na nic myslet, kazdopadne ta zmena se stane i kdyz nekdo treba omylem pripise pomlcku nebo opravi preklep v nazvu. URL potom tedy teoreticky nebude tak staticka jako doted a kdyby se menila casto, tak by mohl byt problem s vyhledávači nebo kdyz si ji nekdo hodi do zalozky či co.

Moznost 2 je stale jednoducha na implementaci a je potom na kuratorovi, jestli je i po zmene nazvu url porad dostacujici nebo jestli je potreba URL aktualizovat (napr v tom tvem pripade).

Výběr zalezi tedy hlavne na tom, jestli je dulezitejsi mit vzdy aktualni spravnou URL bez jakehokoliv uzivatelskeho inputu nebo radsi mit ty URL staticke a menit jen v pripade nutnosti. Pokud se nazvy kolekci meni uplne minimalne, tak je moznost 1 samozrejme v pohode, ale pokud by se nazev trochu upravil kazdy mesic, tak uz by to bylo horsi (z uzivatelskeho hlediska).

**Comment by mariehaskovcova** [comment]
díky za komentář, tlačítko "Aktualizovat URL" by bylo asi lepší - vědomě tu URL buď opravíme nebo ponecháme starou

**Comment by Fasand** [comment]
Souhlas, bude to tam.
![image](https://user-images.githubusercontent.com/1846915/102352496-20aa0100-3fa8-11eb-9d85-e215f6ac4015.png)
