### ISSUE TITLE
Hlavní stránka - abecední řazení zdrojů

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#555]
v polích na Dashboardu (Hlavní stránka) bychom chtěli řazení zdrojů abecedně

**Comment by Fasand** [comment]
Plati to i pro karticky:
- Hodnocení, která spravujete
- Otevřená hodnocení

Nebo by v tomto pripade melo zustat serazeni podle poctu hodnoceni?
Pripadne podle poctu hodnoceni a potom podle abecedy, kdyz vice zdroju ma stejny pocet (to mi dava nejvetsi smysl).

Plus aktualne jsou zdroje u obou karticek serazeny od nejmíň (nahoře) do nejvíc (dole) hodnocení. To může zůstat nebo dává větší smysl to v jednom/obou případech převrátit?

Podobne "Zdroje ke kontrole" jsou aktualne serazene od nejstarsiho (nahore) po nejmladsi (dole) z tech nahodne vybranych (viz #522).
Melo by se toto zachovat nebo je uzitecnejsi mit zdroje serazene abecedne?

**Comment by mariehaskovcova** [comment]
**“Hodnocení, která spravujete” + “Otevřená hodnocení”**
- řazení podle počtu hodnocení je ok
- řazení od nejmíň (nahoře) do nejvíc (dole) je ok, úplně ideální by bylo tlačítko, kdy by si to mohl kurátor překlápět (od nejmíň po nejvíc a naopak, první má pro info, co má hodnotit sám, druhé pro info, že už ohodnotili i všichni ostatní), pokud by to nebylo náročné na implementaci, jinak takto ok

**“Zdroje ke kontrole”**
-  aktuální řazení od nejstaršího - tady je to ok

**Comment by Fasand** [comment]
Uz jsem ti planoval psat, ze to preklapeni poradi bude docela komplikovane a pak me napadla jednodussi implementace, takze bude to tam :)

![image](https://user-images.githubusercontent.com/1846915/102350210-da06d780-3fa4-11eb-8ac9-5d8d096c2a2d.png)

Pridal jsem ikonku na zmenu poradi zatim jenom na ta hodnoceni, protoze jinde mi to uplne nedava smysl, kdyz tam nejde videt nejake explicitni razeni mimo abecedy, ale je to nachystane tak, ze se ta moznost da pridat jednim radkem pro jakoukoliv karticku.

Preklapi se poradi na urovni vsech vysledku, ne jen tech, ktere uzivatel vidi – napr. kdyz je v otevrenych hodnocenich 100 polozek, tak se uzivateli zobrazi v karticce prvnich 10 podle klasickeho razeni a po prehozeni poradi to je prvnich deset z druheho konce te stovky.

To prohozeni poradi zustava ulozene v sessionu, tedy dokud se uzivatel neodhlasi, zustane mu to poradi, ktere si vybral. Kazde kliknuti obrati poradi, takze to v podstate skace mezi 0 a 1.

**Comment by mariehaskovcova** [comment]
super, to vypadá skvěle, stačí opravdu asi jen u toho "hodnocení". Až to bude na testu, mrkneme na to, díky!
