### ISSUE TITLE
Scheduling sklizni s u kolekci s pravidelnou frekvenci

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#568]
TODO Bude treba pripravit scheduling (pre-planing) sklizni unikatniho typu (serials, topics, etc) a kombinovatelneho / nekombinovatelneho obsahu u kolekci s nastavenou frekvenci. Kurator donastavi nasledne data podla reality a approvne (tym dojde k freezu (v pripadne nutnosti se vzdy da unfreeznut a znova upravit))

dle meetingu 20201217 s @mariehaskovcova @Fasand

**Comment by JanMeritus** [comment]
jde doimplentaci #402 pro freez settingu sklizne ze strany kuratora

WF - 
sklizen zalozena, 
probihaji editace,
sklizen je definitivni (ze strany kuratoru)
az pak prebira operator sklizne a dava running

**Comment by mariehaskovcova** [comment]
za mě stačí sloučit stav sklizeň založena + probíhají editace do jednoho - planned, pak hned může následovat stav readyTo Harvest

**Comment by Fasand** [comment]
@JanMeritus Pokud tedy souhlasíš s @mariehaskovcova, v podstatě by se jen přidal nový stav `ReadyToHarvest` a zbytek by zůstal jak je:
- Planned &rarr; **ReadyToHarvest** &rarr; Running &rarr; [Success, Success with failures, Cancelled, Failed]

Jakmile se stav změní na `ReadyToHarvest`, semínka se zmrazí jak tomu bylo doteď u `Running`.
Změna stavu na `Running` potom tedy už neudělá nic.

**Comment by JanMeritus** [comment]
souhlas

**Comment by mariehaskovcova** [comment]
v testu to vypadá v pořádku, můžeme zavřít
