### ISSUE TITLE
Nelze upravit stav sklizně Test

### ISSUE THREAD

**Issue by habetpet** [WebarchivCZ/Seeder#576]
Na produkci není možné upravit stav sklizně Test (č. 218), stránka háže Server Error (500).

**Comment by Fasand** [comment]
Na produkci nemám přístup (@mariehaskovcova), ale ani nic nevidím v Sentry, může to být tedy zatím cokoliv.
Pokud se dá u sklizně alespoň načíst přehled, jak prosím vypadá? Frekvence semínek, archive-it, atd., klidně screenshot stránky. Nejsem si jistý, jestli mi to vůbec pomůže, ale třeba to alespoň přiblíží možný problém.
Případně na app.webarchiv.cz se něco takového neděje nebo nelze replikovat?

**Comment by habetpet** [comment]
![Detail_Test](https://user-images.githubusercontent.com/39479150/112823419-8c146c00-9089-11eb-8bbb-b3f8d4198198.PNG)
![Upravit_Test](https://user-images.githubusercontent.com/39479150/112823433-90d92000-9089-11eb-84e8-a90bed521af1.PNG)
![Error_Test](https://user-images.githubusercontent.com/39479150/112823442-93d41080-9089-11eb-8073-f69da209d88e.PNG)

**Comment by mariehaskovcova** [comment]
děje se Petro @habetpet to samé na testovacím prostředí app.webarchiv.cz?

**Comment by JanMeritus** [comment]
@mariehaskovcova prosim o nasimulovani zalozeni teto sklizne na testu, nicmene dle toho co si telefonicky hovorila, problem je ze sklizen neobsahuje primo zadne seminka, jsou zadane jen v anotaci

@Fasand tato, pripadne exception by prinejhorsim mala byt osetrena nejakou hlaskou aplikace, ne 500

**Comment by mariehaskovcova** [comment]
toto byla výjimečná sklizeň - chtěli jsme udělat test, jak se semínka sklízí,  jsou to ale semínka, která jsou v Seederu, ale nemají archivační stav, tzn. Seeder by je do sklizně nevyexportoval. Zatím nefunguje u sklizní funkce test, proto jsem semínka naházela do textu anotace - aby si je operátor mohl odtud vzít a abychom měli informaci/evidenci, že sklizeň proběhla. Vypadá to asi takto: https://app.webarchiv.cz/seeder/harvests/143/detail, https://app.webarchiv.cz/seeder/harvests/143/urls. Může to mít vliv na Error? 
Error by to asi házet nemělo - spíš nějaké info, že je sklizeň prázdná, chybí semínka - pokud to tedy s tím souvisí

**Comment by JanMeritus** [comment]
@Fasand tvrdi ze problem je u snahy u freeze pokud harvest de facto neobsahuje zadny seminka

za mne hlavne - zacit osetrovat excepce hlaskama - obecne

tato issue se muze resit jednoduchou kontrolou - typu alert

**Comment by Fasand** [comment]
Problém je s tím, že sklizeň vlastně nemá žádná semínka, všechna jsou v anotaci. Jakmile se změní stav na probíhající, pokusí se semínka zmrazit a jelikož je set prázdný, tak to spadne. Je to tedy bug, který jen není ošetřený v `Harvest.freeze_seeds`.

Plán: pokud nejsou ve sklizni žádná semínka (přes custom seeds atd), tak by nemělo být možno změnit stav sklizně na running

**Comment by Fasand** [comment]
Částečně bude vyřešeno #583 ale zatím bez upozornění že nastala nějaká chyba, to zkusím nechat na další milestone.
Semínka se totiž mrazí až v pre_save signálu, jelikož zmražení může trvat docela dlouho, takže v tom signálu nemám přístup k user requestu, abych mohl uživateli vlastně říct, že se něco pokazilo.

Dalo by se to částečně vyřešit třeba pomocí https://github.com/django-notifications/django-notifications i když i to asi bude trochu prasečinka. Další alternativa je samozřejmě zmrazit semínka v rámci toho requestu, na což by alo bylo potřeba, aby se semínka zmrazila nejpozději tak do 10 sekund, jinak tam bude hrozné čekání.

**Comment by Fasand** [comment]
Jelikož získání všech semínek je nyní poměrně rychlé, přidal jsem do Add & Edit formulářů Sklizní navíc kontrolu: pokud je vypočítaný seznam semínek prázdný, zobrazí uživateli červený error alert (viz screenshot).

Je to spíše aby si uživatel mohl všimnout chyby a opravit ji. I pokud by tam teď alert nebyl, tak by to nemělo vyhodit Error 500, jelikož samotné zmrazení semínek nyní kontroluje jestli nějaká semínka vlastně jsou nebo ne.
V případě, že nejsou, nic se nezmrazí a stav Sklizně se vrátí na "Plánované", aby se mohla chyba opravit a znovu nastavit na ready to harvest.

![image](https://user-images.githubusercontent.com/1846915/131817944-4cebd6b9-0c44-4ef0-81d1-9332c2a02bb1.png)
