### ISSUE TITLE
Omezeni platnosti doby prihlaseni

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#579]
Prosim o zavedeni konfigurovatelne doby akceptace prihlaseni, by default max 4 hod (pripadne ak by se to ukazalo spatny tak se to muze operativne posunout)

**Comment by Fasand** [comment]
Přidat SESSION_COOKIE_AGE do env.py, nebo kamkoliv kde se nacita env z Dockeru. Default nastavit na 4 hodiny, pokud neni jinak specifikovano
