### ISSUE TITLE
tematické kolekce - vygenerování seznamu semínek

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#582]
vygenerování seznamu semínek u tematických kolekcí:

- v Seederu (po vložení semínek se roztřídí na Mimosystémová semínka a Přiřazené zdroje a už zpětně nelze získat jejich seznam, jedině pak až při plánování sklizně, př. https://app.webarchiv.cz/seeder/harvests/2/collection_edit)

- na webu, přímo u tematické kolekce, možnost pro uživatele export semínek do CSV 

viz issue #402

**Comment by Fasand** [comment]
Novy link v akcich u tematicke kolekce v Seederu, ktery otevre textak s URL podobne jako tomu bylo doted u sklizni.
Na webu je pod přílohami zatim textovy odkaz ktery po otevreni stahne ten samy seznam primo v CSV.

Na webu u kolekce:
![image](https://user-images.githubusercontent.com/1846915/117642883-1d4a2880-b188-11eb-81fa-82802d8c09b6.png)

V Seederu u kolekce:
![image](https://user-images.githubusercontent.com/1846915/117642914-25a26380-b188-11eb-945b-6e455cb7d2c9.png)

**Comment by mariehaskovcova** [comment]
na testu zatím nevidím, testovací verze se aktuálně zobrazuje nestandardně

<img width="222" alt="Snímek obrazovky 2021-05-10 v 14 33 06" src="https://user-images.githubusercontent.com/19947819/117659826-b6833a00-b19c-11eb-8ec2-d0a63b95dd87.png">

**Comment by Fasand** [comment]
Já už to na testu vidím, každopádně pokud tam vidíš tu ikonku ze screenshotu, tak bys měla vidět i ta nová tlačítka.
Např: https://app.webarchiv.cz/seeder/harvests/40/collection_detail

To DjDT je kdyztak Django Debug Toolbar, uz tam byl nainstalovany driv ale v nejakem bode se vypnul a pri poslednim updatu jsem ho znovu zapnul. Bez odškrtnutí "SQL" se stránky většinou načítají výrazně pomaleji, takže pokud o něj nikdo další nebude stát, nastavím ho aby se zobrazoval jenom mně.

**Comment by mariehaskovcova** [comment]
super, už ty funkce na testu vidím (export semínek v Seederu i list CSV na webu - kdyžtak mrkni @zlodejpapiru), díky
(neviděla jsem předtím ani ty funkce ani kolekci Test 2020 - tu máš asi lokálně, každopádně funkce fungují :))

ikonku DjDT (a po rozkliknutí lištu, toolbar) jsem viděla poprvé, nikdy jsme jí nepoužívali, tak jsem nevěděla, jestli je to ok, asi by mohla být vidět jen u tebe - ať to nemate kurátory při kontrole testu před nasazením

koukám ještě, že hl. stránka webu na testu je nějaká rozsypaná (když srovnáš s živým webem), hned ten první řádek, logo, jazykové verze atd.

**Comment by Fasand** [comment]
RE hl. stránka: jak jsem pridaval to tlacitko pro CSV kolekce, tak jsem si vsiml, ze je na webu uz X let stary Bootstrap 3.3, od ktereho se spousta veci zmenila, tak jsem ho updatnul na 4.6.0, ktery by zase par let mel byt docela aktualni.

Nejake veci se tim samozrejme rozbily, takze jsem je upravil aby se co nejvice podobaly puvodni verzi, ale samozrejme ruzne mezery apod. jsou trosicku jine a navbar ted vypada jinak hlavne v mobilni verzi (i kdyz relativne podobne puvodnimu).
Jelikoz je na verejnem webu jen par stranek, pokud jsi narazila na nejake vyrazne rozdily, radsi bych je poupravil s tou novou verzi nez aby se to vracelo na stary Bootstrap. Zatim jsem si vsiml ze jsem zapomnel na "Zobrazení" u "tématické sbírky" (je teď nalevo), jinak mi přijde, že jsou jen ty mezery trochu jiné.

**Comment by mariehaskovcova** [comment]
v té nové verzi na hlavní stránce jsou ještě navíc černé čáry - hned pod vyhledávacím polem waybacku 

ještě jedna grafická maličkost (to ale není novou verzí, funkčnost je ok) - v sekci https://www.webarchiv.cz/cs/pridat-web, když uživatel listuje nabídkou (Přidejte web / Creative Commons / Výběr zdrojů / Pomozte nám uchovat český web / FAQ), všechny položky jsou pořád podtržené, mělo by to být stejné jako např. tady - https://www.webarchiv.cz/cs/celoplosne-sklizne, podtržítko mizí tam, kde se uživatel nachází
