### ISSUE TITLE
Rozdeleni objektu kolekci

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#592]
Pro implementaci #402 je nutno pristuoupit k rozdeleni kolekci na interni objekt (rezie seminek) a externi objekt (rezie CMS zobrazovani). Externi kolekce bude zobrazovat seminka vsech internich kolekci ktere jsou ji prideleny kuratorem.

Tyto interni kolekce jsou dale pridelovany taky do objektu sklizni. 

Migrace se provede 1:1

**Comment by Fasand** [comment]
- Aktualni tematicke kolekce se prevedou na interni kolekce – kvuli vazbam na sklizne
  - Internim kolekcim pribude Foreign Key na externi kolekce a ubydou prezentacni data
- Pro kazdou se vytvori stejnojmenna externi kolekce, ktera bude mit opět ordering a zbytek prezentacnich dat

**Comment by JanMeritus** [comment]
@Fasand ordering u externich kolekci je dle nejaky specifikace (tj ostava stejna u externich kolekci, jak to bylo pred rozdelenim)?

**Comment by Fasand** [comment]
Jj, tak to mám zamyšlený. Nyní mají tématické kolekce pole `order`, podle kterého se řadí kolekce na webu, tak toto pole bych převedl na externí kolekce a u interních bych se ho zbavil – interní kolekce by se mohly asi řadit v rámci té přiřazené externí, ale podle mě by to nemělo moc užitku.

**Comment by Fasand** [comment]
Tak migrace se mi zřejmě povedla a to i s revert scriptem, tedy je teoreticky manuálně navratitelná, kdyby bylo potřeba.
Způsobuje ale logicky trochu maglajz, protože sice TopicCollection model zůstává vesměs stejný, ale cokoliv prezentačního je nyní řešeno přes ExternalTopicCollection, takže to je prostě větší jednorázový zásah do kódu.

Tedy otázka jen pro ujištění: byl by nějaký problém, kdybych teď pozměnil Seedrové URL pro kolekce? Tedy jen co se objeví v adresovém řádku když prohlížím interní/externí kolekce, když je edituji apod.
Začínám se v tom tak jak to je teď trochu ztrácet, tak bych tomu rád dal trochu štábní kulturu, aby i podle URL bylo naprosto jasné, jestli edituji interní nebo externí kolekce

**Comment by mariehaskovcova** [comment]
mě k tomu jen napadá (nevím, jestli to přímo souvisí), aby to nerozbilo stávající linky tem. kolekcí prezentovaných na webu (např. https://www.webarchiv.cz/cs/tematicke-kolekce/covid-19), odkazujeme na ně v různých materiálech, článcích atd.

**Comment by Fasand** [comment]
@mariehaskovcova Na to jsem myslel a ty by měly zůstat identické i po přechodu na Externí tématické kolekce.
Tohle se týká jen URL v rámci Seederu, tedy mě vlastně nenapadá, proč by to mělo dělat nějaký problém, ale radši jsem to sem chtěl hodit.
