### ISSUE TITLE
Definice default type HarvestConfiguration

### ISSUE THREAD

**Issue by JanMeritus** [WebarchivCZ/Seeder#594]
ad navrh @Fasand v #402 

- jestvuje pro kazdy typ Sklizne (Serials, Topics, Tests, Totals)
- navyse existuje tzv default, priradzen najpr nasledne podle typu sklizne updatovan / pokud typ sklizne nema definovan harvestConfiguration tak default
- key value pairs pole:
   - "seedsNo": 300,
  - "duration": 259200,
  - "budget": 10000,
  - "dataLimit": 10000000000,
  - "documentLimit": 0,
  - "deduplication": "PATH",

**Comment by Fasand** [comment]
- Novy model `HarvestConfiguration(BaseModel)`: { harvest_type, seedsNo, duration, ..., deduplication }
- `Harvest` bude mit nove required fields "seedsNo, duration, ..., deduplication", ktere se nastavi v poradi: Manuálně -> HarvestConfig -> model default (ty specifikovane výše)
- V obou pripadech budou fields nastavene na PositiveInteger pro validaci az na deduplication (Char)
- Pri vytvareni sklizne se po vyberu typu sklizne pres AJAX stahne nastaveni pro dany typ sklizne – pokud neexistuje, ukaze se nejake upozorneni
- HarvestConfig budou moci menit pouze uzivatele ve skupine "Tech" (a superusers)

**Comment by Fasand** [comment]
@JanMeritus sorry že jsem si toho všiml až teď, ale mělo by tam opravdu být i `seedsNo`? To jsem chápal jednoduše jako celkový počet semínek ve všech kolekcích ve sklizni a každá kolekce pak má i vlastní `seedsNo`, viz https://github.com/WebarchivCZ/Seeder/issues/402#issuecomment-746038204
Chápu to tedy jako vypočítanou hodnotu, nikoli přednastavenou.
