### ISSUE TITLE
tematická kolekce - možnost zrušit volbu u plánování sklizně

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#602]
když plánuju sklizeň, která by neměla zahrnovat žádnou tematickou kolekci a omylem ji vyberu, nejde už tato volba zrušit. Lze měnit výběr tematické kolekce, ale už není možné dostat se do bodu, že kolekce nezahrnuje žádnou tematickou kolekci

**Comment by Fasand** [comment]
Přidám třeba tohle k výběru:
![image](https://user-images.githubusercontent.com/1846915/140080350-ebc39d00-24bd-4e45-9d9f-2a4ad6deedf0.png)
```
<a class="pull-right" href="#" onclick="document.getElementById('id_topic_collections').value = null">CLEAR</a>
```

Případně to jde odvybrat pomocí Ctrl+Click nebo Cmd+Click (Mac)
