### ISSUE TITLE
pole combined (přidat sklizeň)

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#604]
pole “combined” - automaticky by se zaškrtlo v metadatovém popisu, když se zkombinuje více typů (např. Archive-it + Manuals), kurátor to vidí, ale manuálně nevolí

**Comment by JanMeritus** [comment]
pole combined ma vyznam nejen u serials (kde se kombinace kolekci predpokladaby default), ale zejmena u topics, kde by to melo byt voleno kuratorem
