### ISSUE TITLE
objem dat - editovatelné pole na hl. stránce webu

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#605]
prosíme o vytvoření editovatelného pole pro objem dat na hl. stránce, abychom mohli rychle rovnou měnit údaje a nemuseli čekat na celkové nasazení Seederu

**Comment by Fasand** [comment]
Zdá se, že tento problém už byl částečně řešený v minulosti, objem dat se načítá z texťáku, který se dá commitem teoreticky měnit přímo na produkci: https://github.com/WebarchivCZ/Seeder/blob/master/Seeder/www/templates/includes/webarchive_size.txt
Každopádně asi to pořád není úplně ideální řešení, jelikož po commitu by se měla stejně znovu nasadit produkce, což je kvůli jednomu souboru trochu zbytečné.

Napadají vás i nějaké další hodnoty/texty, které by se mohly občas měnit a bylo by dobré pro ně mít podobnou možnost editace za běhu?

Buď bych pro toto vytvořil jednoduchou tabulku v databázi (`{key: value}`), kam by se nahrály default hodnoty a pak by se daly měnit z admina. Nebo možná ještě jednodušší řešení by bylo udržovat lokální JSON soubor (mimo git, opět s defaults), kde by byly ty samé informace a dal by se editovat přes formulář v Seederu, asi také jen pro adminy.

**Comment by Fasand** [comment]
Zatím jsem to vyřešil tím JSON souborem a editací konstant v Seederu – jen pro superuživatele, mohu upravit třeba na nějakou skupinu uživatelů nebo klidně nechat pro všechny.

Link jsem dal pod "Historie hledání", ve formuláři se nabídnou všechny předdefinované konstanty s jejími aktuálními hodnotami a je možné je změnit. Tím se přepíše ten soubor a následně se všude načítá upravené hodnota.
![image](https://user-images.githubusercontent.com/1846915/146003146-9974c3c7-58b8-41ad-aa5e-a4ac2d7a14c4.png)
(zatím to mám v PR)

**Comment by mariehaskovcova** [comment]
to asi uvidíme až v testu, viď? Až bude fungovat, koukneme, takhle to vypadá dobře

**Comment by zlodejpapiru** [comment]
- není možné ověřit s přiloženým loginem

**Comment by Fasand** [comment]
@zlodejpapiru Je to nyní opravdu jen pro superuživatele – nevím, jestli by toto mělo být dostupné úplně pro všechny Seeder uživatele, ale mohl bych na tu buď vytvořit další skupinu nebo to třeba povolit skupině "Tech", která spravuje konfigurace sklizní?

Prozatím jsem uživateli "test" nastavil superusera a vrátil heslo, co jsem posílal emailem – chtěl jsem se za něj přihlásit, abych to mohl otestovat a asi už bylo změněné.
