### ISSUE TITLE
datum sklizně - automatické vyplnění údaje

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#607]
na ostré verzi je to ok - po kliknutí na pole kalendáře se datum automaticky propíše, v testu se asi něco rozbilo, musí se vyplňovat ručně

**Comment by Fasand** [comment]
Teď to bude bez testovací verze těžké, ale jakmile naběhne, prosím o prověření, že to je stále problém.
Sám se tomu trochu divím, protože si pamatuji, že to opravdu byl problém, ale když teď vytvářím sklizeň a vyberu datum přes kalendář, tak se mi správně propíše do pole a uloží. Při editaci mi pole také funguje správně.

To řešení s ikonkou kalendáře je vlastně o dost jednodušší než to bylo v minulosti, protože to používá nativní HTML5 validaci a komponentu pro výběr datumu. Otravný side-effect je, že se nedá v poli upravit formát datumu, tedy např. nejde nastavit 24-hodin místo AM/PM, ale z pravidla by to pak mělo fungovat ve všech podporovaných prohlížečích, což by u většiny mělo být už několik let: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#browser_compatibility
Každopádně Safari údajně dostalo plnou podporu teprve 26.4.2021 a Firefox až 5.10.2021, napadá mě tedy jedině, že byl možná problém v prohlížeči.

Pokud však problém stále bude, prosím o popis kde se to přesně děje, jak a třeba nějaký screenshot.

**Comment by mariehaskovcova** [comment]
aktuálně neověříme

**Comment by mariehaskovcova** [comment]
toto pořád trvá, viz screenshot
![datum](https://user-images.githubusercontent.com/19947819/202217452-57992ec8-e437-4602-961c-3f60eae49a31.PNG)

**Comment by Fasand** [comment]
Už si nepamatuji přesně, proč jsem to pole měnil na DateTime (s časem) z původního Date, ale podle mě to musel být nějaký požadavek. Každopádně se to krylo s dobou, kdy přestala fungovat původní utilita na vybírání datumu, tak jsem ten widget přepisoval, aby používal klasický HTML datetime-local input, který je sice už univerzální, ale takový trochu hloupý...

Každopádně podařilo se mi upravit ten loadovací JavaScript, aby správně nastavil datum sklizně na to rozkliknuté z kalendáře:
![image](https://user-images.githubusercontent.com/1846915/206678748-d982c75f-0dc4-4564-8194-175170cd6be7.png)
Automaticky se nastaví čas na 12:00 (poledne), datum se pak ale samozřejmě dá změnit, ať už ručně nebo přes ten HTML widget. Jen se bohužel datum zobrazí v lokálním formátu nastaveném na počítači/v prohlížeči, takže třeba mně se zobrazuje "12/17/2022", podle mě protože mám v Chromu nastavený výchozí jazyk na angličtinu. Datum se každopádně propíše správně jako 17.12.2022
