### ISSUE TITLE
označení a řazení zdrojů - návrh od vydavatele a ISSN

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#608]
u hl. záznamu zdroje je možné vybrat z pole "navrženo" ze 4 možností (vydavatel, návštěvník, ISSN, kurátor). Prosíme o zdroje, které jsou navrženy vydavatelem nebo ISSN, aby byl jejich název v seznamu zdrojů "Hodnocení, která spravujete" a "Otevřená hodnocení" vyznačený  tučně a zobrazoval se přednostně v horní části seznamu

**Comment by Fasand** [comment]
Aktuálně se kartičky hodnocení řadí podle:
1. Počtu hodnocení, nejmenší nahoře
2. Názvu zdroje, alfabeticky od vrchu

Kartičky Vydavatel/ISSN by se tedy měly řadit přednostně nezávisle na počtu hodnocení? Posloupnost by tedy pak vypadala:
`Vydavatel/ISSN nebo ne -> Počet hodnocení -> Název zdroje`

**Comment by mariehaskovcova** [comment]
jj, je to přesně tak, jak píšeš
