### ISSUE TITLE
pole frekvence sklízení 

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#609]
prosíme o upozornění u zdrojů, kterým byl přiřazený stav Archivován nebo Archivován bez smlouvy, že je povinné zadat frekvenci sklízení

**Comment by Fasand** [comment]
Přidávám následující kontrolu/upozornění při editaci zdroje a náhledu na existující špatně nastavený zdroj.
Pokud už je zdroj uložen s prázdnou frekvencí (a archivačním stavem), tak při každém načtení toho zdroje nebo jednoho z jeho semínek se zobrazí červený banner nahoře.

Při samotné editaci zdroje pak při špatném nastavení (archivační stav a prazdná frekvence) vyskočí otravný alert a pole Frekvence zčervená.

Podstatná otázka: teď to bude kurátora otravovat dokud nenastaví frekvenci sklízení, ale zároveň mu to dovolí zdroj takto špatně uložit, jen s těmi upozorněními. Je to tak správně nebo by to nemělo zdroj vůbec uložit, pokud není nastavena frekvence sklízení? @mariehaskovcova 

Upozornění u zdroje a semínek, které jsou takto již uloženy
![image](https://user-images.githubusercontent.com/1846915/146916364-5ab38eea-f941-4700-8ff0-85e4c7c48f90.png)
Alert
![image](https://user-images.githubusercontent.com/1846915/146915907-7b8804a6-ab76-4a34-9fff-4b4681f32bac.png)
Zvýrazněná frekvence
![image](https://user-images.githubusercontent.com/1846915/146915992-3fd791f5-eb7f-4ad8-b77f-021c1dea95ff.png)

**Comment by mariehaskovcova** [comment]
myslím, že frekvence by měla být u těchto dvou stavů povinná, kdyby to byl problém s ohledem na už vložený zdroje, stačí upozornění

**Comment by Fasand** [comment]
Existující zdroje s chybějící frekvencí tak prostě nadále zůstanou, tu kontrolu bych dal jen na editovací formulář. Tedy do budoucna by z formuláře nebylo možné upravit zroj na archivující stav a bez frekvence.
Pokud byste chtěli podchytit i existující zdroje, mohl bych ty špatné hodit třeba na dashboard do nové kartičky.

**Comment by Fasand** [comment]
Přidal jsem validaci na formuláři a nechal červené zvýraznění frekvence a červený banner u špatně nastavených zdrojů:
![image](https://user-images.githubusercontent.com/1846915/147071399-8fd32101-88c0-46b8-857e-6fdd36ab825a.png)

Jelikož těch upozornění tam je teď už několik a kurátora to nepustí zdroj uložit, pokud je nastavený špatně, tak jsem se zbavil toho otravného alertu - přišlo mi to jako už trochu moc.

**Comment by mariehaskovcova** [comment]
takhle to vypadá dobře, díky! Dashboard do nové kartičky není potřeba, ty existující záznamy pobereme a pak už ta funkce vlastně nebude potřeba, takže takhle je to ok
