### ISSUE TITLE
Adding screenshots

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#61]
Chybí funkcionalita přidávání screenshotů. Screenshot by se měl vytvořit automaticky, ale také by měl jít přidat manuálně a připadně jej smazat. 

Nevím, jak je vyřešené párování screenshotů se zdrojem, ale v současné chvíli to máme tak, že 1 zdroj = 1 screenshot. Pokud má zdroj přidaný screenshot, tak v databázi, v tabulce resources, je v poli screenshot_date datum pořízení a podle toho se jmenuje i samotný .png soubor. 

Pak to vypadá takto
http://www.webarchiv.cz/cs/katalog-stranek

**Comment by Visgean** [comment]
A ma tedy byt jenom jeden nebo jich ma byt vice?

**Comment by kvasnicaj** [comment]
Jeden je ok, při automatickém dělání screenshotu ho ber z prvního semínka.
