### ISSUE TITLE
QA - pole pro komentář

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#610]
prosíme upravit pole, aby bylo možné číst text komentáře, viz např. https://webarchiv.cz/seeder/qa/1625/detail

**Comment by Fasand** [comment]
Upraveno: dělal tam problém bootstrapový pull-right, který je jinak úplně všude.
Zároveň jsem komentáři nastavil pre-wrap, takže se budou newlines/mezery zobrazovat stejně jak byly zadány, už to tedy nebude jen souvislý text bez jakýchkoliv mezer.
![image](https://user-images.githubusercontent.com/1846915/147074963-44652851-7676-490e-87d7-2db495ee11fe.png)
