### ISSUE TITLE
interní tem. kolekce - úprava názvu pole "semínka podle podle frekvence"

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#612]
na schůzce jsme zijstili, že u interní tem. kolekce pole "Semínka podle frekvence" znamená ve skutečnosti "Tematické kolekce podle frekvence", je to jen chyba v pojmenování. Zvolená frekvence by se mohla objevit u hl. záznamu kolekce, podobně jako u záznamu jednotlivého zdroje

**Comment by Fasand** [comment]
Pamatuji si, že jsme to probírali, ale prosím o dovysvětlení @mariehaskovcova 

Chcete tedy jen u *Interních tematických kolekcí* změnit název pole "Semínka podle frekvence" na "Tematické kolekce podle frekvence"?
Jak by se pak měla frekvence zobrazit u hl. záznamu kolekce jinak než to je teď? Respektive myslíš "hl. záznamem" detail Interní kolekce nebo detail Externí kolekce ke které ta interní patří? Teď se již frekvence u interních kolekcí zobrazuje, jen se jmenuje "Semínka podle frekvence".

Pokud to tedy chápu správně, možná bych zvážil pozměnit to pojmenování pole frekvence u Interních tematických kolekcí.
V principu když nyní na sklizni zatrhnu "Tematické kolekce podle frekvence" = `Týdně`, tak se do sklizně přidají všechny Interní tematické kolekce, které mají nastaveno "Semínka podle frekvence" = `Týdně`.
Dávalo by mi tedy smysl, kdyby se to pole na interní kolekci změnilo třeba na "Frekvence sklízení" nebo klidně jen "Frekvence" jako je to u zdrojů, protože to to pole vesměs znamená. Na sklizních bych pak nechal stávající "Tematické kolekce podle frekvence"

**Comment by mariehaskovcova** [comment]
bohužel na to nemůžu mrknout teď do testu, protože neběží, ale souhlasím. Přejmenuj to prosím na pole "Frekvence", u sklizní to nech, jak to je. 
co jsem myslela tím hl. záznamem si musím připomenout, až poběží test:)
jen ještě - znamená to teda frekvenci sklízení kolekce jako celku bez ohledu na frekvenci sklízení jednotlivých semínek?

**Comment by Fasand** [comment]
Přesunul jsem `target_frequency` zvlášť do sklizne a zvlášť do tématické kolekce tak, aby ve sklizni bylo vše zachováno a v tématických kolekcích se jen pole nyní jmenuje "Frekvence":
![image](https://user-images.githubusercontent.com/1846915/166432012-87a83941-505b-4a30-8404-30213004c0e0.png)

RE otázka: Ano, v podstatě to pole "Tematické kolekce podle frekvence" za tebe akorát automaticky přidá do sklizně všechny TC, které mají nastavenou takovou frekvenci. Tím ty kolekce přidá v podstatě stejně, jako kdybys tu kolekci manuálně vybrala v poli "Tématické kolekce"

**Comment by mariehaskovcova** [comment]
chtěla bych se vrátit ještě k tomuto issue, který asi nebylo v danou chvíli možné otestovat. Podle tvého posledního komentáře by mělo jít ve sklizních plánovat tematické kolekce podle frekvence. 

Představuji si to analogicky jako u sklizní, kde se vybírají semínka podle frekvence.  Tzn. v kalendáři založím sklizeň, označím ji třeba "Tematické sklizně - půroční" a vyberu půlroční frekvenci. Je to tak? Zkusila jsem a dopadlo to takto:

sklizeň: https://app.webarchiv.cz/seeder/harvests/201/detail
(kolekce s půlroční frekvencí: https://app.webarchiv.cz/seeder/harvests/collections/internal/29 a https://app.webarchiv.cz/seeder/harvests/collections/internal/26)
semínka vypadají cca  takto: http://testseeds.com/1313250
