### ISSUE TITLE
mimosystémová semínka - úprava názvu pole

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#613]
prosíme rozšířit stávající název, je to užitečná informace pro nové uživatele

Mimosystémová semínka - sem vložte všechna semínka, po uložení zde zůstanou zdroje bez záznamu v Seederu, ostatní budu v poli Přiřazené zdroje

**Comment by Fasand** [comment]
Která z následujících dvou možností podle tebe vypadá líp / je jasnější?
1) Jako placeholder, tedy zobrazí se v samotném poli předtím, než se do něj vloží text.
2) Jako helptext: zobrazí se pod polem, možná až trochu moc nenápadně a blízko dalšího pole, ale text je výraznější
![image](https://user-images.githubusercontent.com/1846915/145982943-a93f8717-e1a7-4d96-8f83-382d1a626e5f.png)

Případně je ještě možnost text přidat přímo do nadpisu pole, tam mi přijde možná až moc výrazný, ale úplně zlé to není.
![image](https://user-images.githubusercontent.com/1846915/145983416-9606a34a-31c1-4401-b1d5-14f57bb7bc81.png)

**Comment by mariehaskovcova** [comment]
nejvíc se nám líbí ten helptext, díky
