### ISSUE TITLE
plánování sklizně - reorganizace pořadí položek

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#614]
Datum
Název
Anotace
Typ sklizně
Nabídka (Archive-it, manuals...)
Tematické kolekce
Mimosystémová semínka
Přiřazené zdroje
Semínka podle frekvence
Tematické kolekce podle frekvence

poslední část by mohla mít název Technická nastavení (duration /budget etc...)

**Comment by zlodejpapiru** [comment]
- chybí název poslední sekce "Technická nastavení"
