### ISSUE TITLE
přidat Cookies consent formulář na WWW

### ISSUE THREAD

**Issue by Fasand** [WebarchivCZ/Seeder#621]
@mariehaskovcova @JanMeritus 
Nejrychlejší a nejjistější řešení je použít: https://www.freeprivacypolicy.com/free-cookie-consent/
V reálu to vypadá takto:
![image](https://user-images.githubusercontent.com/1846915/151979455-add6bcad-f81f-43d5-873b-f77fa115a777.png)

Ten widget podporuje ještě 3 další vizuální rozložení jako banner nahoře, vyskakovací okno apod., ale tohle mi přijde asi jako nejčistější řešení, které není příliš otravné pro uživatele, obzvlášť když to ovlivňuje jenom Google Analytics.

Dole ve footeru je pak tlačítko pro otevření nastavení preferencí:
![image](https://user-images.githubusercontent.com/1846915/151980413-e1cee644-bbf5-4bee-a9be-479c3f57a48a.png)

Dokud uživatel nepotvrdí, že chce cookies, GA script zůstává jako text/plain, tedy nic se nenačítá. Po kliknutí se script přepne na text/javascript a načtou se GA cookies.
Když se uživatel později rozhodne, že nechce trackovací cookies, tak se script bude zase načítat jako text/plain, tedy nic se nebude na GA posílat. Původní GA cookies sice zůstanou, ale už vlastně nejsou k ničemu použity.

Co se týče úprav widgetu: celé UI se načítá z externího javascriptu, takže pokud byste chtěli změnit texty, tak by byla možnost JS soubor stáhnout, upravit a pak načítat lokálně (snad by to nemělo vadit jejich licenci). Barvy a jednoduché stylové úpravy jdou udělat přímo přes CSS bez zásahu do originálního JS souboru.

**Comment by mariehaskovcova** [comment]
moc díky za rychlé zpracování, mně se to takhle líbí. Do textů by se asi zasahovalo, jen kdyby byl požadavek pro standardizované texty na všech webech NK. Pokud to není složité, grafika by mohla korespondovat s webem - písmo/barva.
Poprosím ještě @JanMeritus o názor

**Comment by Fasand** [comment]
Jasně, písmo bych taky možná změnil a barvy jsem zatím nechal, protože by to podle mě trochu splývalo, kdybych použil tu WA modrou na tlačítko bez dalšího odlišení, ale to je kdyžtak relativně jednoduché změnit.
Pokud by NK mělo nějaké standardizované řešení, samozřejmě by se jím dalo nahradit toto řešení a bylo by to pak na všech webech opravdu stejné.

**Comment by mariehaskovcova** [comment]
zatím necháme toto řešení ve standardizované graf. úpravě, jak to máš
