### ISSUE TITLE
vkládání zdroje - klíčová slova

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#627]
při vkládání zdroje (Přidat zdroj) je nepovinná možnost zadat klíčová slova, pokud jsou vyplněna, neuloží se - u hl. záznamu se neobjeví. Možná by při vkládání zdroje možnost vkládání klíčových slov nemusela být vůbec, případně by bylo dobré, aby se propsala do záznamu hl. zdroje

**Comment by Fasand** [comment]
První jsem vůbec nechápal, proč se tam nepropisují při vytváření zdroje, ale pak jsem přišel na to, že jelikož se tam při odeslání formuláře doplňují defaults když něco nebylo nastavené, tak se to nejprve ukládá jakoby "neúplně" a v tom kroku se ta klíčová slova ztratí.
Každopádně vyřešeno, stačilo klíčová slova po uložení znovu nastavit => při vytváření zdroje se tedy nyní budou propisovat klíčová slova, ale zůstanou dále nepovinná.
