### ISSUE TITLE
stav Bez smlouvy

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#628]
pokud kurátor zvolí u smlouvy stav Bez smlouvy, chtěli bychom, aby se u hl. záznamu zdroje změnil jeho stav na Archivován bez smlouvy (nyní se objeví stav Bez smlouvy) 
u hlavního záznamu bychom chtěli stav Bez smlouvy úplně zrušit (poté, co vznikl stav Archivován bez smlouvy, tak nemá smysl)
tzn.:
stav Bez smlouvy (hl. záznam zdroje) = zrušit
stav Bez smlouvy (smlouva) = zůstává

**Comment by Fasand** [comment]
Pro úplnost:

Pokud má zdroj stav "Přijato Webarchivem" a změní se stav jeho smlouvy, tak probíhá konverze:
- Smlouva: "Odmítnuto vydavatelem" => Zdroj: "Odmítnuto vydavatelem"
- Smlouva: "Platná smlouva" => Zdroj: "Archivován"
- Smlouva: "Bez smlouvy" => Zdroj: **"Archivován bez smlouvy"**

V rámci migrace pro zrušení stavu "Bez smlouvy" se u všech existujících zdrojů (a QA kontrol, používají se tam stejné konstanty) změní stav "Bez smlouvy" => "Archivován bez smlouvy". Zároveň jsem stav stejně nahradil všude, kde byl v kódu použit.
Stav Bez smlouvy na smlouvě zůstává netknutý.

**Comment by mariehaskovcova** [comment]
jj, je to tak, jak píšeš
