### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by zlodejpapiru** [WebarchivCZ/Seeder#630]
- vytvořit 404 page
- design přikládám

![wa 404](https://user-images.githubusercontent.com/62152053/169062244-deeb7f64-6650-4825-99db-6a4714c76f71.jpg)

**Comment by mariehaskovcova** [comment]
toto by se mělo objevit jako okno na webu na časové ose, když nám nepoběží wayback, mohla by to být nějaká fce, kterou zaškrtneme v Seederu

**Comment by Fasand** [comment]
Pro upřesnění: 404 se zobrazuje když server běží, ale neexistuje hledaná stránka, e.g. https://app.webarchiv.cz/qwerty
Pokud by se toto mělo zobrazovat spíše při údržbě, použil bych spíše HTTP 503, klidně s podobným nebo jednodušším designem.

@mariehaskovcova mělo by tedy být nějaké zaškrtávátko v Seederu, které když je zaškrtnuté, tak se na všech WWW stránkách zobrazí údržba? Mohl bych to nějak napasovat do Konstant https://app.webarchiv.cz/seeder/json_constants ke kterým mají přístup jen admini.

**Comment by mariehaskovcova** [comment]
jj, to je asi fakt, co kdybysme tam teda dali zatím jen to modré okno s textem? Horní část obrázku? Mělo by to sloužit, když nefunguje časová osa, stává se, že webovky jsou ok, ale časová osa (rámeček) ne. Bylo by těžký eventuálně změnit design obrázku (nahradit ho) dodatečně? (až se nám vrátí autor designu)

asi bych to dala někam, kam mají přístup všichni kurátoři, aby mohl zareagovat operativně každý, kdo je zrovna v práci

**Comment by Fasand** [comment]
Souhlas, zatím bych tedy dal modré pozadí s textem z obrázku (podobně jako na té aktuální 404) a pak můžeme kdyžtak přidat obrázek nebo to nějak upravit.

Co se týče umístění, pokud by k tomu měli mít přístup všichni v Seederu a asi by bylo dobré, aby to bylo nějak výrazně vidět, navrhnul bych dát "Maintenance/Údržba" toggle buď do hodního navbaru nalevo od "Jazyky" nebo do sidebaru, buď úplně nahoru nebo úplně dolů.
Pokud by byla zapnutá údržba, bylo by to výrazně červeně, jinak normálně/šedě. 
Zapnutí/vypnutí by ideálně mělo být s potvrzujícím dialogem, aby to někdo omylem nepřekliknul.

A pak tedy jen pro potvrzení: pokud je údržba zapnutá, tak se prostě na všech WWW stránkách zobrazí ta hláška nebo jen na některých? Tedy i https://www.webarchiv.cz/ hlavní stránka apod.?

**Comment by mariehaskovcova** [comment]
možná do toho sidebaru úplně dolů, souhlasím s potvrzujícím dialogem, aby to nešlo odklepnout omylem

já si představuju, že by to vyskočilo před tu časovou osu na hl. stránce (úvod, obr. 1). I když nefunguje osa, ostatní info na webu je k dispozici uživatelům. Je pravda, že to vyhledávací okno je i na dalších záložkách (malé) vpravo nahoře (obr. 2), nevím, jestli se to automaticky propíše i tam?

![obr  1](https://user-images.githubusercontent.com/19947819/186923064-a77d33ce-949d-4c60-97ba-3fdf93b70f9c.PNG)

![obr  2](https://user-images.githubusercontent.com/19947819/186923077-bf3e6a3c-a8fe-4f46-a417-241d6532e255.PNG)

**Comment by Fasand** [comment]
Ahh, tak to jsem jen předtím nepochopil, co myslíš tou časovou osou 😃 
Takže v principu když nepojede wayback.webarchiv.cz, tak se zapne nějaký systém "údržby" (možná bych so spíš nazval konkrétněji, třeba prostě "Údržba Wayback") a tím pádem by nemělo jít používat vyhledávání na hlavní stránce a v navbaru WWW a zobrazí se tam _nějaká_ hláška – chápu to správně?

Pokud to tak je, pak by mohl nastat problém i třeba na stránce zdroje, v katalogu stránek apod. – zkrátka místa, kde je nějaký prolink na Wayback. 
Možná by to teda mohl být třeba jen néjaký relativně výrazný modrý baner, který by se zobrazil na **všech** stránkách WWW, ale neovlivňoval by zobrazený obsah? Plus by ta vyhledávací pole mohla být třeba vypnuta s nějakou placeholder hláškou, opět třeba "Údržba Wayback" nebo něco, co lidi spíš pochopí.

Rychlý náčrt, jak si to představuji:
![image](https://user-images.githubusercontent.com/1846915/186932745-0a3ddba3-5600-408b-84d1-f542d3be4f8f.png)

**Comment by mariehaskovcova** [comment]
jj, už si rozumíme :D Je fakt, že by ten baner měl být na všech stránkách a možná by nakonec stačil jen ten baner. Posílám návrh textu. V pondělí bysme na to koukli případně s ostatníma. 

text:
Pokud vidíte tuto stránku, probíhá údržba dat a v archivu nelze nyní vyhledávat. Některé linky vrátí chybu.
Prosím zkuste načíst webarchiv později.

Šlo by udělat ten text eventuálně i editovatelný?

**Comment by Fasand** [comment]
Vymyslel jsem to zatím pomocí těch konstant, které se zatím použily jen pro velikost webarchivu. Přidal jsem nějaké typové rozlišování, abych mohl pro tento text zobrazit CKEditor a podle mě by to mohlo být docela použitelné.
![image](https://user-images.githubusercontent.com/1846915/187620333-09cc5208-713a-41f1-8a14-dde47cc69e75.png)

Text by tedy mohl upravit jen superuser a pro zbytek uživatelů přidám ještě nějaký toggle/tlačítko dolů do sidebaru, se kterým se jen vypne/zapne maintenance.

**Comment by mariehaskovcova** [comment]
super, to vypadá dobře
