### ISSUE TITLE
zdroje/export - přidat do tabulky s exportovanými údaji i url adresy

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#631]
bylo by možné přidat do tabulky exportovaných zdrojů sloupeček s url adresami?
https://webarchiv.cz/seeder/source/list

**Comment by Fasand** [comment]
@mariehaskovcova Mohlo by to být třeba takhle?

Filtrované zdroje v Seederu:
![image](https://user-images.githubusercontent.com/1846915/186867021-275b40c6-19f1-4bd0-b150-9fff4f2fb160.png)

Exportovaná data:
![image](https://user-images.githubusercontent.com/1846915/186867104-64576657-5132-4f16-91ca-94b82fc5fe1a.png)

django-tables2, které se používají na tabulky by sice měly podporovat i skrytí sloupce při renderování a zobrazení jen v exportu, ale za boha se mi to nedaří rozjet – buď to je v obou nebo nikde.
Takhle by se v Seederu zobrazil počet seedů u zdroje a v exportu všechny seedy spojené čárkou.

**Comment by mariehaskovcova** [comment]
jj, asi takhle dobrý, díky!
