### ISSUE TITLE
Zdroje, které spravujete - vyjmout stav Archivován bez smlouvy

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#637]
v poli _Zdroje, které spravujete_ na hl. stránce vidí kurátor zdroje, které spravuje, ale ještě nejsou uzavřené, například čekají na smlouvu nebo jsou v procesu hodnocení. Objevují se tam i zdroje, které mají stav _Archivován bez smlouvy_, což znamená, že už jsou uzavřené, tento stav by se tu objevovat neměl

**Comment by Fasand** [comment]
Upraveno v další PR, nyní se budou zobrazovat jen zdroje se stavy: **Hodnocení, Čeká na odpověď, V jednání**
