### ISSUE TITLE
Adding Contract

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#64]
Po výběru typu smlouvy (proprientální) se zobrazí tento error:

ValueError at /contracts/1/create
The view contracts.views.Create didn't return an HttpResponse object. It returned None instead.
Request Method:	POST
Request URL:	http://seeder.visgean.me/contracts/1/create
Django Version:	1.8.2
Exception Type:	ValueError
Exception Value:	
The view contracts.views.Create didn't return an HttpResponse object. It returned None instead.
Exception Location:	/home/seeder/cgi-bin/env/local/lib/python2.7/site-packages/django/core/handlers/base.py in get_response, line 151
Python Executable:	/usr/bin/uwsgi-core
Python Version:	2.7.3
Python Path:	
['/home/seeder/cgi-bin/seeder/Seeder/',
 '.',
 '',
 '/home/seeder/cgi-bin/env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/home/seeder/cgi-bin/env/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/home/seeder/cgi-bin/env/lib/python2.7',
 '/home/seeder/cgi-bin/env/lib/python2.7/plat-linux2',
 '/home/seeder/cgi-bin/env/lib/python2.7/lib-tk',
 '/home/seeder/cgi-bin/env/lib/python2.7/lib-old',
 '/home/seeder/cgi-bin/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/seeder/cgi-bin/env/local/lib/python2.7/site-packages']
Server time:	Thu, 11 Jun 2015 12:57:41 +0000

**Comment by Visgean** [comment]
A smluva se vytvortila?

**Comment by kvasnicaj** [comment]
Vytvořila
