### ISSUE TITLE
změna stavu zdroje na Archivován pro přiřazení k existující smlouvě

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#640]
když je zdroj přiřazován k již existující smlouvě (pole Přiřadit), měl by se stav zdroje automaticky změnit na Archivován (s tím, že zůstává editovatelný)

**Comment by Fasand** [comment]
Bude v novém PR.
**Jen poznámka:** pokud se stav zdroje změní na "Archivován" a nemá nastavenou frekvenci sklízení, bude nadále vyskakovat hláška "Zdroje se stavem 'Archivován' a 'Archivován bez smlouvy' musí mít vybranou Frekvenci sklízení", ale **jen přímo u zdroje**.
Po přiřazení zdroje by tedy bylo dobré zkontrolovat zdroj a případně mu nastavit frekvenci sklízení, pokud ještě není nastavena.
