### ISSUE TITLE
název interní kolekce - našeptávač

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#641]
když se přiřazuje interní kolekce k už existující externí, hodil by se našeptávač, který by nabídl kurátorovi pro interní kolekci stejný název jako  má externí, který si pak může podle potřeby editovat. Částečně to tak je, ale neobjevuje se tam vždycky název ext. kolekce, k níž je interní přiřazovaná - ta by tam měla být na prvním místě

**Comment by Fasand** [comment]
Chápu to správně, že když chci **Přidat (interní) tematickou kolekci**, tak po vybrání externí tematické kolekce by se mi mělo předvyplnit pole "Název" na název vybrané externí tematické kolekce?
![image](https://user-images.githubusercontent.com/1846915/206670609-a07d6c15-6655-4afd-a238-2bae73da487c.png)

Nebo máš na mysli spíš něco ala našeptávač u přiřazování zdroje k tematické kolekci, jen s možností vybrat jen jednu kolekci?
![image](https://user-images.githubusercontent.com/1846915/206670821-2b224e0e-8045-4a64-bea9-8adbc799d138.png)

Plus prosím o dovysvětlení té poslední věty – aktuálně by se názvy interních kolekcí neměly nijak předvyplňovat. Nenabízí ti tam náhodou prohlížeč poslední použité hodnoty přes autocomplete? Ten nemůžu moc ovlivnit, jedině ho na poli vypnout, ale to předvyplnění bych tam dodělal přes trochu JavaScriptu. 
Aby se propsal jak CZ tak EN název, udělal bych interní api endpoint pro externí kolekce a po vybrání některé kolekce (z klasického selectu, jak to je nyní?) bych si natáhl jaký má externí kolekce CZ a EN název. V tomto případě by se mohly rovnou propsat i hodnoty "Anotace" a "Kurátor", které bych čekal, že budou ve většině případů stejné na interní kolekci jako na té externí.

**Comment by mariehaskovcova** [comment]
jj, chtěli bychom to tak, jak píšeš v první variantě - ten příklad s 1. světovou válkou, automaticky se propíše český a anglický název. Ostatní hodnoty automaticky propisovat nechceme (kurátor, anotace), to se může lišit případ od případu

s těmi posledními použitými hodnotami (autocomplete) to tak opravdu možná bylo :)
