### ISSUE TITLE
možnost vkládat hyperlink do popisků tem. kolekcí

### ISSUE THREAD

**Issue by zlodejpapiru** [WebarchivCZ/Seeder#659]
Layout webu neumí zacházet s url adresami ad. screenshot. Prosím o možnost vkládání hyperlinků do popisků tem. kolekcí. 
![Snímek obrazovky 2023-08-29 v 15 59 56](https://github.com/WebarchivCZ/Seeder/assets/62152053/b80e5fb5-7bee-472b-870c-98344fb8d228)

**Comment by mariehaskovcova** [comment]
@zlodejpapiru viz issue #452 - zatím ještě nejsou na produkci, v testu už máme
