### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#66]
Velmi často se stává, že text přeteče z rámečku. Dělá to na menším rozlišení (nb) 

Namátkově je to u zdroje: seznam semínek, karta publisher: kontakt

**Comment by kvasnicaj** [comment]
Například na kartě zdroje, jak jsou ty barevné tlačítka, tak text nepřeteče, ale schová. Takto by to mělo být podle mě všude

**Comment by kvasnicaj** [comment]
![pretekani_textu](https://cloud.githubusercontent.com/assets/10117117/8107695/8ac98106-104b-11e5-8aea-84e32ade8941.png)

**Comment by Visgean** [comment]
Jake je to rozliseni? Popravde uplne moc nevim jak se to chova na retine, zkusim to vykoumat...

**Comment by kvasnicaj** [comment]
Je to klasické 1366 × 768, mám macbook air bez retiny

**Comment by Visgean** [comment]
On je problem, ze se to snazim optimalizovat na vicero displeju vcetne mobilnich, primarne bych se tedy mel snazit o jaka rozliseni?

**Comment by westfood** [comment]
Myslím že to pojede spíš z monitorů v NK a asi i v zahraničí. A ty už jedou
větší rozlišení.

Dne pátek 12. června 2015 Visgean Skeloru <notifications@github.com>
napsal(a):

**Comment by Visgean** [comment]
![screenshot from 2015-06-16 18 40 52](https://cloud.githubusercontent.com/assets/193832/8188618/4297ceb4-1457-11e5-89a5-dff2900e78c9.png)
