### ISSUE TITLE
Publishers - smazat

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#69]
Není možné smazat vydavatele. Při mazání vydavatele aktuálně ve starém adminu smažeme jeho propojení na zdroj (u více zdrojů smažeme pouze propojení, ale vydavatel zůstává - zdroj bez propojení má pak prázdného vydavatele, kterého je třeba doplnit), pokud je jen jeden vydavatel s jedním zdrojem - smažeme vydavatele a zdroj zůstává zase s prázdným vydavatelem.

**Comment by Visgean** [comment]
A proc je potreba mazat vydavatele? Muzu tam dat policko ze je neaktivni a tim ho vyradit z katalogu...
