### ISSUE TITLE
Contract number

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#70]
Contract number (1/2015 atd.) musí být přiděleno, až v posledním kroce (contract accepted). Když je smlouvy v Contract in negotiation, tak ještě toto číslo nesmí být přiděleno. Důvodem je nutnost zachování číselné posloupnosti u smluv. Pokud by smlouva, která je v jednání nakonec neprošla, tak se tato posloupnost narušena.

**Comment by kvasnicaj** [comment]
Ještě pro jistotu dodám, že contract number se vždy nuluje na začátku kalendářního roku.

**Comment by Visgean** [comment]
A nemam to pridelovani cisel smluv nechat kompletne na kuratorech? predopkladam ze uz primo v nejake vasem sytemu pridelite te smlouve to cislo... Takhle je to pomerne problematicka zalezitost kdy to cislo pridelit (byt to neni prace na dlouho ale bojim se spis aby to nahodou nedelalo problemy....)
