### ISSUE TITLE
Prioritní zdroj

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/Seeder#702]
měli bychom rádi u záznamu zdroje fci / tlačítko, které by umožnilo označit zdroj za prioritu (podobně jako třeba Mrtvý web). Chtěli bychom, aby se to promítlo také v Nastavení filtrů a bylo možné na základě toho vylistovat a exportovat seznam zdrojů

**Comment by Fasand** [comment]
Přidal jsem Source.priority_source na vzor mrtvého webu, viz níže. Pokud byste to chtěli spíš formou tlačítka s potvrzením, taky to jde. Bude v PR #699 

![image](https://github.com/user-attachments/assets/2802496c-3675-45dc-8034-374ca82b4574)
![image](https://github.com/user-attachments/assets/f20eb25a-904b-4b83-9bbf-e00b07d4e8df)
![image](https://github.com/user-attachments/assets/bce5d9c0-b475-47ce-9f4e-6258ce8b0110)

**Comment by mariehaskovcova** [comment]
otestováno, ok, zavírám
