### ISSUE TITLE
Add source - Open License

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#75]
Pokud zaškrtnu u přidání zdroje licenci, není pak nikde ta informace v záznamu zdroje vidět.

**Comment by Visgean** [comment]
Neni, vytvori se rovnou nova smlouva/license ktera ma nastaveno ze je validni a typu CC, po uspesnem hlasovani tak prejde stav rovnou do uspesneho archivovani...

**Comment by bjackova** [comment]
OK, ale chce to, aby to bylo pro kurátory vidět, může to ovlivnit hlasování (s licencí je větší šance, že budeme chtít archivovat).

**Comment by Visgean** [comment]
OK, zmenim popisek licensi aby to zobrazovalo v odkazech atp, ze je to Creative commons a pridam to do popisku hlasovani..
