### ISSUE TITLE
Add seeds - invalid URL

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/Seeder#76]
Pokud zadám do semínek špatnou URL, např. http://www.cshry. nebo http://www.decin, nehlásí chybu a přidá URL v tomto tvaru.

**Comment by Visgean** [comment]
Ona to totiz neni chyba, tohle nejde uplne overit, ta kontrola uz se deje na urovni prohlizece takze ti to ani nedovoli odeslat nevalidni url.

Problem ovsem je s tim, ze www.decin je naprosto validni domenove jmeno, viz http://www.newtldlist.com/ , s tim ja moc neudelam....

**Comment by westfood** [comment]
A neměl by mít ten checker seznam tld? Vím že je voser s aktualizací tld,
ale není už hotové nějaké elegantní řešení? Případně jen výstraha že člověk
vkládá nestandardní URL. Myslím že nečekáme sklizeň URL s lokálníma
adresama.

A poradí si to s IP adresama?;-) pár jich mezi semínkama máme.

Dne pátek 12. června 2015 Visgean Skeloru <notifications@github.com>
napsal(a):
