### ISSUE TITLE
Proverit stavajici data

### ISSUE THREAD

**Issue by Visgean** [WebArchivCZ/Seeder#80]
V tabulce contacts maji nasledujici id neplatnou hodnotu Publisher_id - odkazuji se na publishers ktere uz neexistuji....

33, 112, 156, 169, 199, 253, 337, 352, 353, 377, 381, 564, 720, 894, 899, 1265, 1367, 1804, 1833, 1841, 1907, 2052, 2099, 2224, 2315, 2538, 2737, 3076, 3104, 3127, 3320, 3512, 3529, 3546, 3583, 3610, 3678, 3710, 3721, 3744, 3839, 3864, 3869, 3959, 3962, 3965, 3990, 4069, 4100, 4126, 4134, 4137, 4149, 4180, 4223, 4237, 4256, 4277, 4282, 4308, 4332, 4407, 4493, 4742, 4759, 4840, 4842, 4875, 4910, 4939, 4940, 4967, 5038, 5046, 5072, 5077, 5086, 5198, 5304, 5324, 5325, 5360, 5361, 5444, 5445, 5446, 5447, 5448, 5495, 5522, 5570, 5616, 5681, 5741, 5777, 5840, 5870, 5915, 5922, 6103, 6138, 6225, 6286, 6493, 6635, 6636, 6646, 6894, 6977, 7001, 7142, 7221, 7366, 7408, 7552, 7617

**Comment by kvasnicaj** [comment]
Hele to je divný, já jsem projel náhodně některé zdroje, co jsi vypsal a všechny zdroje mají existujícího publishera. 

konkrétně: 33, 112, 3965, 5870 a všichni mají svého existujícího publishera

**Comment by kvasnicaj** [comment]
tak jsme to prověřili a jedná se o kontakty, které zůstaly po smazání publishera. Tzn. že současný admin při mazání publishera, nesmaže jeho kontakty a ty tam pak visí. Takže ty kontakty můžeš s klidem zahodit

**Comment by Visgean** [comment]
ok
