### ISSUE TITLE
Retired users

### ISSUE THREAD

**Issue by kvasnicaj** [WebArchivCZ/Seeder#99]
Staří a neaktivní uživatelé by měly mít zmražené účty, tzn. neměli by se zobrazovat v nabídce pro přidělení zdrojů a nesmějí mít možnost se do systému přihlásit, tedy ani hlasovat - nic.
Ale musí v systému zůstat, tzn. u zdrojů, které v minulosti spravovali budou stále uvedení. 

V předchozí verzi to fungovalo tak, že se u uživatele definovala role (např. curator - mohl tedy spravovat zdroje) a nastavovalo se časové rozmezí, kdy je účet aktivní. Pokud byl účet aktivní, pak se ukazoval v hlasování atd. 

Je nutné nutné kvůli tomu, že kurátoři odcházejí (výpověď) a přicházejí, někteří opakovaně (mateřská dovolená).

edit: ještě doplním, že administrátor by měl možnost tuto funkcionalitu spravovat

**Comment by Visgean** [comment]
Ted staci v administraci nastavit ze je uzivatel aktivni
